// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DecryptGroups.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Decrypted version of Member
// Keep field numbers in step
type DecryptedMember struct {
	Uuid                 []byte      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Role                 Member_Role `protobuf:"varint,2,opt,name=role,proto3,enum=Member_Role" json:"role,omitempty"`
	ProfileKey           []byte      `protobuf:"bytes,3,opt,name=profileKey,proto3" json:"profileKey,omitempty"`
	JoinedAtRevision     uint32      `protobuf:"varint,5,opt,name=joinedAtRevision,proto3" json:"joinedAtRevision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DecryptedMember) Reset()         { *m = DecryptedMember{} }
func (m *DecryptedMember) String() string { return proto.CompactTextString(m) }
func (*DecryptedMember) ProtoMessage()    {}
func (*DecryptedMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{0}
}

func (m *DecryptedMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedMember.Unmarshal(m, b)
}
func (m *DecryptedMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedMember.Marshal(b, m, deterministic)
}
func (m *DecryptedMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedMember.Merge(m, src)
}
func (m *DecryptedMember) XXX_Size() int {
	return xxx_messageInfo_DecryptedMember.Size(m)
}
func (m *DecryptedMember) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedMember.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedMember proto.InternalMessageInfo

func (m *DecryptedMember) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *DecryptedMember) GetRole() Member_Role {
	if m != nil {
		return m.Role
	}
	return Member_UNKNOWN
}

func (m *DecryptedMember) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *DecryptedMember) GetJoinedAtRevision() uint32 {
	if m != nil {
		return m.JoinedAtRevision
	}
	return 0
}

type DecryptedPendingMember struct {
	Uuid                 []byte      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Role                 Member_Role `protobuf:"varint,2,opt,name=role,proto3,enum=Member_Role" json:"role,omitempty"`
	AddedByUuid          []byte      `protobuf:"bytes,3,opt,name=addedByUuid,proto3" json:"addedByUuid,omitempty"`
	Timestamp            uint64      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UuidCipherText       []byte      `protobuf:"bytes,5,opt,name=uuidCipherText,proto3" json:"uuidCipherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DecryptedPendingMember) Reset()         { *m = DecryptedPendingMember{} }
func (m *DecryptedPendingMember) String() string { return proto.CompactTextString(m) }
func (*DecryptedPendingMember) ProtoMessage()    {}
func (*DecryptedPendingMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{1}
}

func (m *DecryptedPendingMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedPendingMember.Unmarshal(m, b)
}
func (m *DecryptedPendingMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedPendingMember.Marshal(b, m, deterministic)
}
func (m *DecryptedPendingMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedPendingMember.Merge(m, src)
}
func (m *DecryptedPendingMember) XXX_Size() int {
	return xxx_messageInfo_DecryptedPendingMember.Size(m)
}
func (m *DecryptedPendingMember) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedPendingMember.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedPendingMember proto.InternalMessageInfo

func (m *DecryptedPendingMember) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *DecryptedPendingMember) GetRole() Member_Role {
	if m != nil {
		return m.Role
	}
	return Member_UNKNOWN
}

func (m *DecryptedPendingMember) GetAddedByUuid() []byte {
	if m != nil {
		return m.AddedByUuid
	}
	return nil
}

func (m *DecryptedPendingMember) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DecryptedPendingMember) GetUuidCipherText() []byte {
	if m != nil {
		return m.UuidCipherText
	}
	return nil
}

type DecryptedRequestingMember struct {
	Uuid                 []byte   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ProfileKey           []byte   `protobuf:"bytes,2,opt,name=profileKey,proto3" json:"profileKey,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptedRequestingMember) Reset()         { *m = DecryptedRequestingMember{} }
func (m *DecryptedRequestingMember) String() string { return proto.CompactTextString(m) }
func (*DecryptedRequestingMember) ProtoMessage()    {}
func (*DecryptedRequestingMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{2}
}

func (m *DecryptedRequestingMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedRequestingMember.Unmarshal(m, b)
}
func (m *DecryptedRequestingMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedRequestingMember.Marshal(b, m, deterministic)
}
func (m *DecryptedRequestingMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedRequestingMember.Merge(m, src)
}
func (m *DecryptedRequestingMember) XXX_Size() int {
	return xxx_messageInfo_DecryptedRequestingMember.Size(m)
}
func (m *DecryptedRequestingMember) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedRequestingMember.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedRequestingMember proto.InternalMessageInfo

func (m *DecryptedRequestingMember) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *DecryptedRequestingMember) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *DecryptedRequestingMember) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type DecryptedPendingMemberRemoval struct {
	Uuid                 []byte   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UuidCipherText       []byte   `protobuf:"bytes,2,opt,name=uuidCipherText,proto3" json:"uuidCipherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptedPendingMemberRemoval) Reset()         { *m = DecryptedPendingMemberRemoval{} }
func (m *DecryptedPendingMemberRemoval) String() string { return proto.CompactTextString(m) }
func (*DecryptedPendingMemberRemoval) ProtoMessage()    {}
func (*DecryptedPendingMemberRemoval) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{3}
}

func (m *DecryptedPendingMemberRemoval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedPendingMemberRemoval.Unmarshal(m, b)
}
func (m *DecryptedPendingMemberRemoval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedPendingMemberRemoval.Marshal(b, m, deterministic)
}
func (m *DecryptedPendingMemberRemoval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedPendingMemberRemoval.Merge(m, src)
}
func (m *DecryptedPendingMemberRemoval) XXX_Size() int {
	return xxx_messageInfo_DecryptedPendingMemberRemoval.Size(m)
}
func (m *DecryptedPendingMemberRemoval) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedPendingMemberRemoval.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedPendingMemberRemoval proto.InternalMessageInfo

func (m *DecryptedPendingMemberRemoval) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *DecryptedPendingMemberRemoval) GetUuidCipherText() []byte {
	if m != nil {
		return m.UuidCipherText
	}
	return nil
}

type DecryptedApproveMember struct {
	Uuid                 []byte      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Role                 Member_Role `protobuf:"varint,2,opt,name=role,proto3,enum=Member_Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DecryptedApproveMember) Reset()         { *m = DecryptedApproveMember{} }
func (m *DecryptedApproveMember) String() string { return proto.CompactTextString(m) }
func (*DecryptedApproveMember) ProtoMessage()    {}
func (*DecryptedApproveMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{4}
}

func (m *DecryptedApproveMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedApproveMember.Unmarshal(m, b)
}
func (m *DecryptedApproveMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedApproveMember.Marshal(b, m, deterministic)
}
func (m *DecryptedApproveMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedApproveMember.Merge(m, src)
}
func (m *DecryptedApproveMember) XXX_Size() int {
	return xxx_messageInfo_DecryptedApproveMember.Size(m)
}
func (m *DecryptedApproveMember) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedApproveMember.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedApproveMember proto.InternalMessageInfo

func (m *DecryptedApproveMember) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *DecryptedApproveMember) GetRole() Member_Role {
	if m != nil {
		return m.Role
	}
	return Member_UNKNOWN
}

type DecryptedModifyMemberRole struct {
	Uuid                 []byte      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Role                 Member_Role `protobuf:"varint,2,opt,name=role,proto3,enum=Member_Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DecryptedModifyMemberRole) Reset()         { *m = DecryptedModifyMemberRole{} }
func (m *DecryptedModifyMemberRole) String() string { return proto.CompactTextString(m) }
func (*DecryptedModifyMemberRole) ProtoMessage()    {}
func (*DecryptedModifyMemberRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{5}
}

func (m *DecryptedModifyMemberRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedModifyMemberRole.Unmarshal(m, b)
}
func (m *DecryptedModifyMemberRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedModifyMemberRole.Marshal(b, m, deterministic)
}
func (m *DecryptedModifyMemberRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedModifyMemberRole.Merge(m, src)
}
func (m *DecryptedModifyMemberRole) XXX_Size() int {
	return xxx_messageInfo_DecryptedModifyMemberRole.Size(m)
}
func (m *DecryptedModifyMemberRole) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedModifyMemberRole.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedModifyMemberRole proto.InternalMessageInfo

func (m *DecryptedModifyMemberRole) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *DecryptedModifyMemberRole) GetRole() Member_Role {
	if m != nil {
		return m.Role
	}
	return Member_UNKNOWN
}

// Decrypted version of message Group
// Keep field numbers in step
type DecryptedGroup struct {
	Title                     string                       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Avatar                    string                       `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	DisappearingMessagesTimer *DecryptedTimer              `protobuf:"bytes,4,opt,name=disappearingMessagesTimer,proto3" json:"disappearingMessagesTimer,omitempty"`
	AccessControl             *AccessControl               `protobuf:"bytes,5,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	Revision                  uint32                       `protobuf:"varint,6,opt,name=revision,proto3" json:"revision,omitempty"`
	Members                   []*DecryptedMember           `protobuf:"bytes,7,rep,name=members,proto3" json:"members,omitempty"`
	PendingMembers            []*DecryptedPendingMember    `protobuf:"bytes,8,rep,name=pendingMembers,proto3" json:"pendingMembers,omitempty"`
	RequestingMembers         []*DecryptedRequestingMember `protobuf:"bytes,9,rep,name=requestingMembers,proto3" json:"requestingMembers,omitempty"`
	InviteLinkPassword        []byte                       `protobuf:"bytes,10,opt,name=inviteLinkPassword,proto3" json:"inviteLinkPassword,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                     `json:"-"`
	XXX_unrecognized          []byte                       `json:"-"`
	XXX_sizecache             int32                        `json:"-"`
}

func (m *DecryptedGroup) Reset()         { *m = DecryptedGroup{} }
func (m *DecryptedGroup) String() string { return proto.CompactTextString(m) }
func (*DecryptedGroup) ProtoMessage()    {}
func (*DecryptedGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{6}
}

func (m *DecryptedGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedGroup.Unmarshal(m, b)
}
func (m *DecryptedGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedGroup.Marshal(b, m, deterministic)
}
func (m *DecryptedGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedGroup.Merge(m, src)
}
func (m *DecryptedGroup) XXX_Size() int {
	return xxx_messageInfo_DecryptedGroup.Size(m)
}
func (m *DecryptedGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedGroup.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedGroup proto.InternalMessageInfo

func (m *DecryptedGroup) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DecryptedGroup) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *DecryptedGroup) GetDisappearingMessagesTimer() *DecryptedTimer {
	if m != nil {
		return m.DisappearingMessagesTimer
	}
	return nil
}

func (m *DecryptedGroup) GetAccessControl() *AccessControl {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

func (m *DecryptedGroup) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *DecryptedGroup) GetMembers() []*DecryptedMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *DecryptedGroup) GetPendingMembers() []*DecryptedPendingMember {
	if m != nil {
		return m.PendingMembers
	}
	return nil
}

func (m *DecryptedGroup) GetRequestingMembers() []*DecryptedRequestingMember {
	if m != nil {
		return m.RequestingMembers
	}
	return nil
}

func (m *DecryptedGroup) GetInviteLinkPassword() []byte {
	if m != nil {
		return m.InviteLinkPassword
	}
	return nil
}

// Decrypted version of message GroupChange.Actions
// Keep field numbers in step
type DecryptedGroupChange struct {
	Editor                   []byte                           `protobuf:"bytes,1,opt,name=editor,proto3" json:"editor,omitempty"`
	Revision                 uint32                           `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	NewMembers               []*DecryptedMember               `protobuf:"bytes,3,rep,name=newMembers,proto3" json:"newMembers,omitempty"`
	DeleteMembers            [][]byte                         `protobuf:"bytes,4,rep,name=deleteMembers,proto3" json:"deleteMembers,omitempty"`
	ModifyMemberRoles        []*DecryptedModifyMemberRole     `protobuf:"bytes,5,rep,name=modifyMemberRoles,proto3" json:"modifyMemberRoles,omitempty"`
	ModifiedProfileKeys      []*DecryptedMember               `protobuf:"bytes,6,rep,name=modifiedProfileKeys,proto3" json:"modifiedProfileKeys,omitempty"`
	NewPendingMembers        []*DecryptedPendingMember        `protobuf:"bytes,7,rep,name=newPendingMembers,proto3" json:"newPendingMembers,omitempty"`
	DeletePendingMembers     []*DecryptedPendingMemberRemoval `protobuf:"bytes,8,rep,name=deletePendingMembers,proto3" json:"deletePendingMembers,omitempty"`
	PromotePendingMembers    []*DecryptedMember               `protobuf:"bytes,9,rep,name=promotePendingMembers,proto3" json:"promotePendingMembers,omitempty"`
	NewTitle                 *DecryptedString                 `protobuf:"bytes,10,opt,name=newTitle,proto3" json:"newTitle,omitempty"`
	NewAvatar                *DecryptedString                 `protobuf:"bytes,11,opt,name=newAvatar,proto3" json:"newAvatar,omitempty"`
	NewTimer                 *DecryptedTimer                  `protobuf:"bytes,12,opt,name=newTimer,proto3" json:"newTimer,omitempty"`
	NewAttributeAccess       AccessControl_AccessRequired     `protobuf:"varint,13,opt,name=newAttributeAccess,proto3,enum=AccessControl_AccessRequired" json:"newAttributeAccess,omitempty"`
	NewMemberAccess          AccessControl_AccessRequired     `protobuf:"varint,14,opt,name=newMemberAccess,proto3,enum=AccessControl_AccessRequired" json:"newMemberAccess,omitempty"`
	NewInviteLinkAccess      AccessControl_AccessRequired     `protobuf:"varint,15,opt,name=newInviteLinkAccess,proto3,enum=AccessControl_AccessRequired" json:"newInviteLinkAccess,omitempty"`
	NewRequestingMembers     []*DecryptedRequestingMember     `protobuf:"bytes,16,rep,name=newRequestingMembers,proto3" json:"newRequestingMembers,omitempty"`
	DeleteRequestingMembers  [][]byte                         `protobuf:"bytes,17,rep,name=deleteRequestingMembers,proto3" json:"deleteRequestingMembers,omitempty"`
	PromoteRequestingMembers []*DecryptedApproveMember        `protobuf:"bytes,18,rep,name=promoteRequestingMembers,proto3" json:"promoteRequestingMembers,omitempty"`
	NewInviteLinkPassword    []byte                           `protobuf:"bytes,19,opt,name=newInviteLinkPassword,proto3" json:"newInviteLinkPassword,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                         `json:"-"`
	XXX_unrecognized         []byte                           `json:"-"`
	XXX_sizecache            int32                            `json:"-"`
}

func (m *DecryptedGroupChange) Reset()         { *m = DecryptedGroupChange{} }
func (m *DecryptedGroupChange) String() string { return proto.CompactTextString(m) }
func (*DecryptedGroupChange) ProtoMessage()    {}
func (*DecryptedGroupChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{7}
}

func (m *DecryptedGroupChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedGroupChange.Unmarshal(m, b)
}
func (m *DecryptedGroupChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedGroupChange.Marshal(b, m, deterministic)
}
func (m *DecryptedGroupChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedGroupChange.Merge(m, src)
}
func (m *DecryptedGroupChange) XXX_Size() int {
	return xxx_messageInfo_DecryptedGroupChange.Size(m)
}
func (m *DecryptedGroupChange) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedGroupChange.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedGroupChange proto.InternalMessageInfo

func (m *DecryptedGroupChange) GetEditor() []byte {
	if m != nil {
		return m.Editor
	}
	return nil
}

func (m *DecryptedGroupChange) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *DecryptedGroupChange) GetNewMembers() []*DecryptedMember {
	if m != nil {
		return m.NewMembers
	}
	return nil
}

func (m *DecryptedGroupChange) GetDeleteMembers() [][]byte {
	if m != nil {
		return m.DeleteMembers
	}
	return nil
}

func (m *DecryptedGroupChange) GetModifyMemberRoles() []*DecryptedModifyMemberRole {
	if m != nil {
		return m.ModifyMemberRoles
	}
	return nil
}

func (m *DecryptedGroupChange) GetModifiedProfileKeys() []*DecryptedMember {
	if m != nil {
		return m.ModifiedProfileKeys
	}
	return nil
}

func (m *DecryptedGroupChange) GetNewPendingMembers() []*DecryptedPendingMember {
	if m != nil {
		return m.NewPendingMembers
	}
	return nil
}

func (m *DecryptedGroupChange) GetDeletePendingMembers() []*DecryptedPendingMemberRemoval {
	if m != nil {
		return m.DeletePendingMembers
	}
	return nil
}

func (m *DecryptedGroupChange) GetPromotePendingMembers() []*DecryptedMember {
	if m != nil {
		return m.PromotePendingMembers
	}
	return nil
}

func (m *DecryptedGroupChange) GetNewTitle() *DecryptedString {
	if m != nil {
		return m.NewTitle
	}
	return nil
}

func (m *DecryptedGroupChange) GetNewAvatar() *DecryptedString {
	if m != nil {
		return m.NewAvatar
	}
	return nil
}

func (m *DecryptedGroupChange) GetNewTimer() *DecryptedTimer {
	if m != nil {
		return m.NewTimer
	}
	return nil
}

func (m *DecryptedGroupChange) GetNewAttributeAccess() AccessControl_AccessRequired {
	if m != nil {
		return m.NewAttributeAccess
	}
	return AccessControl_UNKNOWN
}

func (m *DecryptedGroupChange) GetNewMemberAccess() AccessControl_AccessRequired {
	if m != nil {
		return m.NewMemberAccess
	}
	return AccessControl_UNKNOWN
}

func (m *DecryptedGroupChange) GetNewInviteLinkAccess() AccessControl_AccessRequired {
	if m != nil {
		return m.NewInviteLinkAccess
	}
	return AccessControl_UNKNOWN
}

func (m *DecryptedGroupChange) GetNewRequestingMembers() []*DecryptedRequestingMember {
	if m != nil {
		return m.NewRequestingMembers
	}
	return nil
}

func (m *DecryptedGroupChange) GetDeleteRequestingMembers() [][]byte {
	if m != nil {
		return m.DeleteRequestingMembers
	}
	return nil
}

func (m *DecryptedGroupChange) GetPromoteRequestingMembers() []*DecryptedApproveMember {
	if m != nil {
		return m.PromoteRequestingMembers
	}
	return nil
}

func (m *DecryptedGroupChange) GetNewInviteLinkPassword() []byte {
	if m != nil {
		return m.NewInviteLinkPassword
	}
	return nil
}

type DecryptedString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptedString) Reset()         { *m = DecryptedString{} }
func (m *DecryptedString) String() string { return proto.CompactTextString(m) }
func (*DecryptedString) ProtoMessage()    {}
func (*DecryptedString) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{8}
}

func (m *DecryptedString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedString.Unmarshal(m, b)
}
func (m *DecryptedString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedString.Marshal(b, m, deterministic)
}
func (m *DecryptedString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedString.Merge(m, src)
}
func (m *DecryptedString) XXX_Size() int {
	return xxx_messageInfo_DecryptedString.Size(m)
}
func (m *DecryptedString) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedString.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedString proto.InternalMessageInfo

func (m *DecryptedString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DecryptedTimer struct {
	Duration             uint32   `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptedTimer) Reset()         { *m = DecryptedTimer{} }
func (m *DecryptedTimer) String() string { return proto.CompactTextString(m) }
func (*DecryptedTimer) ProtoMessage()    {}
func (*DecryptedTimer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{9}
}

func (m *DecryptedTimer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedTimer.Unmarshal(m, b)
}
func (m *DecryptedTimer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedTimer.Marshal(b, m, deterministic)
}
func (m *DecryptedTimer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedTimer.Merge(m, src)
}
func (m *DecryptedTimer) XXX_Size() int {
	return xxx_messageInfo_DecryptedTimer.Size(m)
}
func (m *DecryptedTimer) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedTimer.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedTimer proto.InternalMessageInfo

func (m *DecryptedTimer) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type DecryptedGroupJoinInfo struct {
	Title                string                       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Avatar               string                       `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	MemberCount          uint32                       `protobuf:"varint,4,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	AddFromInviteLink    AccessControl_AccessRequired `protobuf:"varint,5,opt,name=addFromInviteLink,proto3,enum=AccessControl_AccessRequired" json:"addFromInviteLink,omitempty"`
	Revision             uint32                       `protobuf:"varint,6,opt,name=revision,proto3" json:"revision,omitempty"`
	PendingAdminApproval bool                         `protobuf:"varint,7,opt,name=pendingAdminApproval,proto3" json:"pendingAdminApproval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DecryptedGroupJoinInfo) Reset()         { *m = DecryptedGroupJoinInfo{} }
func (m *DecryptedGroupJoinInfo) String() string { return proto.CompactTextString(m) }
func (*DecryptedGroupJoinInfo) ProtoMessage()    {}
func (*DecryptedGroupJoinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4195e4d51187a6b, []int{10}
}

func (m *DecryptedGroupJoinInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptedGroupJoinInfo.Unmarshal(m, b)
}
func (m *DecryptedGroupJoinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptedGroupJoinInfo.Marshal(b, m, deterministic)
}
func (m *DecryptedGroupJoinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptedGroupJoinInfo.Merge(m, src)
}
func (m *DecryptedGroupJoinInfo) XXX_Size() int {
	return xxx_messageInfo_DecryptedGroupJoinInfo.Size(m)
}
func (m *DecryptedGroupJoinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptedGroupJoinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptedGroupJoinInfo proto.InternalMessageInfo

func (m *DecryptedGroupJoinInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DecryptedGroupJoinInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *DecryptedGroupJoinInfo) GetMemberCount() uint32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func (m *DecryptedGroupJoinInfo) GetAddFromInviteLink() AccessControl_AccessRequired {
	if m != nil {
		return m.AddFromInviteLink
	}
	return AccessControl_UNKNOWN
}

func (m *DecryptedGroupJoinInfo) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *DecryptedGroupJoinInfo) GetPendingAdminApproval() bool {
	if m != nil {
		return m.PendingAdminApproval
	}
	return false
}

func init() {
	proto.RegisterType((*DecryptedMember)(nil), "DecryptedMember")
	proto.RegisterType((*DecryptedPendingMember)(nil), "DecryptedPendingMember")
	proto.RegisterType((*DecryptedRequestingMember)(nil), "DecryptedRequestingMember")
	proto.RegisterType((*DecryptedPendingMemberRemoval)(nil), "DecryptedPendingMemberRemoval")
	proto.RegisterType((*DecryptedApproveMember)(nil), "DecryptedApproveMember")
	proto.RegisterType((*DecryptedModifyMemberRole)(nil), "DecryptedModifyMemberRole")
	proto.RegisterType((*DecryptedGroup)(nil), "DecryptedGroup")
	proto.RegisterType((*DecryptedGroupChange)(nil), "DecryptedGroupChange")
	proto.RegisterType((*DecryptedString)(nil), "DecryptedString")
	proto.RegisterType((*DecryptedTimer)(nil), "DecryptedTimer")
	proto.RegisterType((*DecryptedGroupJoinInfo)(nil), "DecryptedGroupJoinInfo")
}

func init() { proto.RegisterFile("DecryptGroups.proto", fileDescriptor_e4195e4d51187a6b) }

var fileDescriptor_e4195e4d51187a6b = []byte{
	// 935 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x73, 0xdb, 0x44,
	0x10, 0x1f, 0xd9, 0x4e, 0x62, 0xaf, 0xff, 0x24, 0xb9, 0xb8, 0xad, 0x9a, 0xa1, 0x1d, 0x8d, 0x87,
	0x01, 0x4f, 0x29, 0x1a, 0xc6, 0xf4, 0x81, 0x37, 0x70, 0x02, 0x2d, 0xa5, 0xa4, 0x98, 0x6b, 0x78,
	0x81, 0x27, 0xc5, 0xda, 0xb8, 0x07, 0xd2, 0x9d, 0xb8, 0x3b, 0xdb, 0xe4, 0x03, 0xf0, 0x09, 0x78,
	0xe5, 0x73, 0xf0, 0x11, 0xf8, 0x5c, 0x8c, 0x4e, 0xb2, 0x22, 0xeb, 0x8f, 0x5b, 0xda, 0x37, 0xdf,
	0xde, 0xfe, 0xd6, 0x7b, 0xbb, 0xbf, 0xdf, 0xae, 0xe0, 0xe4, 0x6b, 0x9c, 0xcb, 0x9b, 0x48, 0x3f,
	0x93, 0x62, 0x19, 0x29, 0x37, 0x92, 0x42, 0x8b, 0xd3, 0x5e, 0xfe, 0x34, 0xfa, 0xcb, 0x82, 0xc3,
	0xd4, 0x0b, 0xfd, 0x0b, 0x0c, 0xaf, 0x50, 0x12, 0x02, 0xad, 0xe5, 0x92, 0xf9, 0xb6, 0xe5, 0x58,
	0xe3, 0x1e, 0x35, 0xbf, 0x89, 0x03, 0x2d, 0x29, 0x02, 0xb4, 0x1b, 0x8e, 0x35, 0x1e, 0x4c, 0x7a,
	0x6e, 0xe2, 0xea, 0x52, 0x11, 0x20, 0x35, 0x37, 0xe4, 0x21, 0x40, 0x24, 0xc5, 0x35, 0x0b, 0xf0,
	0x05, 0xde, 0xd8, 0x4d, 0x83, 0xcd, 0x59, 0xc8, 0x23, 0x38, 0xfa, 0x55, 0x30, 0x8e, 0xfe, 0x54,
	0x53, 0x5c, 0x31, 0xc5, 0x04, 0xb7, 0xf7, 0x1c, 0x6b, 0xdc, 0xa7, 0x25, 0xfb, 0xe8, 0x1f, 0x0b,
	0xee, 0x66, 0x59, 0xcd, 0x90, 0xfb, 0x8c, 0x2f, 0xde, 0x2b, 0x39, 0x07, 0xba, 0x9e, 0xef, 0xa3,
	0x7f, 0x76, 0xf3, 0x53, 0x0c, 0x4e, 0xb2, 0xcb, 0x9b, 0xc8, 0x07, 0xd0, 0xd1, 0x2c, 0x44, 0xa5,
	0xbd, 0x30, 0xb2, 0x5b, 0x8e, 0x35, 0x6e, 0xd1, 0x5b, 0x03, 0xf9, 0x08, 0x06, 0xf1, 0x3f, 0x9d,
	0xb3, 0xe8, 0x35, 0xca, 0x4b, 0xfc, 0x43, 0x9b, 0xd4, 0x7b, 0xb4, 0x60, 0x1d, 0x85, 0x70, 0x3f,
	0xcb, 0x9b, 0xe2, 0xef, 0x4b, 0x54, 0x7a, 0x77, 0xea, 0xdb, 0x55, 0x6b, 0x94, 0xaa, 0xb6, 0x33,
	0xad, 0xd1, 0x2f, 0xf0, 0xa0, 0xba, 0x4c, 0x14, 0x43, 0xb1, 0xf2, 0x82, 0xca, 0xbf, 0x2c, 0xbf,
	0xa5, 0x51, 0xf9, 0x96, 0x97, 0xb9, 0x1e, 0x4c, 0xa3, 0x48, 0x8a, 0x15, 0xbe, 0x4f, 0x0f, 0x46,
	0x3f, 0xe6, 0x6a, 0x73, 0x21, 0x7c, 0x76, 0x7d, 0x93, 0xe6, 0x1a, 0x37, 0xe8, 0xdd, 0x42, 0xfe,
	0xdb, 0x84, 0x41, 0x16, 0xd3, 0xf0, 0x9a, 0x0c, 0x61, 0x4f, 0x33, 0x9d, 0xa2, 0x3a, 0x34, 0x39,
	0x90, 0xbb, 0xb0, 0xef, 0xad, 0x3c, 0xed, 0x49, 0xd3, 0xfa, 0x0e, 0x4d, 0x4f, 0xe4, 0x02, 0xee,
	0xfb, 0x4c, 0x79, 0x51, 0x84, 0x9e, 0x34, 0xc5, 0x53, 0xca, 0x5b, 0xa0, 0xba, 0x64, 0x21, 0x4a,
	0x53, 0xee, 0xee, 0xe4, 0xd0, 0xcd, 0xfe, 0xc1, 0x98, 0x69, 0x3d, 0x82, 0x3c, 0x81, 0xbe, 0x37,
	0x9f, 0xa3, 0x52, 0xe7, 0x82, 0x6b, 0x29, 0x02, 0xc3, 0x92, 0xee, 0x64, 0xe0, 0x4e, 0xf3, 0x56,
	0xba, 0xed, 0x44, 0x4e, 0xa1, 0x2d, 0x37, 0x8a, 0xd8, 0x37, 0x8a, 0xc8, 0xce, 0xe4, 0x11, 0x1c,
	0x84, 0xe6, 0xd9, 0xca, 0x3e, 0x70, 0x9a, 0xe3, 0xee, 0xe4, 0xc8, 0x2d, 0xc8, 0x95, 0x6e, 0x1c,
	0xc8, 0x97, 0x30, 0x88, 0xf2, 0x24, 0x50, 0x76, 0xdb, 0x40, 0xee, 0xb9, 0x35, 0x24, 0x29, 0xb8,
	0x93, 0x6f, 0xe1, 0x58, 0x16, 0x48, 0xab, 0xec, 0x8e, 0x89, 0x71, 0xea, 0xd6, 0xf2, 0x9a, 0x96,
	0x41, 0xc4, 0x05, 0xc2, 0xf8, 0x8a, 0x69, 0xfc, 0x9e, 0xf1, 0xdf, 0x66, 0x9e, 0x52, 0x6b, 0x21,
	0x7d, 0x1b, 0x4c, 0x73, 0x2b, 0x6e, 0x46, 0x7f, 0x77, 0x60, 0xb8, 0xdd, 0xc8, 0xf3, 0xd7, 0x1e,
	0x5f, 0x98, 0xc6, 0xa1, 0xcf, 0xb4, 0x90, 0x29, 0x33, 0xd2, 0xd3, 0x56, 0xcd, 0x1a, 0x85, 0x9a,
	0x7d, 0x06, 0xc0, 0x71, 0xbd, 0xc9, 0xbf, 0x59, 0x53, 0xb6, 0x9c, 0x0f, 0xf9, 0x10, 0xfa, 0x3e,
	0x06, 0xa8, 0x71, 0x03, 0x6a, 0x39, 0xcd, 0x71, 0x8f, 0x6e, 0x1b, 0xe3, 0xf2, 0x84, 0x05, 0xde,
	0x2a, 0x7b, 0xaf, 0x58, 0x9e, 0x22, 0xb5, 0x69, 0x19, 0x44, 0xce, 0xe0, 0xc4, 0x18, 0x19, 0xfa,
	0xb3, 0x4c, 0xeb, 0xca, 0xde, 0xaf, 0x49, 0xb5, 0xca, 0x99, 0x7c, 0x03, 0xc7, 0x1c, 0xd7, 0xb3,
	0xed, 0x86, 0x1f, 0xec, 0x6e, 0x78, 0x19, 0x41, 0x28, 0x0c, 0x93, 0x57, 0xce, 0xaa, 0xa8, 0xf3,
	0xd0, 0xdd, 0x39, 0x5f, 0x68, 0x25, 0x96, 0x3c, 0x85, 0x3b, 0x91, 0x14, 0xa1, 0x28, 0x05, 0xed,
	0xd4, 0x3c, 0xb0, 0xda, 0x9d, 0x3c, 0x86, 0x36, 0xc7, 0xf5, 0xa5, 0x91, 0x33, 0x18, 0x25, 0xe5,
	0xa0, 0xaf, 0x74, 0xac, 0x3f, 0x9a, 0x79, 0x10, 0x17, 0x3a, 0x1c, 0xd7, 0xd3, 0x44, 0xe6, 0xdd,
	0x1a, 0xf7, 0x5b, 0x17, 0xf2, 0x49, 0x1a, 0x3d, 0x96, 0x7a, 0xaf, 0x5a, 0xea, 0x99, 0x03, 0xb9,
	0x00, 0x12, 0x23, 0xb5, 0x96, 0xec, 0x6a, 0xa9, 0x31, 0xd1, 0xb3, 0xdd, 0x37, 0x93, 0xe9, 0xc1,
	0xb6, 0xbc, 0xd3, 0x53, 0x2c, 0x13, 0x26, 0xd1, 0xa7, 0x15, 0x40, 0xf2, 0x0c, 0x0e, 0x33, 0xfa,
	0xa5, 0xb1, 0x06, 0x6f, 0x13, 0xab, 0x88, 0x22, 0x3f, 0xc0, 0x09, 0xc7, 0xf5, 0xf3, 0x4c, 0x51,
	0x69, 0xb0, 0xc3, 0xb7, 0x09, 0x56, 0x85, 0x24, 0x2f, 0x61, 0xc8, 0x71, 0x4d, 0x4b, 0x63, 0xe0,
	0xe8, 0x8d, 0x63, 0xa0, 0x12, 0x47, 0xbe, 0x80, 0x7b, 0x09, 0x47, 0xca, 0x21, 0x8f, 0x8d, 0xc8,
	0xea, 0xae, 0xc9, 0x2b, 0xb0, 0x53, 0x5a, 0x94, 0xa1, 0xa4, 0xc8, 0xf3, 0xad, 0x05, 0x45, 0x6b,
	0x81, 0xe4, 0x09, 0xdc, 0xd9, 0x7a, 0x75, 0x36, 0x9b, 0x4e, 0xcc, 0x78, 0xa9, 0xbe, 0x1c, 0x7d,
	0x9c, 0xfb, 0x48, 0x4a, 0x88, 0x14, 0xef, 0x99, 0x95, 0x17, 0x2c, 0xd1, 0xcc, 0xa5, 0x0e, 0x4d,
	0x0e, 0xa3, 0xc7, 0xb9, 0x7d, 0x94, 0x10, 0xe7, 0x14, 0xda, 0xfe, 0x52, 0x7a, 0x3a, 0x1e, 0x54,
	0x56, 0x32, 0xa8, 0x36, 0xe7, 0xd1, 0x9f, 0x8d, 0xdc, 0x8a, 0x35, 0x53, 0xef, 0x3b, 0xc1, 0xf8,
	0x73, 0x7e, 0x2d, 0xfe, 0xe7, 0x1a, 0x73, 0xa0, 0x9b, 0x2c, 0x81, 0x73, 0xb1, 0xe4, 0xda, 0x2c,
	0xae, 0x3e, 0xcd, 0x9b, 0xc8, 0x0b, 0x38, 0xf6, 0x7c, 0xff, 0xa9, 0x14, 0xe1, 0xed, 0xf3, 0xcc,
	0x76, 0x7a, 0x23, 0x4b, 0xca, 0xb8, 0x9d, 0x0b, 0x6b, 0x02, 0xc3, 0x74, 0xab, 0x4c, 0xfd, 0x90,
	0xf1, 0xa4, 0x2f, 0x5e, 0x60, 0x1f, 0x38, 0xd6, 0xb8, 0x4d, 0x2b, 0xef, 0xce, 0xbe, 0x82, 0x4f,
	0x85, 0x5c, 0xb8, 0x8a, 0x2d, 0xb8, 0x17, 0xb8, 0x4a, 0x0b, 0x19, 0xaf, 0x54, 0x94, 0x2b, 0x36,
	0xc7, 0xe4, 0x3b, 0x55, 0xb9, 0x8b, 0xe4, 0xab, 0x35, 0x10, 0x73, 0x2f, 0x98, 0x59, 0x3f, 0xf7,
	0x13, 0xe7, 0xd4, 0xe9, 0x6a, 0xdf, 0x78, 0x7d, 0xfe, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x85,
	0xa9, 0x34, 0x46, 0xf2, 0x0a, 0x00, 0x00,
}
