// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Groups.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Member_Role int32

const (
	Member_UNKNOWN       Member_Role = 0
	Member_DEFAULT       Member_Role = 1
	Member_ADMINISTRATOR Member_Role = 2
)

var Member_Role_name = map[int32]string{
	0: "UNKNOWN",
	1: "DEFAULT",
	2: "ADMINISTRATOR",
}

var Member_Role_value = map[string]int32{
	"UNKNOWN":       0,
	"DEFAULT":       1,
	"ADMINISTRATOR": 2,
}

func (x Member_Role) String() string {
	return proto.EnumName(Member_Role_name, int32(x))
}

func (Member_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{1, 0}
}

type AccessControl_AccessRequired int32

const (
	AccessControl_UNKNOWN       AccessControl_AccessRequired = 0
	AccessControl_ANY           AccessControl_AccessRequired = 1
	AccessControl_MEMBER        AccessControl_AccessRequired = 2
	AccessControl_ADMINISTRATOR AccessControl_AccessRequired = 3
	AccessControl_UNSATISFIABLE AccessControl_AccessRequired = 4
)

var AccessControl_AccessRequired_name = map[int32]string{
	0: "UNKNOWN",
	1: "ANY",
	2: "MEMBER",
	3: "ADMINISTRATOR",
	4: "UNSATISFIABLE",
}

var AccessControl_AccessRequired_value = map[string]int32{
	"UNKNOWN":       0,
	"ANY":           1,
	"MEMBER":        2,
	"ADMINISTRATOR": 3,
	"UNSATISFIABLE": 4,
}

func (x AccessControl_AccessRequired) String() string {
	return proto.EnumName(AccessControl_AccessRequired_name, int32(x))
}

func (AccessControl_AccessRequired) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{4, 0}
}

type AvatarUploadAttributes struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Credential           string   `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	Acl                  string   `protobuf:"bytes,3,opt,name=acl,proto3" json:"acl,omitempty"`
	Algorithm            string   `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Date                 string   `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Policy               string   `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	Signature            string   `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarUploadAttributes) Reset()         { *m = AvatarUploadAttributes{} }
func (m *AvatarUploadAttributes) String() string { return proto.CompactTextString(m) }
func (*AvatarUploadAttributes) ProtoMessage()    {}
func (*AvatarUploadAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{0}
}

func (m *AvatarUploadAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarUploadAttributes.Unmarshal(m, b)
}
func (m *AvatarUploadAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarUploadAttributes.Marshal(b, m, deterministic)
}
func (m *AvatarUploadAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarUploadAttributes.Merge(m, src)
}
func (m *AvatarUploadAttributes) XXX_Size() int {
	return xxx_messageInfo_AvatarUploadAttributes.Size(m)
}
func (m *AvatarUploadAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarUploadAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarUploadAttributes proto.InternalMessageInfo

func (m *AvatarUploadAttributes) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AvatarUploadAttributes) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

func (m *AvatarUploadAttributes) GetAcl() string {
	if m != nil {
		return m.Acl
	}
	return ""
}

func (m *AvatarUploadAttributes) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *AvatarUploadAttributes) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *AvatarUploadAttributes) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *AvatarUploadAttributes) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Member struct {
	UserId               []byte      `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Role                 Member_Role `protobuf:"varint,2,opt,name=role,proto3,enum=Member_Role" json:"role,omitempty"`
	ProfileKey           []byte      `protobuf:"bytes,3,opt,name=profileKey,proto3" json:"profileKey,omitempty"`
	Presentation         []byte      `protobuf:"bytes,4,opt,name=presentation,proto3" json:"presentation,omitempty"`
	JoinedAtRevision     uint32      `protobuf:"varint,5,opt,name=joinedAtRevision,proto3" json:"joinedAtRevision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{1}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetUserId() []byte {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *Member) GetRole() Member_Role {
	if m != nil {
		return m.Role
	}
	return Member_UNKNOWN
}

func (m *Member) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *Member) GetPresentation() []byte {
	if m != nil {
		return m.Presentation
	}
	return nil
}

func (m *Member) GetJoinedAtRevision() uint32 {
	if m != nil {
		return m.JoinedAtRevision
	}
	return 0
}

type PendingMember struct {
	Member               *Member  `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	AddedByUserId        []byte   `protobuf:"bytes,2,opt,name=addedByUserId,proto3" json:"addedByUserId,omitempty"`
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingMember) Reset()         { *m = PendingMember{} }
func (m *PendingMember) String() string { return proto.CompactTextString(m) }
func (*PendingMember) ProtoMessage()    {}
func (*PendingMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{2}
}

func (m *PendingMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingMember.Unmarshal(m, b)
}
func (m *PendingMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingMember.Marshal(b, m, deterministic)
}
func (m *PendingMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingMember.Merge(m, src)
}
func (m *PendingMember) XXX_Size() int {
	return xxx_messageInfo_PendingMember.Size(m)
}
func (m *PendingMember) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingMember.DiscardUnknown(m)
}

var xxx_messageInfo_PendingMember proto.InternalMessageInfo

func (m *PendingMember) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *PendingMember) GetAddedByUserId() []byte {
	if m != nil {
		return m.AddedByUserId
	}
	return nil
}

func (m *PendingMember) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type RequestingMember struct {
	UserId               []byte   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProfileKey           []byte   `protobuf:"bytes,2,opt,name=profileKey,proto3" json:"profileKey,omitempty"`
	Presentation         []byte   `protobuf:"bytes,3,opt,name=presentation,proto3" json:"presentation,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestingMember) Reset()         { *m = RequestingMember{} }
func (m *RequestingMember) String() string { return proto.CompactTextString(m) }
func (*RequestingMember) ProtoMessage()    {}
func (*RequestingMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{3}
}

func (m *RequestingMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestingMember.Unmarshal(m, b)
}
func (m *RequestingMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestingMember.Marshal(b, m, deterministic)
}
func (m *RequestingMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestingMember.Merge(m, src)
}
func (m *RequestingMember) XXX_Size() int {
	return xxx_messageInfo_RequestingMember.Size(m)
}
func (m *RequestingMember) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestingMember.DiscardUnknown(m)
}

var xxx_messageInfo_RequestingMember proto.InternalMessageInfo

func (m *RequestingMember) GetUserId() []byte {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *RequestingMember) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *RequestingMember) GetPresentation() []byte {
	if m != nil {
		return m.Presentation
	}
	return nil
}

func (m *RequestingMember) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type AccessControl struct {
	Attributes           AccessControl_AccessRequired `protobuf:"varint,1,opt,name=attributes,proto3,enum=AccessControl_AccessRequired" json:"attributes,omitempty"`
	Members              AccessControl_AccessRequired `protobuf:"varint,2,opt,name=members,proto3,enum=AccessControl_AccessRequired" json:"members,omitempty"`
	AddFromInviteLink    AccessControl_AccessRequired `protobuf:"varint,3,opt,name=addFromInviteLink,proto3,enum=AccessControl_AccessRequired" json:"addFromInviteLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *AccessControl) Reset()         { *m = AccessControl{} }
func (m *AccessControl) String() string { return proto.CompactTextString(m) }
func (*AccessControl) ProtoMessage()    {}
func (*AccessControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{4}
}

func (m *AccessControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControl.Unmarshal(m, b)
}
func (m *AccessControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControl.Marshal(b, m, deterministic)
}
func (m *AccessControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControl.Merge(m, src)
}
func (m *AccessControl) XXX_Size() int {
	return xxx_messageInfo_AccessControl.Size(m)
}
func (m *AccessControl) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControl.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControl proto.InternalMessageInfo

func (m *AccessControl) GetAttributes() AccessControl_AccessRequired {
	if m != nil {
		return m.Attributes
	}
	return AccessControl_UNKNOWN
}

func (m *AccessControl) GetMembers() AccessControl_AccessRequired {
	if m != nil {
		return m.Members
	}
	return AccessControl_UNKNOWN
}

func (m *AccessControl) GetAddFromInviteLink() AccessControl_AccessRequired {
	if m != nil {
		return m.AddFromInviteLink
	}
	return AccessControl_UNKNOWN
}

type Group struct {
	PublicKey                 []byte              `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Title                     []byte              `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Avatar                    string              `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	DisappearingMessagesTimer []byte              `protobuf:"bytes,4,opt,name=disappearingMessagesTimer,proto3" json:"disappearingMessagesTimer,omitempty"`
	AccessControl             *AccessControl      `protobuf:"bytes,5,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	Revision                  uint32              `protobuf:"varint,6,opt,name=revision,proto3" json:"revision,omitempty"`
	Members                   []*Member           `protobuf:"bytes,7,rep,name=members,proto3" json:"members,omitempty"`
	PendingMembers            []*PendingMember    `protobuf:"bytes,8,rep,name=pendingMembers,proto3" json:"pendingMembers,omitempty"`
	RequestingMembers         []*RequestingMember `protobuf:"bytes,9,rep,name=requestingMembers,proto3" json:"requestingMembers,omitempty"`
	InviteLinkPassword        []byte              `protobuf:"bytes,10,opt,name=inviteLinkPassword,proto3" json:"inviteLinkPassword,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}            `json:"-"`
	XXX_unrecognized          []byte              `json:"-"`
	XXX_sizecache             int32               `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{5}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Group) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Group) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Group) GetDisappearingMessagesTimer() []byte {
	if m != nil {
		return m.DisappearingMessagesTimer
	}
	return nil
}

func (m *Group) GetAccessControl() *AccessControl {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

func (m *Group) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *Group) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Group) GetPendingMembers() []*PendingMember {
	if m != nil {
		return m.PendingMembers
	}
	return nil
}

func (m *Group) GetRequestingMembers() []*RequestingMember {
	if m != nil {
		return m.RequestingMembers
	}
	return nil
}

func (m *Group) GetInviteLinkPassword() []byte {
	if m != nil {
		return m.InviteLinkPassword
	}
	return nil
}

type GroupChange struct {
	Actions              []byte   `protobuf:"bytes,1,opt,name=actions,proto3" json:"actions,omitempty"`
	ServerSignature      []byte   `protobuf:"bytes,2,opt,name=serverSignature,proto3" json:"serverSignature,omitempty"`
	ChangeEpoch          uint32   `protobuf:"varint,3,opt,name=changeEpoch,proto3" json:"changeEpoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange) Reset()         { *m = GroupChange{} }
func (m *GroupChange) String() string { return proto.CompactTextString(m) }
func (*GroupChange) ProtoMessage()    {}
func (*GroupChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6}
}

func (m *GroupChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange.Unmarshal(m, b)
}
func (m *GroupChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange.Marshal(b, m, deterministic)
}
func (m *GroupChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange.Merge(m, src)
}
func (m *GroupChange) XXX_Size() int {
	return xxx_messageInfo_GroupChange.Size(m)
}
func (m *GroupChange) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange proto.InternalMessageInfo

func (m *GroupChange) GetActions() []byte {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *GroupChange) GetServerSignature() []byte {
	if m != nil {
		return m.ServerSignature
	}
	return nil
}

func (m *GroupChange) GetChangeEpoch() uint32 {
	if m != nil {
		return m.ChangeEpoch
	}
	return 0
}

type GroupChange_Actions struct {
	SourceUuid                      []byte                                                          `protobuf:"bytes,1,opt,name=sourceUuid,proto3" json:"sourceUuid,omitempty"`
	Revision                        uint32                                                          `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	AddMembers                      []*GroupChange_Actions_AddMemberAction                          `protobuf:"bytes,3,rep,name=addMembers,proto3" json:"addMembers,omitempty"`
	DeleteMembers                   []*GroupChange_Actions_DeleteMemberAction                       `protobuf:"bytes,4,rep,name=deleteMembers,proto3" json:"deleteMembers,omitempty"`
	ModifyMemberRoles               []*GroupChange_Actions_ModifyMemberRoleAction                   `protobuf:"bytes,5,rep,name=modifyMemberRoles,proto3" json:"modifyMemberRoles,omitempty"`
	ModifyMemberProfileKeys         []*GroupChange_Actions_ModifyMemberProfileKeyAction             `protobuf:"bytes,6,rep,name=modifyMemberProfileKeys,proto3" json:"modifyMemberProfileKeys,omitempty"`
	AddPendingMembers               []*GroupChange_Actions_AddPendingMemberAction                   `protobuf:"bytes,7,rep,name=addPendingMembers,proto3" json:"addPendingMembers,omitempty"`
	DeletePendingMembers            []*GroupChange_Actions_DeletePendingMemberAction                `protobuf:"bytes,8,rep,name=deletePendingMembers,proto3" json:"deletePendingMembers,omitempty"`
	PromotePendingMembers           []*GroupChange_Actions_PromotePendingMemberAction               `protobuf:"bytes,9,rep,name=promotePendingMembers,proto3" json:"promotePendingMembers,omitempty"`
	ModifyTitle                     *GroupChange_Actions_ModifyTitleAction                          `protobuf:"bytes,10,opt,name=modifyTitle,proto3" json:"modifyTitle,omitempty"`
	ModifyAvatar                    *GroupChange_Actions_ModifyAvatarAction                         `protobuf:"bytes,11,opt,name=modifyAvatar,proto3" json:"modifyAvatar,omitempty"`
	ModifyDisappearingMessagesTimer *GroupChange_Actions_ModifyDisappearingMessagesTimerAction      `protobuf:"bytes,12,opt,name=modifyDisappearingMessagesTimer,proto3" json:"modifyDisappearingMessagesTimer,omitempty"`
	ModifyAttributesAccess          *GroupChange_Actions_ModifyAttributesAccessControlAction        `protobuf:"bytes,13,opt,name=modifyAttributesAccess,proto3" json:"modifyAttributesAccess,omitempty"`
	ModifyMemberAccess              *GroupChange_Actions_ModifyMembersAccessControlAction           `protobuf:"bytes,14,opt,name=modifyMemberAccess,proto3" json:"modifyMemberAccess,omitempty"`
	ModifyAddFromInviteLinkAccess   *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction `protobuf:"bytes,15,opt,name=modifyAddFromInviteLinkAccess,proto3" json:"modifyAddFromInviteLinkAccess,omitempty"`
	AddRequestingMembers            []*GroupChange_Actions_AddRequestingMemberAction                `protobuf:"bytes,16,rep,name=addRequestingMembers,proto3" json:"addRequestingMembers,omitempty"`
	DeleteRequestingMembers         []*GroupChange_Actions_DeleteRequestingMemberAction             `protobuf:"bytes,17,rep,name=deleteRequestingMembers,proto3" json:"deleteRequestingMembers,omitempty"`
	PromoteRequestingMembers        []*GroupChange_Actions_PromoteRequestingMemberAction            `protobuf:"bytes,18,rep,name=promoteRequestingMembers,proto3" json:"promoteRequestingMembers,omitempty"`
	ModifyInviteLinkPassword        *GroupChange_Actions_ModifyInviteLinkPasswordAction             `protobuf:"bytes,19,opt,name=modifyInviteLinkPassword,proto3" json:"modifyInviteLinkPassword,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}                                                        `json:"-"`
	XXX_unrecognized                []byte                                                          `json:"-"`
	XXX_sizecache                   int32                                                           `json:"-"`
}

func (m *GroupChange_Actions) Reset()         { *m = GroupChange_Actions{} }
func (m *GroupChange_Actions) String() string { return proto.CompactTextString(m) }
func (*GroupChange_Actions) ProtoMessage()    {}
func (*GroupChange_Actions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0}
}

func (m *GroupChange_Actions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions.Unmarshal(m, b)
}
func (m *GroupChange_Actions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions.Merge(m, src)
}
func (m *GroupChange_Actions) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions.Size(m)
}
func (m *GroupChange_Actions) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions proto.InternalMessageInfo

func (m *GroupChange_Actions) GetSourceUuid() []byte {
	if m != nil {
		return m.SourceUuid
	}
	return nil
}

func (m *GroupChange_Actions) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *GroupChange_Actions) GetAddMembers() []*GroupChange_Actions_AddMemberAction {
	if m != nil {
		return m.AddMembers
	}
	return nil
}

func (m *GroupChange_Actions) GetDeleteMembers() []*GroupChange_Actions_DeleteMemberAction {
	if m != nil {
		return m.DeleteMembers
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyMemberRoles() []*GroupChange_Actions_ModifyMemberRoleAction {
	if m != nil {
		return m.ModifyMemberRoles
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyMemberProfileKeys() []*GroupChange_Actions_ModifyMemberProfileKeyAction {
	if m != nil {
		return m.ModifyMemberProfileKeys
	}
	return nil
}

func (m *GroupChange_Actions) GetAddPendingMembers() []*GroupChange_Actions_AddPendingMemberAction {
	if m != nil {
		return m.AddPendingMembers
	}
	return nil
}

func (m *GroupChange_Actions) GetDeletePendingMembers() []*GroupChange_Actions_DeletePendingMemberAction {
	if m != nil {
		return m.DeletePendingMembers
	}
	return nil
}

func (m *GroupChange_Actions) GetPromotePendingMembers() []*GroupChange_Actions_PromotePendingMemberAction {
	if m != nil {
		return m.PromotePendingMembers
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyTitle() *GroupChange_Actions_ModifyTitleAction {
	if m != nil {
		return m.ModifyTitle
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyAvatar() *GroupChange_Actions_ModifyAvatarAction {
	if m != nil {
		return m.ModifyAvatar
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyDisappearingMessagesTimer() *GroupChange_Actions_ModifyDisappearingMessagesTimerAction {
	if m != nil {
		return m.ModifyDisappearingMessagesTimer
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyAttributesAccess() *GroupChange_Actions_ModifyAttributesAccessControlAction {
	if m != nil {
		return m.ModifyAttributesAccess
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyMemberAccess() *GroupChange_Actions_ModifyMembersAccessControlAction {
	if m != nil {
		return m.ModifyMemberAccess
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyAddFromInviteLinkAccess() *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction {
	if m != nil {
		return m.ModifyAddFromInviteLinkAccess
	}
	return nil
}

func (m *GroupChange_Actions) GetAddRequestingMembers() []*GroupChange_Actions_AddRequestingMemberAction {
	if m != nil {
		return m.AddRequestingMembers
	}
	return nil
}

func (m *GroupChange_Actions) GetDeleteRequestingMembers() []*GroupChange_Actions_DeleteRequestingMemberAction {
	if m != nil {
		return m.DeleteRequestingMembers
	}
	return nil
}

func (m *GroupChange_Actions) GetPromoteRequestingMembers() []*GroupChange_Actions_PromoteRequestingMemberAction {
	if m != nil {
		return m.PromoteRequestingMembers
	}
	return nil
}

func (m *GroupChange_Actions) GetModifyInviteLinkPassword() *GroupChange_Actions_ModifyInviteLinkPasswordAction {
	if m != nil {
		return m.ModifyInviteLinkPassword
	}
	return nil
}

type GroupChange_Actions_AddMemberAction struct {
	Added                *Member  `protobuf:"bytes,1,opt,name=added,proto3" json:"added,omitempty"`
	JoinFromInviteLink   bool     `protobuf:"varint,2,opt,name=joinFromInviteLink,proto3" json:"joinFromInviteLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_AddMemberAction) Reset()         { *m = GroupChange_Actions_AddMemberAction{} }
func (m *GroupChange_Actions_AddMemberAction) String() string { return proto.CompactTextString(m) }
func (*GroupChange_Actions_AddMemberAction) ProtoMessage()    {}
func (*GroupChange_Actions_AddMemberAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 0}
}

func (m *GroupChange_Actions_AddMemberAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_AddMemberAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_AddMemberAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_AddMemberAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_AddMemberAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_AddMemberAction.Merge(m, src)
}
func (m *GroupChange_Actions_AddMemberAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_AddMemberAction.Size(m)
}
func (m *GroupChange_Actions_AddMemberAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_AddMemberAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_AddMemberAction proto.InternalMessageInfo

func (m *GroupChange_Actions_AddMemberAction) GetAdded() *Member {
	if m != nil {
		return m.Added
	}
	return nil
}

func (m *GroupChange_Actions_AddMemberAction) GetJoinFromInviteLink() bool {
	if m != nil {
		return m.JoinFromInviteLink
	}
	return false
}

type GroupChange_Actions_DeleteMemberAction struct {
	DeletedUserId        []byte   `protobuf:"bytes,1,opt,name=deletedUserId,proto3" json:"deletedUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_DeleteMemberAction) Reset() {
	*m = GroupChange_Actions_DeleteMemberAction{}
}
func (m *GroupChange_Actions_DeleteMemberAction) String() string { return proto.CompactTextString(m) }
func (*GroupChange_Actions_DeleteMemberAction) ProtoMessage()    {}
func (*GroupChange_Actions_DeleteMemberAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 1}
}

func (m *GroupChange_Actions_DeleteMemberAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_DeleteMemberAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_DeleteMemberAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_DeleteMemberAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_DeleteMemberAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_DeleteMemberAction.Merge(m, src)
}
func (m *GroupChange_Actions_DeleteMemberAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_DeleteMemberAction.Size(m)
}
func (m *GroupChange_Actions_DeleteMemberAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_DeleteMemberAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_DeleteMemberAction proto.InternalMessageInfo

func (m *GroupChange_Actions_DeleteMemberAction) GetDeletedUserId() []byte {
	if m != nil {
		return m.DeletedUserId
	}
	return nil
}

type GroupChange_Actions_ModifyMemberRoleAction struct {
	UserId               []byte      `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Role                 Member_Role `protobuf:"varint,2,opt,name=role,proto3,enum=Member_Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GroupChange_Actions_ModifyMemberRoleAction) Reset() {
	*m = GroupChange_Actions_ModifyMemberRoleAction{}
}
func (m *GroupChange_Actions_ModifyMemberRoleAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_ModifyMemberRoleAction) ProtoMessage() {}
func (*GroupChange_Actions_ModifyMemberRoleAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 2}
}

func (m *GroupChange_Actions_ModifyMemberRoleAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyMemberRoleAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyMemberRoleAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyMemberRoleAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyMemberRoleAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyMemberRoleAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyMemberRoleAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyMemberRoleAction.Size(m)
}
func (m *GroupChange_Actions_ModifyMemberRoleAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyMemberRoleAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyMemberRoleAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyMemberRoleAction) GetUserId() []byte {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *GroupChange_Actions_ModifyMemberRoleAction) GetRole() Member_Role {
	if m != nil {
		return m.Role
	}
	return Member_UNKNOWN
}

type GroupChange_Actions_ModifyMemberProfileKeyAction struct {
	Presentation         []byte   `protobuf:"bytes,1,opt,name=presentation,proto3" json:"presentation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_ModifyMemberProfileKeyAction) Reset() {
	*m = GroupChange_Actions_ModifyMemberProfileKeyAction{}
}
func (m *GroupChange_Actions_ModifyMemberProfileKeyAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_ModifyMemberProfileKeyAction) ProtoMessage() {}
func (*GroupChange_Actions_ModifyMemberProfileKeyAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 3}
}

func (m *GroupChange_Actions_ModifyMemberProfileKeyAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyMemberProfileKeyAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyMemberProfileKeyAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyMemberProfileKeyAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyMemberProfileKeyAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyMemberProfileKeyAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyMemberProfileKeyAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyMemberProfileKeyAction.Size(m)
}
func (m *GroupChange_Actions_ModifyMemberProfileKeyAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyMemberProfileKeyAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyMemberProfileKeyAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyMemberProfileKeyAction) GetPresentation() []byte {
	if m != nil {
		return m.Presentation
	}
	return nil
}

type GroupChange_Actions_AddPendingMemberAction struct {
	Added                *PendingMember `protobuf:"bytes,1,opt,name=added,proto3" json:"added,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GroupChange_Actions_AddPendingMemberAction) Reset() {
	*m = GroupChange_Actions_AddPendingMemberAction{}
}
func (m *GroupChange_Actions_AddPendingMemberAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_AddPendingMemberAction) ProtoMessage() {}
func (*GroupChange_Actions_AddPendingMemberAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 4}
}

func (m *GroupChange_Actions_AddPendingMemberAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_AddPendingMemberAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_AddPendingMemberAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_AddPendingMemberAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_AddPendingMemberAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_AddPendingMemberAction.Merge(m, src)
}
func (m *GroupChange_Actions_AddPendingMemberAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_AddPendingMemberAction.Size(m)
}
func (m *GroupChange_Actions_AddPendingMemberAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_AddPendingMemberAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_AddPendingMemberAction proto.InternalMessageInfo

func (m *GroupChange_Actions_AddPendingMemberAction) GetAdded() *PendingMember {
	if m != nil {
		return m.Added
	}
	return nil
}

type GroupChange_Actions_DeletePendingMemberAction struct {
	DeletedUserId        []byte   `protobuf:"bytes,1,opt,name=deletedUserId,proto3" json:"deletedUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_DeletePendingMemberAction) Reset() {
	*m = GroupChange_Actions_DeletePendingMemberAction{}
}
func (m *GroupChange_Actions_DeletePendingMemberAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_DeletePendingMemberAction) ProtoMessage() {}
func (*GroupChange_Actions_DeletePendingMemberAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 5}
}

func (m *GroupChange_Actions_DeletePendingMemberAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_DeletePendingMemberAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_DeletePendingMemberAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_DeletePendingMemberAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_DeletePendingMemberAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_DeletePendingMemberAction.Merge(m, src)
}
func (m *GroupChange_Actions_DeletePendingMemberAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_DeletePendingMemberAction.Size(m)
}
func (m *GroupChange_Actions_DeletePendingMemberAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_DeletePendingMemberAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_DeletePendingMemberAction proto.InternalMessageInfo

func (m *GroupChange_Actions_DeletePendingMemberAction) GetDeletedUserId() []byte {
	if m != nil {
		return m.DeletedUserId
	}
	return nil
}

type GroupChange_Actions_PromotePendingMemberAction struct {
	Presentation         []byte   `protobuf:"bytes,1,opt,name=presentation,proto3" json:"presentation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_PromotePendingMemberAction) Reset() {
	*m = GroupChange_Actions_PromotePendingMemberAction{}
}
func (m *GroupChange_Actions_PromotePendingMemberAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_PromotePendingMemberAction) ProtoMessage() {}
func (*GroupChange_Actions_PromotePendingMemberAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 6}
}

func (m *GroupChange_Actions_PromotePendingMemberAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_PromotePendingMemberAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_PromotePendingMemberAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_PromotePendingMemberAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_PromotePendingMemberAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_PromotePendingMemberAction.Merge(m, src)
}
func (m *GroupChange_Actions_PromotePendingMemberAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_PromotePendingMemberAction.Size(m)
}
func (m *GroupChange_Actions_PromotePendingMemberAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_PromotePendingMemberAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_PromotePendingMemberAction proto.InternalMessageInfo

func (m *GroupChange_Actions_PromotePendingMemberAction) GetPresentation() []byte {
	if m != nil {
		return m.Presentation
	}
	return nil
}

type GroupChange_Actions_AddRequestingMemberAction struct {
	Added                *RequestingMember `protobuf:"bytes,1,opt,name=added,proto3" json:"added,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GroupChange_Actions_AddRequestingMemberAction) Reset() {
	*m = GroupChange_Actions_AddRequestingMemberAction{}
}
func (m *GroupChange_Actions_AddRequestingMemberAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_AddRequestingMemberAction) ProtoMessage() {}
func (*GroupChange_Actions_AddRequestingMemberAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 7}
}

func (m *GroupChange_Actions_AddRequestingMemberAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_AddRequestingMemberAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_AddRequestingMemberAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_AddRequestingMemberAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_AddRequestingMemberAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_AddRequestingMemberAction.Merge(m, src)
}
func (m *GroupChange_Actions_AddRequestingMemberAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_AddRequestingMemberAction.Size(m)
}
func (m *GroupChange_Actions_AddRequestingMemberAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_AddRequestingMemberAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_AddRequestingMemberAction proto.InternalMessageInfo

func (m *GroupChange_Actions_AddRequestingMemberAction) GetAdded() *RequestingMember {
	if m != nil {
		return m.Added
	}
	return nil
}

type GroupChange_Actions_DeleteRequestingMemberAction struct {
	DeletedUserId        []byte   `protobuf:"bytes,1,opt,name=deletedUserId,proto3" json:"deletedUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_DeleteRequestingMemberAction) Reset() {
	*m = GroupChange_Actions_DeleteRequestingMemberAction{}
}
func (m *GroupChange_Actions_DeleteRequestingMemberAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_DeleteRequestingMemberAction) ProtoMessage() {}
func (*GroupChange_Actions_DeleteRequestingMemberAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 8}
}

func (m *GroupChange_Actions_DeleteRequestingMemberAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_DeleteRequestingMemberAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_DeleteRequestingMemberAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_DeleteRequestingMemberAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_DeleteRequestingMemberAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_DeleteRequestingMemberAction.Merge(m, src)
}
func (m *GroupChange_Actions_DeleteRequestingMemberAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_DeleteRequestingMemberAction.Size(m)
}
func (m *GroupChange_Actions_DeleteRequestingMemberAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_DeleteRequestingMemberAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_DeleteRequestingMemberAction proto.InternalMessageInfo

func (m *GroupChange_Actions_DeleteRequestingMemberAction) GetDeletedUserId() []byte {
	if m != nil {
		return m.DeletedUserId
	}
	return nil
}

type GroupChange_Actions_PromoteRequestingMemberAction struct {
	UserId               []byte      `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Role                 Member_Role `protobuf:"varint,2,opt,name=role,proto3,enum=Member_Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GroupChange_Actions_PromoteRequestingMemberAction) Reset() {
	*m = GroupChange_Actions_PromoteRequestingMemberAction{}
}
func (m *GroupChange_Actions_PromoteRequestingMemberAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_PromoteRequestingMemberAction) ProtoMessage() {}
func (*GroupChange_Actions_PromoteRequestingMemberAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 9}
}

func (m *GroupChange_Actions_PromoteRequestingMemberAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_PromoteRequestingMemberAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_PromoteRequestingMemberAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_PromoteRequestingMemberAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_PromoteRequestingMemberAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_PromoteRequestingMemberAction.Merge(m, src)
}
func (m *GroupChange_Actions_PromoteRequestingMemberAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_PromoteRequestingMemberAction.Size(m)
}
func (m *GroupChange_Actions_PromoteRequestingMemberAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_PromoteRequestingMemberAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_PromoteRequestingMemberAction proto.InternalMessageInfo

func (m *GroupChange_Actions_PromoteRequestingMemberAction) GetUserId() []byte {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *GroupChange_Actions_PromoteRequestingMemberAction) GetRole() Member_Role {
	if m != nil {
		return m.Role
	}
	return Member_UNKNOWN
}

type GroupChange_Actions_ModifyTitleAction struct {
	Title                []byte   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_ModifyTitleAction) Reset()         { *m = GroupChange_Actions_ModifyTitleAction{} }
func (m *GroupChange_Actions_ModifyTitleAction) String() string { return proto.CompactTextString(m) }
func (*GroupChange_Actions_ModifyTitleAction) ProtoMessage()    {}
func (*GroupChange_Actions_ModifyTitleAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 10}
}

func (m *GroupChange_Actions_ModifyTitleAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyTitleAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyTitleAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyTitleAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyTitleAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyTitleAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyTitleAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyTitleAction.Size(m)
}
func (m *GroupChange_Actions_ModifyTitleAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyTitleAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyTitleAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyTitleAction) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

type GroupChange_Actions_ModifyAvatarAction struct {
	Avatar               string   `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_ModifyAvatarAction) Reset() {
	*m = GroupChange_Actions_ModifyAvatarAction{}
}
func (m *GroupChange_Actions_ModifyAvatarAction) String() string { return proto.CompactTextString(m) }
func (*GroupChange_Actions_ModifyAvatarAction) ProtoMessage()    {}
func (*GroupChange_Actions_ModifyAvatarAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 11}
}

func (m *GroupChange_Actions_ModifyAvatarAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyAvatarAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyAvatarAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyAvatarAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyAvatarAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyAvatarAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyAvatarAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyAvatarAction.Size(m)
}
func (m *GroupChange_Actions_ModifyAvatarAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyAvatarAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyAvatarAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyAvatarAction) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type GroupChange_Actions_ModifyDisappearingMessagesTimerAction struct {
	Timer                []byte   `protobuf:"bytes,1,opt,name=timer,proto3" json:"timer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_ModifyDisappearingMessagesTimerAction) Reset() {
	*m = GroupChange_Actions_ModifyDisappearingMessagesTimerAction{}
}
func (m *GroupChange_Actions_ModifyDisappearingMessagesTimerAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_ModifyDisappearingMessagesTimerAction) ProtoMessage() {}
func (*GroupChange_Actions_ModifyDisappearingMessagesTimerAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 12}
}

func (m *GroupChange_Actions_ModifyDisappearingMessagesTimerAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyDisappearingMessagesTimerAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyDisappearingMessagesTimerAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyDisappearingMessagesTimerAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyDisappearingMessagesTimerAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyDisappearingMessagesTimerAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyDisappearingMessagesTimerAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyDisappearingMessagesTimerAction.Size(m)
}
func (m *GroupChange_Actions_ModifyDisappearingMessagesTimerAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyDisappearingMessagesTimerAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyDisappearingMessagesTimerAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyDisappearingMessagesTimerAction) GetTimer() []byte {
	if m != nil {
		return m.Timer
	}
	return nil
}

type GroupChange_Actions_ModifyAttributesAccessControlAction struct {
	AttributesAccess     AccessControl_AccessRequired `protobuf:"varint,1,opt,name=attributesAccess,proto3,enum=AccessControl_AccessRequired" json:"attributesAccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GroupChange_Actions_ModifyAttributesAccessControlAction) Reset() {
	*m = GroupChange_Actions_ModifyAttributesAccessControlAction{}
}
func (m *GroupChange_Actions_ModifyAttributesAccessControlAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_ModifyAttributesAccessControlAction) ProtoMessage() {}
func (*GroupChange_Actions_ModifyAttributesAccessControlAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 13}
}

func (m *GroupChange_Actions_ModifyAttributesAccessControlAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyAttributesAccessControlAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyAttributesAccessControlAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyAttributesAccessControlAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyAttributesAccessControlAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyAttributesAccessControlAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyAttributesAccessControlAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyAttributesAccessControlAction.Size(m)
}
func (m *GroupChange_Actions_ModifyAttributesAccessControlAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyAttributesAccessControlAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyAttributesAccessControlAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyAttributesAccessControlAction) GetAttributesAccess() AccessControl_AccessRequired {
	if m != nil {
		return m.AttributesAccess
	}
	return AccessControl_UNKNOWN
}

type GroupChange_Actions_ModifyMembersAccessControlAction struct {
	MembersAccess        AccessControl_AccessRequired `protobuf:"varint,1,opt,name=membersAccess,proto3,enum=AccessControl_AccessRequired" json:"membersAccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GroupChange_Actions_ModifyMembersAccessControlAction) Reset() {
	*m = GroupChange_Actions_ModifyMembersAccessControlAction{}
}
func (m *GroupChange_Actions_ModifyMembersAccessControlAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_ModifyMembersAccessControlAction) ProtoMessage() {}
func (*GroupChange_Actions_ModifyMembersAccessControlAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 14}
}

func (m *GroupChange_Actions_ModifyMembersAccessControlAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyMembersAccessControlAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyMembersAccessControlAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyMembersAccessControlAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyMembersAccessControlAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyMembersAccessControlAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyMembersAccessControlAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyMembersAccessControlAction.Size(m)
}
func (m *GroupChange_Actions_ModifyMembersAccessControlAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyMembersAccessControlAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyMembersAccessControlAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyMembersAccessControlAction) GetMembersAccess() AccessControl_AccessRequired {
	if m != nil {
		return m.MembersAccess
	}
	return AccessControl_UNKNOWN
}

type GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction struct {
	AddFromInviteLinkAccess AccessControl_AccessRequired `protobuf:"varint,1,opt,name=addFromInviteLinkAccess,proto3,enum=AccessControl_AccessRequired" json:"addFromInviteLinkAccess,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                     `json:"-"`
	XXX_unrecognized        []byte                       `json:"-"`
	XXX_sizecache           int32                        `json:"-"`
}

func (m *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) Reset() {
	*m = GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction{}
}
func (m *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) ProtoMessage() {}
func (*GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 15}
}

func (m *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction.Size(m)
}
func (m *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction) GetAddFromInviteLinkAccess() AccessControl_AccessRequired {
	if m != nil {
		return m.AddFromInviteLinkAccess
	}
	return AccessControl_UNKNOWN
}

type GroupChange_Actions_ModifyInviteLinkPasswordAction struct {
	InviteLinkPassword   []byte   `protobuf:"bytes,1,opt,name=inviteLinkPassword,proto3" json:"inviteLinkPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChange_Actions_ModifyInviteLinkPasswordAction) Reset() {
	*m = GroupChange_Actions_ModifyInviteLinkPasswordAction{}
}
func (m *GroupChange_Actions_ModifyInviteLinkPasswordAction) String() string {
	return proto.CompactTextString(m)
}
func (*GroupChange_Actions_ModifyInviteLinkPasswordAction) ProtoMessage() {}
func (*GroupChange_Actions_ModifyInviteLinkPasswordAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{6, 0, 16}
}

func (m *GroupChange_Actions_ModifyInviteLinkPasswordAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChange_Actions_ModifyInviteLinkPasswordAction.Unmarshal(m, b)
}
func (m *GroupChange_Actions_ModifyInviteLinkPasswordAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChange_Actions_ModifyInviteLinkPasswordAction.Marshal(b, m, deterministic)
}
func (m *GroupChange_Actions_ModifyInviteLinkPasswordAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChange_Actions_ModifyInviteLinkPasswordAction.Merge(m, src)
}
func (m *GroupChange_Actions_ModifyInviteLinkPasswordAction) XXX_Size() int {
	return xxx_messageInfo_GroupChange_Actions_ModifyInviteLinkPasswordAction.Size(m)
}
func (m *GroupChange_Actions_ModifyInviteLinkPasswordAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChange_Actions_ModifyInviteLinkPasswordAction.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChange_Actions_ModifyInviteLinkPasswordAction proto.InternalMessageInfo

func (m *GroupChange_Actions_ModifyInviteLinkPasswordAction) GetInviteLinkPassword() []byte {
	if m != nil {
		return m.InviteLinkPassword
	}
	return nil
}

type GroupChanges struct {
	GroupChanges         []*GroupChanges_GroupChangeState `protobuf:"bytes,1,rep,name=groupChanges,proto3" json:"groupChanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GroupChanges) Reset()         { *m = GroupChanges{} }
func (m *GroupChanges) String() string { return proto.CompactTextString(m) }
func (*GroupChanges) ProtoMessage()    {}
func (*GroupChanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{7}
}

func (m *GroupChanges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChanges.Unmarshal(m, b)
}
func (m *GroupChanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChanges.Marshal(b, m, deterministic)
}
func (m *GroupChanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChanges.Merge(m, src)
}
func (m *GroupChanges) XXX_Size() int {
	return xxx_messageInfo_GroupChanges.Size(m)
}
func (m *GroupChanges) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChanges.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChanges proto.InternalMessageInfo

func (m *GroupChanges) GetGroupChanges() []*GroupChanges_GroupChangeState {
	if m != nil {
		return m.GroupChanges
	}
	return nil
}

type GroupChanges_GroupChangeState struct {
	GroupChange          *GroupChange `protobuf:"bytes,1,opt,name=groupChange,proto3" json:"groupChange,omitempty"`
	GroupState           *Group       `protobuf:"bytes,2,opt,name=groupState,proto3" json:"groupState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupChanges_GroupChangeState) Reset()         { *m = GroupChanges_GroupChangeState{} }
func (m *GroupChanges_GroupChangeState) String() string { return proto.CompactTextString(m) }
func (*GroupChanges_GroupChangeState) ProtoMessage()    {}
func (*GroupChanges_GroupChangeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{7, 0}
}

func (m *GroupChanges_GroupChangeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChanges_GroupChangeState.Unmarshal(m, b)
}
func (m *GroupChanges_GroupChangeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChanges_GroupChangeState.Marshal(b, m, deterministic)
}
func (m *GroupChanges_GroupChangeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChanges_GroupChangeState.Merge(m, src)
}
func (m *GroupChanges_GroupChangeState) XXX_Size() int {
	return xxx_messageInfo_GroupChanges_GroupChangeState.Size(m)
}
func (m *GroupChanges_GroupChangeState) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChanges_GroupChangeState.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChanges_GroupChangeState proto.InternalMessageInfo

func (m *GroupChanges_GroupChangeState) GetGroupChange() *GroupChange {
	if m != nil {
		return m.GroupChange
	}
	return nil
}

func (m *GroupChanges_GroupChangeState) GetGroupState() *Group {
	if m != nil {
		return m.GroupState
	}
	return nil
}

type GroupAttributeBlob struct {
	// Types that are valid to be assigned to Content:
	//	*GroupAttributeBlob_Title
	//	*GroupAttributeBlob_Avatar
	//	*GroupAttributeBlob_DisappearingMessagesDuration
	Content              isGroupAttributeBlob_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GroupAttributeBlob) Reset()         { *m = GroupAttributeBlob{} }
func (m *GroupAttributeBlob) String() string { return proto.CompactTextString(m) }
func (*GroupAttributeBlob) ProtoMessage()    {}
func (*GroupAttributeBlob) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{8}
}

func (m *GroupAttributeBlob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupAttributeBlob.Unmarshal(m, b)
}
func (m *GroupAttributeBlob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupAttributeBlob.Marshal(b, m, deterministic)
}
func (m *GroupAttributeBlob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupAttributeBlob.Merge(m, src)
}
func (m *GroupAttributeBlob) XXX_Size() int {
	return xxx_messageInfo_GroupAttributeBlob.Size(m)
}
func (m *GroupAttributeBlob) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupAttributeBlob.DiscardUnknown(m)
}

var xxx_messageInfo_GroupAttributeBlob proto.InternalMessageInfo

type isGroupAttributeBlob_Content interface {
	isGroupAttributeBlob_Content()
}

type GroupAttributeBlob_Title struct {
	Title string `protobuf:"bytes,1,opt,name=title,proto3,oneof"`
}

type GroupAttributeBlob_Avatar struct {
	Avatar []byte `protobuf:"bytes,2,opt,name=avatar,proto3,oneof"`
}

type GroupAttributeBlob_DisappearingMessagesDuration struct {
	DisappearingMessagesDuration uint32 `protobuf:"varint,3,opt,name=disappearingMessagesDuration,proto3,oneof"`
}

func (*GroupAttributeBlob_Title) isGroupAttributeBlob_Content() {}

func (*GroupAttributeBlob_Avatar) isGroupAttributeBlob_Content() {}

func (*GroupAttributeBlob_DisappearingMessagesDuration) isGroupAttributeBlob_Content() {}

func (m *GroupAttributeBlob) GetContent() isGroupAttributeBlob_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GroupAttributeBlob) GetTitle() string {
	if x, ok := m.GetContent().(*GroupAttributeBlob_Title); ok {
		return x.Title
	}
	return ""
}

func (m *GroupAttributeBlob) GetAvatar() []byte {
	if x, ok := m.GetContent().(*GroupAttributeBlob_Avatar); ok {
		return x.Avatar
	}
	return nil
}

func (m *GroupAttributeBlob) GetDisappearingMessagesDuration() uint32 {
	if x, ok := m.GetContent().(*GroupAttributeBlob_DisappearingMessagesDuration); ok {
		return x.DisappearingMessagesDuration
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GroupAttributeBlob) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GroupAttributeBlob_Title)(nil),
		(*GroupAttributeBlob_Avatar)(nil),
		(*GroupAttributeBlob_DisappearingMessagesDuration)(nil),
	}
}

type GroupInviteLink struct {
	// Types that are valid to be assigned to Contents:
	//	*GroupInviteLink_V1Contents
	Contents             isGroupInviteLink_Contents `protobuf_oneof:"contents"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GroupInviteLink) Reset()         { *m = GroupInviteLink{} }
func (m *GroupInviteLink) String() string { return proto.CompactTextString(m) }
func (*GroupInviteLink) ProtoMessage()    {}
func (*GroupInviteLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{9}
}

func (m *GroupInviteLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInviteLink.Unmarshal(m, b)
}
func (m *GroupInviteLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInviteLink.Marshal(b, m, deterministic)
}
func (m *GroupInviteLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInviteLink.Merge(m, src)
}
func (m *GroupInviteLink) XXX_Size() int {
	return xxx_messageInfo_GroupInviteLink.Size(m)
}
func (m *GroupInviteLink) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInviteLink.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInviteLink proto.InternalMessageInfo

type isGroupInviteLink_Contents interface {
	isGroupInviteLink_Contents()
}

type GroupInviteLink_V1Contents struct {
	V1Contents *GroupInviteLink_GroupInviteLinkContentsV1 `protobuf:"bytes,1,opt,name=v1Contents,proto3,oneof"`
}

func (*GroupInviteLink_V1Contents) isGroupInviteLink_Contents() {}

func (m *GroupInviteLink) GetContents() isGroupInviteLink_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *GroupInviteLink) GetV1Contents() *GroupInviteLink_GroupInviteLinkContentsV1 {
	if x, ok := m.GetContents().(*GroupInviteLink_V1Contents); ok {
		return x.V1Contents
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GroupInviteLink) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GroupInviteLink_V1Contents)(nil),
	}
}

type GroupInviteLink_GroupInviteLinkContentsV1 struct {
	GroupMasterKey       []byte   `protobuf:"bytes,1,opt,name=groupMasterKey,proto3" json:"groupMasterKey,omitempty"`
	InviteLinkPassword   []byte   `protobuf:"bytes,2,opt,name=inviteLinkPassword,proto3" json:"inviteLinkPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupInviteLink_GroupInviteLinkContentsV1) Reset() {
	*m = GroupInviteLink_GroupInviteLinkContentsV1{}
}
func (m *GroupInviteLink_GroupInviteLinkContentsV1) String() string { return proto.CompactTextString(m) }
func (*GroupInviteLink_GroupInviteLinkContentsV1) ProtoMessage()    {}
func (*GroupInviteLink_GroupInviteLinkContentsV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{9, 0}
}

func (m *GroupInviteLink_GroupInviteLinkContentsV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInviteLink_GroupInviteLinkContentsV1.Unmarshal(m, b)
}
func (m *GroupInviteLink_GroupInviteLinkContentsV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInviteLink_GroupInviteLinkContentsV1.Marshal(b, m, deterministic)
}
func (m *GroupInviteLink_GroupInviteLinkContentsV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInviteLink_GroupInviteLinkContentsV1.Merge(m, src)
}
func (m *GroupInviteLink_GroupInviteLinkContentsV1) XXX_Size() int {
	return xxx_messageInfo_GroupInviteLink_GroupInviteLinkContentsV1.Size(m)
}
func (m *GroupInviteLink_GroupInviteLinkContentsV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInviteLink_GroupInviteLinkContentsV1.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInviteLink_GroupInviteLinkContentsV1 proto.InternalMessageInfo

func (m *GroupInviteLink_GroupInviteLinkContentsV1) GetGroupMasterKey() []byte {
	if m != nil {
		return m.GroupMasterKey
	}
	return nil
}

func (m *GroupInviteLink_GroupInviteLinkContentsV1) GetInviteLinkPassword() []byte {
	if m != nil {
		return m.InviteLinkPassword
	}
	return nil
}

type GroupJoinInfo struct {
	PublicKey            []byte                       `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Title                []byte                       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Avatar               string                       `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	MemberCount          uint32                       `protobuf:"varint,4,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	AddFromInviteLink    AccessControl_AccessRequired `protobuf:"varint,5,opt,name=addFromInviteLink,proto3,enum=AccessControl_AccessRequired" json:"addFromInviteLink,omitempty"`
	Revision             uint32                       `protobuf:"varint,6,opt,name=revision,proto3" json:"revision,omitempty"`
	PendingAdminApproval bool                         `protobuf:"varint,7,opt,name=pendingAdminApproval,proto3" json:"pendingAdminApproval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GroupJoinInfo) Reset()         { *m = GroupJoinInfo{} }
func (m *GroupJoinInfo) String() string { return proto.CompactTextString(m) }
func (*GroupJoinInfo) ProtoMessage()    {}
func (*GroupJoinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0760b0ffc86a42ae, []int{10}
}

func (m *GroupJoinInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupJoinInfo.Unmarshal(m, b)
}
func (m *GroupJoinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupJoinInfo.Marshal(b, m, deterministic)
}
func (m *GroupJoinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupJoinInfo.Merge(m, src)
}
func (m *GroupJoinInfo) XXX_Size() int {
	return xxx_messageInfo_GroupJoinInfo.Size(m)
}
func (m *GroupJoinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupJoinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupJoinInfo proto.InternalMessageInfo

func (m *GroupJoinInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *GroupJoinInfo) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *GroupJoinInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GroupJoinInfo) GetMemberCount() uint32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func (m *GroupJoinInfo) GetAddFromInviteLink() AccessControl_AccessRequired {
	if m != nil {
		return m.AddFromInviteLink
	}
	return AccessControl_UNKNOWN
}

func (m *GroupJoinInfo) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *GroupJoinInfo) GetPendingAdminApproval() bool {
	if m != nil {
		return m.PendingAdminApproval
	}
	return false
}

func init() {
	proto.RegisterEnum("Member_Role", Member_Role_name, Member_Role_value)
	proto.RegisterEnum("AccessControl_AccessRequired", AccessControl_AccessRequired_name, AccessControl_AccessRequired_value)
	proto.RegisterType((*AvatarUploadAttributes)(nil), "AvatarUploadAttributes")
	proto.RegisterType((*Member)(nil), "Member")
	proto.RegisterType((*PendingMember)(nil), "PendingMember")
	proto.RegisterType((*RequestingMember)(nil), "RequestingMember")
	proto.RegisterType((*AccessControl)(nil), "AccessControl")
	proto.RegisterType((*Group)(nil), "Group")
	proto.RegisterType((*GroupChange)(nil), "GroupChange")
	proto.RegisterType((*GroupChange_Actions)(nil), "GroupChange.Actions")
	proto.RegisterType((*GroupChange_Actions_AddMemberAction)(nil), "GroupChange.Actions.AddMemberAction")
	proto.RegisterType((*GroupChange_Actions_DeleteMemberAction)(nil), "GroupChange.Actions.DeleteMemberAction")
	proto.RegisterType((*GroupChange_Actions_ModifyMemberRoleAction)(nil), "GroupChange.Actions.ModifyMemberRoleAction")
	proto.RegisterType((*GroupChange_Actions_ModifyMemberProfileKeyAction)(nil), "GroupChange.Actions.ModifyMemberProfileKeyAction")
	proto.RegisterType((*GroupChange_Actions_AddPendingMemberAction)(nil), "GroupChange.Actions.AddPendingMemberAction")
	proto.RegisterType((*GroupChange_Actions_DeletePendingMemberAction)(nil), "GroupChange.Actions.DeletePendingMemberAction")
	proto.RegisterType((*GroupChange_Actions_PromotePendingMemberAction)(nil), "GroupChange.Actions.PromotePendingMemberAction")
	proto.RegisterType((*GroupChange_Actions_AddRequestingMemberAction)(nil), "GroupChange.Actions.AddRequestingMemberAction")
	proto.RegisterType((*GroupChange_Actions_DeleteRequestingMemberAction)(nil), "GroupChange.Actions.DeleteRequestingMemberAction")
	proto.RegisterType((*GroupChange_Actions_PromoteRequestingMemberAction)(nil), "GroupChange.Actions.PromoteRequestingMemberAction")
	proto.RegisterType((*GroupChange_Actions_ModifyTitleAction)(nil), "GroupChange.Actions.ModifyTitleAction")
	proto.RegisterType((*GroupChange_Actions_ModifyAvatarAction)(nil), "GroupChange.Actions.ModifyAvatarAction")
	proto.RegisterType((*GroupChange_Actions_ModifyDisappearingMessagesTimerAction)(nil), "GroupChange.Actions.ModifyDisappearingMessagesTimerAction")
	proto.RegisterType((*GroupChange_Actions_ModifyAttributesAccessControlAction)(nil), "GroupChange.Actions.ModifyAttributesAccessControlAction")
	proto.RegisterType((*GroupChange_Actions_ModifyMembersAccessControlAction)(nil), "GroupChange.Actions.ModifyMembersAccessControlAction")
	proto.RegisterType((*GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction)(nil), "GroupChange.Actions.ModifyAddFromInviteLinkAccessControlAction")
	proto.RegisterType((*GroupChange_Actions_ModifyInviteLinkPasswordAction)(nil), "GroupChange.Actions.ModifyInviteLinkPasswordAction")
	proto.RegisterType((*GroupChanges)(nil), "GroupChanges")
	proto.RegisterType((*GroupChanges_GroupChangeState)(nil), "GroupChanges.GroupChangeState")
	proto.RegisterType((*GroupAttributeBlob)(nil), "GroupAttributeBlob")
	proto.RegisterType((*GroupInviteLink)(nil), "GroupInviteLink")
	proto.RegisterType((*GroupInviteLink_GroupInviteLinkContentsV1)(nil), "GroupInviteLink.GroupInviteLinkContentsV1")
	proto.RegisterType((*GroupJoinInfo)(nil), "GroupJoinInfo")
}

func init() { proto.RegisterFile("Groups.proto", fileDescriptor_0760b0ffc86a42ae) }

var fileDescriptor_0760b0ffc86a42ae = []byte{
	// 1647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x73, 0xdb, 0x44,
	0x14, 0x8f, 0x6c, 0xc7, 0x4e, 0x9e, 0x3f, 0xe2, 0x2c, 0x25, 0x55, 0x34, 0x49, 0x1a, 0x4c, 0x69,
	0x4a, 0x61, 0xc4, 0x34, 0xe5, 0x6b, 0x3a, 0x94, 0x22, 0xc7, 0x29, 0x31, 0xf9, 0xa8, 0x67, 0x93,
	0x50, 0xca, 0x09, 0xc5, 0xda, 0xba, 0x6a, 0x65, 0x49, 0xec, 0xca, 0x61, 0x72, 0xa7, 0x37, 0xee,
	0xcc, 0x70, 0xe0, 0xcc, 0x09, 0xfe, 0x03, 0x4e, 0xfc, 0x21, 0xdc, 0xf8, 0x37, 0x18, 0xad, 0xd6,
	0xb6, 0xbe, 0xed, 0x29, 0xdc, 0xb4, 0x6f, 0xdf, 0x7b, 0x3f, 0xbd, 0xf7, 0xf6, 0xb7, 0x6f, 0x77,
	0xa1, 0xf6, 0x25, 0x75, 0x46, 0x2e, 0x53, 0x5d, 0xea, 0x78, 0x4e, 0xeb, 0x2f, 0x09, 0xd6, 0xb4,
	0x4b, 0xdd, 0xd3, 0xe9, 0xb9, 0x6b, 0x39, 0xba, 0xa1, 0x79, 0x1e, 0x35, 0x2f, 0x46, 0x1e, 0x61,
	0xa8, 0x09, 0xc5, 0x97, 0xe4, 0x4a, 0x96, 0xb6, 0xa5, 0xdb, 0xcb, 0xd8, 0xff, 0x44, 0x5b, 0x00,
	0x7d, 0x4a, 0x0c, 0x62, 0x7b, 0xa6, 0x6e, 0xc9, 0x05, 0x3e, 0x11, 0x92, 0xf8, 0x16, 0x7a, 0xdf,
	0x92, 0x8b, 0x81, 0x85, 0xde, 0xb7, 0xd0, 0x06, 0x2c, 0xeb, 0xd6, 0xc0, 0xa1, 0xa6, 0xf7, 0x7c,
	0x28, 0x97, 0xb8, 0x7c, 0x2a, 0x40, 0x08, 0x4a, 0x86, 0xee, 0x11, 0x79, 0x91, 0x4f, 0xf0, 0x6f,
	0xb4, 0x06, 0x65, 0xd7, 0xb1, 0xcc, 0xfe, 0x95, 0x5c, 0xe6, 0x52, 0x31, 0xf2, 0x3d, 0x31, 0x73,
	0x60, 0xeb, 0xde, 0x88, 0x12, 0xb9, 0x12, 0x78, 0x9a, 0x08, 0x5a, 0xff, 0x48, 0x50, 0x3e, 0x26,
	0xc3, 0x0b, 0x42, 0x7d, 0x07, 0x23, 0x46, 0x68, 0xd7, 0xe0, 0x7f, 0x5e, 0xc3, 0x62, 0x84, 0xb6,
	0xa1, 0x44, 0x1d, 0x8b, 0xf0, 0xdf, 0x6e, 0xec, 0xd6, 0xd4, 0x40, 0x5d, 0xc5, 0x8e, 0x45, 0x30,
	0x9f, 0xf1, 0xc3, 0x73, 0xa9, 0xf3, 0xcc, 0xb4, 0xc8, 0x21, 0xb9, 0xe2, 0x51, 0xd4, 0x70, 0x48,
	0x82, 0x5a, 0x50, 0x73, 0x29, 0x61, 0xc4, 0xf6, 0x74, 0xcf, 0x74, 0x6c, 0x1e, 0x4f, 0x0d, 0x47,
	0x64, 0xe8, 0x0e, 0x34, 0x5f, 0x38, 0xa6, 0x4d, 0x0c, 0xcd, 0xc3, 0xe4, 0xd2, 0x64, 0xbe, 0x9e,
	0x1f, 0x5e, 0x1d, 0x27, 0xe4, 0xad, 0x7b, 0x50, 0xf2, 0xd1, 0x51, 0x15, 0x2a, 0xe7, 0x27, 0x87,
	0x27, 0x8f, 0x9f, 0x9c, 0x34, 0x17, 0xfc, 0x41, 0x67, 0xff, 0x91, 0x76, 0x7e, 0x74, 0xd6, 0x94,
	0xd0, 0x2a, 0xd4, 0xb5, 0xce, 0x71, 0xf7, 0xa4, 0x7b, 0x7a, 0x86, 0xb5, 0xb3, 0xc7, 0xb8, 0x59,
	0x68, 0x79, 0x50, 0xef, 0x11, 0xdb, 0x30, 0xed, 0x81, 0x88, 0xf7, 0x06, 0x94, 0x87, 0xfc, 0x8b,
	0xc7, 0x5b, 0xdd, 0xad, 0x88, 0xc8, 0xb0, 0x10, 0xa3, 0x9b, 0x50, 0xd7, 0x0d, 0x83, 0x18, 0xed,
	0xab, 0xf3, 0x20, 0x2f, 0x05, 0xfe, 0xdf, 0x51, 0xa1, 0x9f, 0x5f, 0xcf, 0x1c, 0x12, 0xe6, 0xe9,
	0x43, 0x97, 0xc7, 0x5e, 0xc2, 0x53, 0x41, 0xeb, 0x27, 0x09, 0x9a, 0x98, 0x7c, 0x3f, 0x22, 0xcc,
	0x9b, 0x22, 0x67, 0x65, 0x3a, 0x9a, 0xc7, 0xc2, 0xcc, 0x3c, 0x16, 0x53, 0xf2, 0x18, 0xf9, 0x9d,
	0x52, 0xfc, 0x77, 0x7e, 0x2f, 0x40, 0x5d, 0xeb, 0xf7, 0x09, 0x63, 0x7b, 0x8e, 0xed, 0x51, 0xc7,
	0x42, 0x0f, 0x00, 0xf4, 0xc9, 0xd2, 0xe5, 0xff, 0xd3, 0xd8, 0xdd, 0x54, 0x23, 0x3a, 0x62, 0xe4,
	0x87, 0x61, 0x52, 0x62, 0xe0, 0x90, 0x01, 0xfa, 0x04, 0x2a, 0x41, 0xb6, 0x98, 0x58, 0x1f, 0x33,
	0x6c, 0xc7, 0xda, 0xe8, 0x10, 0x56, 0x75, 0xc3, 0x78, 0x44, 0x9d, 0x61, 0xd7, 0xbe, 0x34, 0x3d,
	0x72, 0x64, 0xda, 0x2f, 0x79, 0x40, 0x33, 0x5d, 0x24, 0xed, 0x5a, 0xdf, 0x40, 0x23, 0xaa, 0x14,
	0x5d, 0x1a, 0x15, 0x28, 0x6a, 0x27, 0x4f, 0x9b, 0x12, 0x02, 0x28, 0x1f, 0xef, 0x1f, 0xb7, 0xf7,
	0x71, 0xb3, 0x90, 0x5c, 0x22, 0x45, 0x5f, 0x74, 0x7e, 0x72, 0xaa, 0x9d, 0x75, 0x4f, 0x1f, 0x75,
	0xb5, 0xf6, 0xd1, 0x7e, 0xb3, 0xd4, 0xfa, 0xa3, 0x08, 0x8b, 0x9c, 0xf7, 0x7e, 0x62, 0xdd, 0xd1,
	0x85, 0x65, 0xf6, 0x0f, 0x05, 0xb7, 0x6b, 0x78, 0x2a, 0x40, 0xd7, 0x60, 0xd1, 0x33, 0x3d, 0xc1,
	0x92, 0x1a, 0x0e, 0x06, 0x7e, 0xa1, 0x75, 0xbe, 0x47, 0x08, 0x6a, 0x8b, 0x11, 0xfa, 0x0c, 0xd6,
	0x0d, 0x93, 0xe9, 0xae, 0x4b, 0x74, 0xca, 0x97, 0x05, 0x63, 0xfa, 0x80, 0xb0, 0x33, 0x73, 0x48,
	0xa8, 0x60, 0x47, 0xb6, 0x02, 0xfa, 0x10, 0xea, 0x7a, 0x38, 0x41, 0x9c, 0x27, 0xd5, 0xdd, 0x46,
	0x34, 0x6d, 0x38, 0xaa, 0x84, 0x14, 0x58, 0xa2, 0x63, 0x62, 0x95, 0x39, 0xb1, 0x26, 0x63, 0xf4,
	0xd6, 0xb4, 0x8a, 0x95, 0xed, 0x62, 0x98, 0x0b, 0x93, 0x7a, 0x7d, 0x0c, 0x0d, 0x37, 0x4c, 0x1f,
	0x26, 0x2f, 0x71, 0xcd, 0x86, 0x1a, 0x61, 0x15, 0x8e, 0x69, 0xa1, 0x87, 0xb0, 0x4a, 0x63, 0xeb,
	0x9f, 0xc9, 0xcb, 0xdc, 0x74, 0x55, 0x8d, 0x33, 0x03, 0x27, 0x75, 0x91, 0x0a, 0xc8, 0x9c, 0x54,
	0xba, 0xa7, 0x33, 0xf6, 0x83, 0x43, 0x0d, 0x19, 0x78, 0x92, 0x52, 0x66, 0x5a, 0xbf, 0xae, 0x43,
	0x95, 0x57, 0x6c, 0xef, 0xb9, 0x6e, 0x0f, 0x08, 0x92, 0xa1, 0xa2, 0xf7, 0x7d, 0x6a, 0x30, 0x51,
	0xb5, 0xf1, 0x10, 0xdd, 0x86, 0x15, 0x46, 0xe8, 0x25, 0xa1, 0xa7, 0x93, 0xfd, 0x31, 0xa8, 0x5e,
	0x5c, 0x8c, 0xb6, 0xa1, 0xda, 0xe7, 0xde, 0xf6, 0x5d, 0xa7, 0xff, 0x9c, 0x17, 0xb3, 0x8e, 0xc3,
	0x22, 0xe5, 0x37, 0x19, 0x2a, 0x9a, 0xf0, 0xbb, 0x05, 0xc0, 0x9c, 0x11, 0xed, 0x93, 0xf3, 0x91,
	0x39, 0xa6, 0x78, 0x48, 0x12, 0xa9, 0x44, 0x21, 0x56, 0x89, 0x0e, 0x80, 0x6e, 0x18, 0xe3, 0x3c,
	0x15, 0x79, 0x9e, 0x6e, 0xaa, 0xa1, 0x78, 0x54, 0x81, 0xa2, 0x6a, 0x63, 0xb5, 0x40, 0x80, 0x43,
	0x76, 0xe8, 0x18, 0xea, 0x06, 0xb1, 0x88, 0x47, 0xc6, 0x8e, 0x4a, 0xdc, 0xd1, 0x4e, 0xaa, 0xa3,
	0x4e, 0x48, 0x53, 0xf8, 0x8a, 0x5a, 0xa3, 0xa7, 0xb0, 0x3a, 0x74, 0x0c, 0xf3, 0xd9, 0x95, 0xa8,
	0x92, 0x63, 0x11, 0x26, 0x2f, 0x72, 0x97, 0xef, 0xa5, 0xba, 0x3c, 0x8e, 0x69, 0x0b, 0xb7, 0x49,
	0x2f, 0xe8, 0x25, 0x5c, 0x0f, 0x0b, 0x7b, 0x93, 0xcd, 0x8e, 0xc9, 0x65, 0x0e, 0x70, 0x77, 0x26,
	0xc0, 0xd4, 0x46, 0xc0, 0x64, 0x79, 0xf4, 0xe3, 0xd0, 0x0d, 0xa3, 0x17, 0x5d, 0xc6, 0x95, 0x9c,
	0x38, 0xb4, 0x98, 0xf6, 0x38, 0x8e, 0x84, 0x17, 0x74, 0x01, 0xd7, 0x82, 0x9c, 0xf5, 0xd2, 0x48,
	0xa2, 0xe6, 0x24, 0x3e, 0x0d, 0x20, 0xd5, 0x17, 0x22, 0xf0, 0xa6, 0x4b, 0x9d, 0xa1, 0x93, 0x00,
	0x09, 0xe8, 0xf4, 0x41, 0x2a, 0x48, 0x2f, 0xc5, 0x42, 0xa0, 0xa4, 0x7b, 0x43, 0x07, 0x50, 0x0d,
	0x12, 0x78, 0xc6, 0x37, 0x34, 0xe0, 0x9b, 0xcb, 0xad, 0x9c, 0x32, 0x70, 0x3d, 0xe1, 0x33, 0x6c,
	0x8a, 0x0e, 0xa1, 0x16, 0x0c, 0x83, 0x83, 0x92, 0x5c, 0xe5, 0xae, 0x76, 0x72, 0x5c, 0x05, 0x8a,
	0xc2, 0x57, 0xc4, 0x18, 0xfd, 0x28, 0xc1, 0x8d, 0x40, 0xd0, 0xc9, 0xdc, 0x3a, 0x6b, 0x1c, 0xe0,
	0x7e, 0x0e, 0x40, 0xa6, 0xad, 0xc0, 0x9c, 0x05, 0x81, 0x5c, 0x58, 0x13, 0xbf, 0x35, 0x69, 0x82,
	0xc1, 0xb6, 0x2b, 0xd7, 0x39, 0xf8, 0xa7, 0x79, 0xd1, 0xc5, 0x4c, 0xc4, 0xd6, 0x2c, 0xa0, 0x33,
	0xfc, 0x22, 0x02, 0x28, 0xbc, 0xa0, 0x05, 0x5a, 0x83, 0xa3, 0x7d, 0x34, 0x93, 0x1d, 0xa9, 0x50,
	0x29, 0x0e, 0xd1, 0x2b, 0x09, 0x36, 0xc5, 0x1f, 0xc4, 0xfb, 0xab, 0x80, 0x5c, 0xe1, 0x90, 0x0f,
	0xf3, 0x02, 0x4c, 0xb7, 0x8c, 0x82, 0xe7, 0xa3, 0xf8, 0x4c, 0xd2, 0x0d, 0x03, 0x27, 0x7a, 0x46,
	0x33, 0x87, 0x49, 0x5a, 0xd2, 0x60, 0xcc, 0xa4, 0x34, 0x5f, 0xfe, 0xae, 0x13, 0x30, 0x2c, 0x09,
	0xb3, 0x9a, 0xb3, 0xeb, 0x74, 0x52, 0x6d, 0xc6, 0xbb, 0x4e, 0x86, 0x47, 0x64, 0x83, 0x2c, 0x88,
	0x96, 0x44, 0x43, 0x1c, 0x6d, 0x37, 0x8f, 0xb9, 0x19, 0x70, 0x99, 0x3e, 0x91, 0x03, 0x72, 0x90,
	0xe1, 0x6e, 0xb2, 0x6d, 0xbe, 0xc1, 0x4b, 0x78, 0x2f, 0xa7, 0x84, 0x49, 0xa3, 0x31, 0x60, 0x96,
	0x53, 0xe5, 0x3b, 0x58, 0x89, 0x35, 0x23, 0xb4, 0x09, 0x8b, 0xfc, 0x94, 0x1c, 0x3f, 0x5a, 0x07,
	0x52, 0xbf, 0xa7, 0xfb, 0x87, 0xfa, 0xd8, 0xe9, 0xcf, 0xef, 0x85, 0x4b, 0x38, 0x65, 0x46, 0xb9,
	0x0f, 0x28, 0xd9, 0xa5, 0xfc, 0xf3, 0x79, 0x90, 0x73, 0xe3, 0x3c, 0x7c, 0x9a, 0x8e, 0x0a, 0x15,
	0x0c, 0x6b, 0xe9, 0xed, 0xe8, 0xf5, 0x2f, 0x3c, 0x4a, 0x1b, 0x36, 0xf2, 0x3a, 0x50, 0xe2, 0xa0,
	0x2e, 0x25, 0x0f, 0xea, 0xca, 0xe7, 0xb0, 0x96, 0xde, 0x5e, 0xd0, 0xcd, 0x68, 0xf2, 0xe2, 0x27,
	0xac, 0x60, 0x52, 0xd1, 0x60, 0x3d, 0xb3, 0x81, 0xcc, 0x99, 0x9a, 0x2f, 0x40, 0xc9, 0x6e, 0x0f,
	0x73, 0x05, 0xd1, 0x81, 0xf5, 0x4c, 0xee, 0xa1, 0x9d, 0x68, 0x1c, 0x29, 0xc7, 0x3d, 0x11, 0x4a,
	0x07, 0x36, 0xf2, 0xa8, 0x35, 0x67, 0x34, 0x4f, 0x61, 0x33, 0x97, 0x32, 0xff, 0xa1, 0xde, 0xef,
	0xc2, 0x6a, 0xa2, 0xd5, 0x4d, 0x8f, 0xfc, 0x52, 0xe8, 0xc8, 0xaf, 0xbc, 0x0f, 0x28, 0xd9, 0xca,
	0x42, 0x17, 0x01, 0x29, 0x7c, 0x11, 0x50, 0x1e, 0xc0, 0x3b, 0x73, 0xf5, 0xa5, 0x00, 0x6c, 0x28,
	0xee, 0xaa, 0x1c, 0x6c, 0x48, 0xa8, 0xe2, 0xc2, 0xdb, 0x73, 0x74, 0x16, 0xd4, 0x85, 0xa6, 0x1e,
	0xef, 0x56, 0x73, 0xdd, 0xf4, 0x12, 0x66, 0xca, 0x00, 0xb6, 0x67, 0x75, 0x17, 0xb4, 0x07, 0xf5,
	0x61, 0x78, 0x76, 0x3e, 0xac, 0xa8, 0x8d, 0xf2, 0x4a, 0x82, 0x3b, 0xf3, 0x37, 0x15, 0xf4, 0x04,
	0xae, 0xeb, 0x19, 0x6d, 0x6b, 0x2e, 0xf4, 0x2c, 0x6b, 0xa5, 0x07, 0x5b, 0xf9, 0x1b, 0x63, 0xc6,
	0x05, 0x45, 0xca, 0xbc, 0xa0, 0xfc, 0x29, 0x89, 0xa7, 0xa4, 0x60, 0xff, 0x65, 0xa8, 0x0d, 0xb5,
	0x41, 0x68, 0x2c, 0x4b, 0xbc, 0x29, 0x6c, 0x85, 0x37, 0x69, 0x16, 0x1e, 0x9c, 0x7a, 0xba, 0x47,
	0x70, 0xc4, 0x46, 0x79, 0x01, 0xcd, 0xb8, 0x06, 0x52, 0xa1, 0x1a, 0xd2, 0x11, 0x2c, 0xac, 0x85,
	0x3d, 0xe1, 0xb0, 0x02, 0xba, 0x05, 0xc0, 0x87, 0xdc, 0x9a, 0xb3, 0xa1, 0xba, 0x5b, 0x0e, 0xd4,
	0x71, 0x68, 0xa6, 0xf5, 0xb3, 0x04, 0x88, 0x4b, 0x27, 0xab, 0xae, 0x6d, 0x39, 0x17, 0x68, 0x2d,
	0xcc, 0x87, 0xe5, 0x83, 0x85, 0xf1, 0x25, 0x58, 0x9e, 0xac, 0x7d, 0x7e, 0xbb, 0x3a, 0x58, 0x98,
	0x5c, 0x83, 0x3b, 0xb0, 0x91, 0x76, 0xcb, 0xed, 0x8c, 0xe8, 0xf4, 0x7d, 0xa3, 0x7e, 0xb0, 0x80,
	0x73, 0xb5, 0xda, 0xcb, 0x50, 0xe9, 0x3b, 0xb6, 0x47, 0x6c, 0xaf, 0xf5, 0xb7, 0x04, 0x2b, 0xfc,
	0xcf, 0xa6, 0xc5, 0x42, 0x47, 0x00, 0x97, 0x77, 0xf7, 0x02, 0x05, 0x26, 0x92, 0x70, 0x47, 0x8d,
	0x69, 0xc5, 0xc7, 0x63, 0xfd, 0xaf, 0xef, 0x1e, 0x2c, 0xe0, 0x90, 0xbd, 0xc2, 0x60, 0x3d, 0x53,
	0x15, 0xdd, 0x82, 0x06, 0x4f, 0xd3, 0xb1, 0xce, 0x3c, 0x42, 0xa7, 0xef, 0x04, 0x31, 0x69, 0xc6,
	0x8a, 0x29, 0x64, 0xad, 0x98, 0x36, 0xc0, 0x92, 0x88, 0x90, 0xb5, 0x7e, 0x29, 0x40, 0x9d, 0xff,
	0xc1, 0x57, 0x8e, 0x69, 0x77, 0xed, 0x67, 0xce, 0xff, 0xfa, 0x30, 0xb1, 0x0d, 0xd5, 0x80, 0x86,
	0x7b, 0xce, 0xc8, 0xf6, 0xf8, 0x53, 0x44, 0x1d, 0x87, 0x45, 0xe9, 0xef, 0x36, 0x8b, 0xaf, 0xf7,
	0x6e, 0x93, 0xfb, 0x26, 0xb1, 0x0b, 0xd7, 0xc4, 0x53, 0x82, 0x66, 0x0c, 0x4d, 0x5b, 0x73, 0x5d,
	0xea, 0x5c, 0xea, 0x16, 0x7f, 0xc2, 0x5c, 0xc2, 0xa9, 0x73, 0xed, 0xfb, 0xb0, 0xe3, 0xd0, 0x81,
	0xca, 0x9f, 0x37, 0x2d, 0x95, 0x79, 0x0e, 0xf5, 0x57, 0x0a, 0xa1, 0x97, 0x66, 0x9f, 0x04, 0xef,
	0xb6, 0x4c, 0xe5, 0xb5, 0x60, 0x3d, 0xe9, 0xdb, 0x7a, 0xa0, 0x26, 0xa6, 0x2f, 0xca, 0x7c, 0xfe,
	0xde, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68, 0xec, 0x1e, 0x78, 0xe7, 0x15, 0x00, 0x00,
}
