// Code generated by protoc-gen-go. DO NOT EDIT.
// source: InternalSerialization.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignalServiceContentProto struct {
	LocalAddress *AddressProto  `protobuf:"bytes,1,opt,name=localAddress" json:"localAddress,omitempty"`
	Metadata     *MetadataProto `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*SignalServiceContentProto_LegacyDataMessage
	//	*SignalServiceContentProto_Content
	Data                 isSignalServiceContentProto_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SignalServiceContentProto) Reset()         { *m = SignalServiceContentProto{} }
func (m *SignalServiceContentProto) String() string { return proto.CompactTextString(m) }
func (*SignalServiceContentProto) ProtoMessage()    {}
func (*SignalServiceContentProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2acddae6895657, []int{0}
}

func (m *SignalServiceContentProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalServiceContentProto.Unmarshal(m, b)
}
func (m *SignalServiceContentProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalServiceContentProto.Marshal(b, m, deterministic)
}
func (m *SignalServiceContentProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalServiceContentProto.Merge(m, src)
}
func (m *SignalServiceContentProto) XXX_Size() int {
	return xxx_messageInfo_SignalServiceContentProto.Size(m)
}
func (m *SignalServiceContentProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalServiceContentProto.DiscardUnknown(m)
}

var xxx_messageInfo_SignalServiceContentProto proto.InternalMessageInfo

func (m *SignalServiceContentProto) GetLocalAddress() *AddressProto {
	if m != nil {
		return m.LocalAddress
	}
	return nil
}

func (m *SignalServiceContentProto) GetMetadata() *MetadataProto {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type isSignalServiceContentProto_Data interface {
	isSignalServiceContentProto_Data()
}

type SignalServiceContentProto_LegacyDataMessage struct {
	LegacyDataMessage *DataMessage `protobuf:"bytes,3,opt,name=legacyDataMessage,oneof"`
}

type SignalServiceContentProto_Content struct {
	Content *Content `protobuf:"bytes,4,opt,name=content,oneof"`
}

func (*SignalServiceContentProto_LegacyDataMessage) isSignalServiceContentProto_Data() {}

func (*SignalServiceContentProto_Content) isSignalServiceContentProto_Data() {}

func (m *SignalServiceContentProto) GetData() isSignalServiceContentProto_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignalServiceContentProto) GetLegacyDataMessage() *DataMessage {
	if x, ok := m.GetData().(*SignalServiceContentProto_LegacyDataMessage); ok {
		return x.LegacyDataMessage
	}
	return nil
}

func (m *SignalServiceContentProto) GetContent() *Content {
	if x, ok := m.GetData().(*SignalServiceContentProto_Content); ok {
		return x.Content
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SignalServiceContentProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SignalServiceContentProto_LegacyDataMessage)(nil),
		(*SignalServiceContentProto_Content)(nil),
	}
}

type MetadataProto struct {
	Address                  *AddressProto `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	SenderDevice             *int32        `protobuf:"varint,2,opt,name=senderDevice" json:"senderDevice,omitempty"`
	Timestamp                *int64        `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	ServerReceivedTimestamp  *int64        `protobuf:"varint,5,opt,name=serverReceivedTimestamp" json:"serverReceivedTimestamp,omitempty"`
	ServerDeliveredTimestamp *int64        `protobuf:"varint,6,opt,name=serverDeliveredTimestamp" json:"serverDeliveredTimestamp,omitempty"`
	NeedsReceipt             *bool         `protobuf:"varint,4,opt,name=needsReceipt" json:"needsReceipt,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}      `json:"-"`
	XXX_unrecognized         []byte        `json:"-"`
	XXX_sizecache            int32         `json:"-"`
}

func (m *MetadataProto) Reset()         { *m = MetadataProto{} }
func (m *MetadataProto) String() string { return proto.CompactTextString(m) }
func (*MetadataProto) ProtoMessage()    {}
func (*MetadataProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2acddae6895657, []int{1}
}

func (m *MetadataProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataProto.Unmarshal(m, b)
}
func (m *MetadataProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataProto.Marshal(b, m, deterministic)
}
func (m *MetadataProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataProto.Merge(m, src)
}
func (m *MetadataProto) XXX_Size() int {
	return xxx_messageInfo_MetadataProto.Size(m)
}
func (m *MetadataProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataProto.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataProto proto.InternalMessageInfo

func (m *MetadataProto) GetAddress() *AddressProto {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MetadataProto) GetSenderDevice() int32 {
	if m != nil && m.SenderDevice != nil {
		return *m.SenderDevice
	}
	return 0
}

func (m *MetadataProto) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *MetadataProto) GetServerReceivedTimestamp() int64 {
	if m != nil && m.ServerReceivedTimestamp != nil {
		return *m.ServerReceivedTimestamp
	}
	return 0
}

func (m *MetadataProto) GetServerDeliveredTimestamp() int64 {
	if m != nil && m.ServerDeliveredTimestamp != nil {
		return *m.ServerDeliveredTimestamp
	}
	return 0
}

func (m *MetadataProto) GetNeedsReceipt() bool {
	if m != nil && m.NeedsReceipt != nil {
		return *m.NeedsReceipt
	}
	return false
}

type AddressProto struct {
	Uuid                 []byte   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	E164                 *string  `protobuf:"bytes,2,opt,name=e164" json:"e164,omitempty"`
	Relay                *string  `protobuf:"bytes,3,opt,name=relay" json:"relay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressProto) Reset()         { *m = AddressProto{} }
func (m *AddressProto) String() string { return proto.CompactTextString(m) }
func (*AddressProto) ProtoMessage()    {}
func (*AddressProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2acddae6895657, []int{2}
}

func (m *AddressProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressProto.Unmarshal(m, b)
}
func (m *AddressProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressProto.Marshal(b, m, deterministic)
}
func (m *AddressProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressProto.Merge(m, src)
}
func (m *AddressProto) XXX_Size() int {
	return xxx_messageInfo_AddressProto.Size(m)
}
func (m *AddressProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressProto.DiscardUnknown(m)
}

var xxx_messageInfo_AddressProto proto.InternalMessageInfo

func (m *AddressProto) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *AddressProto) GetE164() string {
	if m != nil && m.E164 != nil {
		return *m.E164
	}
	return ""
}

func (m *AddressProto) GetRelay() string {
	if m != nil && m.Relay != nil {
		return *m.Relay
	}
	return ""
}

func init() {
	proto.RegisterType((*SignalServiceContentProto)(nil), "textsecure.SignalServiceContentProto")
	proto.RegisterType((*MetadataProto)(nil), "textsecure.MetadataProto")
	proto.RegisterType((*AddressProto)(nil), "textsecure.AddressProto")
}

func init() { proto.RegisterFile("InternalSerialization.proto", fileDescriptor_3a2acddae6895657) }

var fileDescriptor_3a2acddae6895657 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x8a, 0xd3, 0x50,
	0x10, 0xc6, 0xfb, 0xdf, 0x76, 0x8c, 0x17, 0x1e, 0x45, 0xd3, 0xea, 0x85, 0xe4, 0xca, 0xab, 0x80,
	0x45, 0x45, 0x8a, 0x08, 0xd6, 0x5e, 0x54, 0xb1, 0x50, 0x4e, 0xf7, 0x05, 0x0e, 0xc9, 0x90, 0x3d,
	0x90, 0x7f, 0x9c, 0x39, 0xed, 0x6e, 0xf7, 0x49, 0xf6, 0x6e, 0x5f, 0x75, 0xc9, 0x24, 0x6d, 0x93,
	0x2e, 0x85, 0xbd, 0x3b, 0x9d, 0xf9, 0x7d, 0xd3, 0xef, 0x9b, 0x0c, 0x7c, 0xf8, 0x9b, 0x5a, 0x34,
	0xa9, 0x8a, 0x37, 0x68, 0xb4, 0x8a, 0xf5, 0x9d, 0xb2, 0x3a, 0x4b, 0xfd, 0xdc, 0x64, 0x36, 0x13,
	0x60, 0xf1, 0xd6, 0x12, 0x06, 0x5b, 0x83, 0x93, 0x37, 0x1b, 0x1d, 0x95, 0xd8, 0x4e, 0x07, 0x58,
	0x02, 0xde, 0x7d, 0x07, 0xc6, 0x8d, 0xfa, 0x9f, 0x2c, 0xb5, 0x98, 0xda, 0x35, 0xcb, 0x7f, 0x82,
	0x13, 0x67, 0x81, 0x8a, 0x7f, 0x87, 0xa1, 0x41, 0x22, 0xb7, 0xfd, 0xa9, 0xfd, 0xf9, 0xe5, 0xd4,
	0xf5, 0x4f, 0x53, 0xfd, 0xaa, 0xc5, 0xbc, 0x6c, 0xd0, 0xe2, 0x1b, 0x0c, 0x13, 0xb4, 0x2a, 0x54,
	0x56, 0xb9, 0x1d, 0x56, 0x8e, 0xeb, 0xca, 0x55, 0xd5, 0x2b, 0xa5, 0x47, 0x54, 0xfc, 0x83, 0xd7,
	0x31, 0x46, 0x2a, 0xd8, 0x2f, 0x94, 0x55, 0x2b, 0x24, 0x52, 0x11, 0xba, 0x5d, 0xd6, 0x4f, 0x7c,
	0x62, 0xaf, 0x54, 0x65, 0xa8, 0x11, 0xcb, 0x96, 0x7c, 0x2a, 0x13, 0x53, 0x78, 0x11, 0x94, 0x81,
	0xdc, 0x1e, 0x4f, 0x78, 0x77, 0x36, 0xa1, 0x8a, 0xbb, 0x6c, 0xc9, 0x03, 0x38, 0x1f, 0x40, 0xaf,
	0xf0, 0xe1, 0x3d, 0x74, 0xe0, 0x55, 0xc3, 0x63, 0x31, 0x4d, 0x3d, 0x73, 0x13, 0x07, 0x50, 0x78,
	0xe0, 0x10, 0xa6, 0x21, 0x9a, 0x05, 0x16, 0x7f, 0xc8, 0x8b, 0xe8, 0xcb, 0x46, 0x4d, 0x7c, 0x84,
	0x91, 0xd5, 0x09, 0x92, 0x55, 0x49, 0xce, 0x49, 0xbb, 0xf2, 0x54, 0x10, 0x3f, 0xe0, 0x7d, 0xe1,
	0x16, 0x8d, 0xc4, 0x00, 0xf5, 0x0e, 0xc3, 0xab, 0x23, 0xdb, 0x67, 0xf6, 0x52, 0x5b, 0xcc, 0xc0,
	0x2d, 0x5b, 0x0b, 0x8c, 0xf5, 0x0e, 0x4d, 0x5d, 0x3a, 0x60, 0xe9, 0xc5, 0x7e, 0xe1, 0x3b, 0x45,
	0x0c, 0x89, 0xa7, 0xe6, 0xe5, 0xfa, 0x86, 0xb2, 0x51, 0xf3, 0xfe, 0x83, 0x53, 0x0f, 0x2d, 0x04,
	0xf4, 0xb6, 0x5b, 0x1d, 0xf2, 0x72, 0x1c, 0xc9, 0xef, 0xa2, 0x86, 0x5f, 0xbe, 0x7f, 0xe5, 0xdc,
	0x23, 0xc9, 0x6f, 0xf1, 0x16, 0xfa, 0x06, 0x63, 0xb5, 0xe7, 0xac, 0x23, 0x59, 0xfe, 0x98, 0xff,
	0x82, 0x59, 0x66, 0x22, 0xff, 0xe6, 0x5a, 0x53, 0x8e, 0x86, 0xf6, 0x64, 0x31, 0xa1, 0xb3, 0xcf,
	0xa5, 0xab, 0x5b, 0xf7, 0xa9, 0x3a, 0xf6, 0xea, 0x8e, 0x69, 0xdd, 0x7e, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0x24, 0xba, 0x00, 0xf6, 0x09, 0x03, 0x00, 0x00,
}
