//*
// Copyright (C) 2019 Open Whisper Systems
//
// Licensed according to the LICENSE file in this repository.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: KeyBackupService.proto

package signalservice

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BackupResponse_Status int32

const (
	BackupResponse_OK             BackupResponse_Status = 1
	BackupResponse_ALREADY_EXISTS BackupResponse_Status = 2
	BackupResponse_NOT_YET_VALID  BackupResponse_Status = 3
)

// Enum value maps for BackupResponse_Status.
var (
	BackupResponse_Status_name = map[int32]string{
		1: "OK",
		2: "ALREADY_EXISTS",
		3: "NOT_YET_VALID",
	}
	BackupResponse_Status_value = map[string]int32{
		"OK":             1,
		"ALREADY_EXISTS": 2,
		"NOT_YET_VALID":  3,
	}
)

func (x BackupResponse_Status) Enum() *BackupResponse_Status {
	p := new(BackupResponse_Status)
	*p = x
	return p
}

func (x BackupResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_KeyBackupService_proto_enumTypes[0].Descriptor()
}

func (BackupResponse_Status) Type() protoreflect.EnumType {
	return &file_KeyBackupService_proto_enumTypes[0]
}

func (x BackupResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BackupResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BackupResponse_Status(num)
	return nil
}

// Deprecated: Use BackupResponse_Status.Descriptor instead.
func (BackupResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{3, 0}
}

type RestoreResponse_Status int32

const (
	RestoreResponse_OK             RestoreResponse_Status = 1
	RestoreResponse_TOKEN_MISMATCH RestoreResponse_Status = 2
	RestoreResponse_NOT_YET_VALID  RestoreResponse_Status = 3
	RestoreResponse_MISSING        RestoreResponse_Status = 4
	RestoreResponse_PIN_MISMATCH   RestoreResponse_Status = 5
)

// Enum value maps for RestoreResponse_Status.
var (
	RestoreResponse_Status_name = map[int32]string{
		1: "OK",
		2: "TOKEN_MISMATCH",
		3: "NOT_YET_VALID",
		4: "MISSING",
		5: "PIN_MISMATCH",
	}
	RestoreResponse_Status_value = map[string]int32{
		"OK":             1,
		"TOKEN_MISMATCH": 2,
		"NOT_YET_VALID":  3,
		"MISSING":        4,
		"PIN_MISMATCH":   5,
	}
)

func (x RestoreResponse_Status) Enum() *RestoreResponse_Status {
	p := new(RestoreResponse_Status)
	*p = x
	return p
}

func (x RestoreResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestoreResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_KeyBackupService_proto_enumTypes[1].Descriptor()
}

func (RestoreResponse_Status) Type() protoreflect.EnumType {
	return &file_KeyBackupService_proto_enumTypes[1]
}

func (x RestoreResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RestoreResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RestoreResponse_Status(num)
	return nil
}

// Deprecated: Use RestoreResponse_Status.Descriptor instead.
func (RestoreResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{5, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backup  *BackupRequest  `protobuf:"bytes,1,opt,name=backup" json:"backup,omitempty"`
	Restore *RestoreRequest `protobuf:"bytes,2,opt,name=restore" json:"restore,omitempty"`
	Delete  *DeleteRequest  `protobuf:"bytes,3,opt,name=delete" json:"delete,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyBackupService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_KeyBackupService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetBackup() *BackupRequest {
	if x != nil {
		return x.Backup
	}
	return nil
}

func (x *Request) GetRestore() *RestoreRequest {
	if x != nil {
		return x.Restore
	}
	return nil
}

func (x *Request) GetDelete() *DeleteRequest {
	if x != nil {
		return x.Delete
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backup  *BackupResponse  `protobuf:"bytes,1,opt,name=backup" json:"backup,omitempty"`
	Restore *RestoreResponse `protobuf:"bytes,2,opt,name=restore" json:"restore,omitempty"`
	Delete  *DeleteResponse  `protobuf:"bytes,3,opt,name=delete" json:"delete,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyBackupService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_KeyBackupService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetBackup() *BackupResponse {
	if x != nil {
		return x.Backup
	}
	return nil
}

func (x *Response) GetRestore() *RestoreResponse {
	if x != nil {
		return x.Restore
	}
	return nil
}

func (x *Response) GetDelete() *DeleteResponse {
	if x != nil {
		return x.Delete
	}
	return nil
}

type BackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId []byte  `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	BackupId  []byte  `protobuf:"bytes,2,opt,name=backup_id,json=backupId" json:"backup_id,omitempty"`
	Token     []byte  `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	ValidFrom *uint64 `protobuf:"varint,4,opt,name=valid_from,json=validFrom" json:"valid_from,omitempty"`
	Data      []byte  `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	Pin       []byte  `protobuf:"bytes,6,opt,name=pin" json:"pin,omitempty"`
	Tries     *uint32 `protobuf:"varint,7,opt,name=tries" json:"tries,omitempty"`
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyBackupService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KeyBackupService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{2}
}

func (x *BackupRequest) GetServiceId() []byte {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *BackupRequest) GetBackupId() []byte {
	if x != nil {
		return x.BackupId
	}
	return nil
}

func (x *BackupRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *BackupRequest) GetValidFrom() uint64 {
	if x != nil && x.ValidFrom != nil {
		return *x.ValidFrom
	}
	return 0
}

func (x *BackupRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BackupRequest) GetPin() []byte {
	if x != nil {
		return x.Pin
	}
	return nil
}

func (x *BackupRequest) GetTries() uint32 {
	if x != nil && x.Tries != nil {
		return *x.Tries
	}
	return 0
}

type BackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *BackupResponse_Status `protobuf:"varint,1,opt,name=status,enum=textsecure.BackupResponse_Status" json:"status,omitempty"`
	Token  []byte                 `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyBackupService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_KeyBackupService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{3}
}

func (x *BackupResponse) GetStatus() BackupResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return BackupResponse_OK
}

func (x *BackupResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId []byte  `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	BackupId  []byte  `protobuf:"bytes,2,opt,name=backup_id,json=backupId" json:"backup_id,omitempty"`
	Token     []byte  `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	ValidFrom *uint64 `protobuf:"varint,4,opt,name=valid_from,json=validFrom" json:"valid_from,omitempty"`
	Pin       []byte  `protobuf:"bytes,5,opt,name=pin" json:"pin,omitempty"`
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyBackupService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KeyBackupService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreRequest) GetServiceId() []byte {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *RestoreRequest) GetBackupId() []byte {
	if x != nil {
		return x.BackupId
	}
	return nil
}

func (x *RestoreRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RestoreRequest) GetValidFrom() uint64 {
	if x != nil && x.ValidFrom != nil {
		return *x.ValidFrom
	}
	return 0
}

func (x *RestoreRequest) GetPin() []byte {
	if x != nil {
		return x.Pin
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *RestoreResponse_Status `protobuf:"varint,1,opt,name=status,enum=textsecure.RestoreResponse_Status" json:"status,omitempty"`
	Token  []byte                  `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Data   []byte                  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Tries  *uint32                 `protobuf:"varint,4,opt,name=tries" json:"tries,omitempty"`
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyBackupService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_KeyBackupService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreResponse) GetStatus() RestoreResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return RestoreResponse_OK
}

func (x *RestoreResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RestoreResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RestoreResponse) GetTries() uint32 {
	if x != nil && x.Tries != nil {
		return *x.Tries
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId []byte `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	BackupId  []byte `protobuf:"bytes,2,opt,name=backup_id,json=backupId" json:"backup_id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyBackupService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KeyBackupService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetServiceId() []byte {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *DeleteRequest) GetBackupId() []byte {
	if x != nil {
		return x.BackupId
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KeyBackupService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_KeyBackupService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_KeyBackupService_proto_rawDescGZIP(), []int{7}
}

var File_KeyBackupService_proto protoreflect.FileDescriptor

var file_KeyBackupService_proto_rawDesc = []byte{
	0x0a, 0x16, 0x4b, 0x65, 0x79, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x65, 0x22, 0xa5, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x62, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x65, 0x78, 0x74,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0xa9, 0x01, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x62, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x78, 0x74,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x35, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x0d, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x69,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x74, 0x65, 0x78,
	0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x37, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10,
	0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x5f, 0x59, 0x45, 0x54, 0x5f, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x03, 0x22, 0x93, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x22, 0xe5, 0x01, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22,
	0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x4d, 0x49, 0x53, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x02,
	0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x5f, 0x59, 0x45, 0x54, 0x5f, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x04,
	0x12, 0x10, 0x0a, 0x0c, 0x50, 0x49, 0x4e, 0x5f, 0x4d, 0x49, 0x53, 0x4d, 0x41, 0x54, 0x43, 0x48,
	0x10, 0x05, 0x22, 0x4b, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x64, 0x22,
	0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x4f, 0x0a, 0x3a, 0x6f, 0x72, 0x67, 0x2e, 0x77, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x6b,
	0x65, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x50,
	0x01, 0x5a, 0x0f, 0x2e, 0x3b, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65,
}

var (
	file_KeyBackupService_proto_rawDescOnce sync.Once
	file_KeyBackupService_proto_rawDescData = file_KeyBackupService_proto_rawDesc
)

func file_KeyBackupService_proto_rawDescGZIP() []byte {
	file_KeyBackupService_proto_rawDescOnce.Do(func() {
		file_KeyBackupService_proto_rawDescData = protoimpl.X.CompressGZIP(file_KeyBackupService_proto_rawDescData)
	})
	return file_KeyBackupService_proto_rawDescData
}

var file_KeyBackupService_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_KeyBackupService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_KeyBackupService_proto_goTypes = []interface{}{
	(BackupResponse_Status)(0),  // 0: textsecure.BackupResponse.Status
	(RestoreResponse_Status)(0), // 1: textsecure.RestoreResponse.Status
	(*Request)(nil),             // 2: textsecure.Request
	(*Response)(nil),            // 3: textsecure.Response
	(*BackupRequest)(nil),       // 4: textsecure.BackupRequest
	(*BackupResponse)(nil),      // 5: textsecure.BackupResponse
	(*RestoreRequest)(nil),      // 6: textsecure.RestoreRequest
	(*RestoreResponse)(nil),     // 7: textsecure.RestoreResponse
	(*DeleteRequest)(nil),       // 8: textsecure.DeleteRequest
	(*DeleteResponse)(nil),      // 9: textsecure.DeleteResponse
}
var file_KeyBackupService_proto_depIdxs = []int32{
	4, // 0: textsecure.Request.backup:type_name -> textsecure.BackupRequest
	6, // 1: textsecure.Request.restore:type_name -> textsecure.RestoreRequest
	8, // 2: textsecure.Request.delete:type_name -> textsecure.DeleteRequest
	5, // 3: textsecure.Response.backup:type_name -> textsecure.BackupResponse
	7, // 4: textsecure.Response.restore:type_name -> textsecure.RestoreResponse
	9, // 5: textsecure.Response.delete:type_name -> textsecure.DeleteResponse
	0, // 6: textsecure.BackupResponse.status:type_name -> textsecure.BackupResponse.Status
	1, // 7: textsecure.RestoreResponse.status:type_name -> textsecure.RestoreResponse.Status
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_KeyBackupService_proto_init() }
func file_KeyBackupService_proto_init() {
	if File_KeyBackupService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_KeyBackupService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyBackupService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyBackupService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyBackupService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyBackupService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyBackupService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyBackupService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KeyBackupService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KeyBackupService_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KeyBackupService_proto_goTypes,
		DependencyIndexes: file_KeyBackupService_proto_depIdxs,
		EnumInfos:         file_KeyBackupService_proto_enumTypes,
		MessageInfos:      file_KeyBackupService_proto_msgTypes,
	}.Build()
	File_KeyBackupService_proto = out.File
	file_KeyBackupService_proto_rawDesc = nil
	file_KeyBackupService_proto_goTypes = nil
	file_KeyBackupService_proto_depIdxs = nil
}
