// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KeyBackupService.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BackupResponse_Status int32

const (
	BackupResponse_OK             BackupResponse_Status = 1
	BackupResponse_ALREADY_EXISTS BackupResponse_Status = 2
	BackupResponse_NOT_YET_VALID  BackupResponse_Status = 3
)

var BackupResponse_Status_name = map[int32]string{
	1: "OK",
	2: "ALREADY_EXISTS",
	3: "NOT_YET_VALID",
}

var BackupResponse_Status_value = map[string]int32{
	"OK":             1,
	"ALREADY_EXISTS": 2,
	"NOT_YET_VALID":  3,
}

func (x BackupResponse_Status) Enum() *BackupResponse_Status {
	p := new(BackupResponse_Status)
	*p = x
	return p
}

func (x BackupResponse_Status) String() string {
	return proto.EnumName(BackupResponse_Status_name, int32(x))
}

func (x *BackupResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BackupResponse_Status_value, data, "BackupResponse_Status")
	if err != nil {
		return err
	}
	*x = BackupResponse_Status(value)
	return nil
}

func (BackupResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{3, 0}
}

type RestoreResponse_Status int32

const (
	RestoreResponse_OK             RestoreResponse_Status = 1
	RestoreResponse_TOKEN_MISMATCH RestoreResponse_Status = 2
	RestoreResponse_NOT_YET_VALID  RestoreResponse_Status = 3
	RestoreResponse_MISSING        RestoreResponse_Status = 4
	RestoreResponse_PIN_MISMATCH   RestoreResponse_Status = 5
)

var RestoreResponse_Status_name = map[int32]string{
	1: "OK",
	2: "TOKEN_MISMATCH",
	3: "NOT_YET_VALID",
	4: "MISSING",
	5: "PIN_MISMATCH",
}

var RestoreResponse_Status_value = map[string]int32{
	"OK":             1,
	"TOKEN_MISMATCH": 2,
	"NOT_YET_VALID":  3,
	"MISSING":        4,
	"PIN_MISMATCH":   5,
}

func (x RestoreResponse_Status) Enum() *RestoreResponse_Status {
	p := new(RestoreResponse_Status)
	*p = x
	return p
}

func (x RestoreResponse_Status) String() string {
	return proto.EnumName(RestoreResponse_Status_name, int32(x))
}

func (x *RestoreResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RestoreResponse_Status_value, data, "RestoreResponse_Status")
	if err != nil {
		return err
	}
	*x = RestoreResponse_Status(value)
	return nil
}

func (RestoreResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{5, 0}
}

type Request struct {
	Backup               *BackupRequest  `protobuf:"bytes,1,opt,name=backup" json:"backup,omitempty"`
	Restore              *RestoreRequest `protobuf:"bytes,2,opt,name=restore" json:"restore,omitempty"`
	Delete               *DeleteRequest  `protobuf:"bytes,3,opt,name=delete" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetBackup() *BackupRequest {
	if m != nil {
		return m.Backup
	}
	return nil
}

func (m *Request) GetRestore() *RestoreRequest {
	if m != nil {
		return m.Restore
	}
	return nil
}

func (m *Request) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

type Response struct {
	Backup               *BackupResponse  `protobuf:"bytes,1,opt,name=backup" json:"backup,omitempty"`
	Restore              *RestoreResponse `protobuf:"bytes,2,opt,name=restore" json:"restore,omitempty"`
	Delete               *DeleteResponse  `protobuf:"bytes,3,opt,name=delete" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBackup() *BackupResponse {
	if m != nil {
		return m.Backup
	}
	return nil
}

func (m *Response) GetRestore() *RestoreResponse {
	if m != nil {
		return m.Restore
	}
	return nil
}

func (m *Response) GetDelete() *DeleteResponse {
	if m != nil {
		return m.Delete
	}
	return nil
}

type BackupRequest struct {
	ServiceId            []byte   `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	BackupId             []byte   `protobuf:"bytes,2,opt,name=backup_id,json=backupId" json:"backup_id,omitempty"`
	Token                []byte   `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	ValidFrom            *uint64  `protobuf:"varint,4,opt,name=valid_from,json=validFrom" json:"valid_from,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	Pin                  []byte   `protobuf:"bytes,6,opt,name=pin" json:"pin,omitempty"`
	Tries                *uint32  `protobuf:"varint,7,opt,name=tries" json:"tries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupRequest) Reset()         { *m = BackupRequest{} }
func (m *BackupRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRequest) ProtoMessage()    {}
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{2}
}

func (m *BackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRequest.Unmarshal(m, b)
}
func (m *BackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRequest.Marshal(b, m, deterministic)
}
func (m *BackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRequest.Merge(m, src)
}
func (m *BackupRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRequest.Size(m)
}
func (m *BackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRequest proto.InternalMessageInfo

func (m *BackupRequest) GetServiceId() []byte {
	if m != nil {
		return m.ServiceId
	}
	return nil
}

func (m *BackupRequest) GetBackupId() []byte {
	if m != nil {
		return m.BackupId
	}
	return nil
}

func (m *BackupRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *BackupRequest) GetValidFrom() uint64 {
	if m != nil && m.ValidFrom != nil {
		return *m.ValidFrom
	}
	return 0
}

func (m *BackupRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BackupRequest) GetPin() []byte {
	if m != nil {
		return m.Pin
	}
	return nil
}

func (m *BackupRequest) GetTries() uint32 {
	if m != nil && m.Tries != nil {
		return *m.Tries
	}
	return 0
}

type BackupResponse struct {
	Status               *BackupResponse_Status `protobuf:"varint,1,opt,name=status,enum=textsecure.BackupResponse_Status" json:"status,omitempty"`
	Token                []byte                 `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BackupResponse) Reset()         { *m = BackupResponse{} }
func (m *BackupResponse) String() string { return proto.CompactTextString(m) }
func (*BackupResponse) ProtoMessage()    {}
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{3}
}

func (m *BackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupResponse.Unmarshal(m, b)
}
func (m *BackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupResponse.Marshal(b, m, deterministic)
}
func (m *BackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupResponse.Merge(m, src)
}
func (m *BackupResponse) XXX_Size() int {
	return xxx_messageInfo_BackupResponse.Size(m)
}
func (m *BackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupResponse proto.InternalMessageInfo

func (m *BackupResponse) GetStatus() BackupResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return BackupResponse_OK
}

func (m *BackupResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type RestoreRequest struct {
	ServiceId            []byte   `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	BackupId             []byte   `protobuf:"bytes,2,opt,name=backup_id,json=backupId" json:"backup_id,omitempty"`
	Token                []byte   `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	ValidFrom            *uint64  `protobuf:"varint,4,opt,name=valid_from,json=validFrom" json:"valid_from,omitempty"`
	Pin                  []byte   `protobuf:"bytes,5,opt,name=pin" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{4}
}

func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (m *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(m, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetServiceId() []byte {
	if m != nil {
		return m.ServiceId
	}
	return nil
}

func (m *RestoreRequest) GetBackupId() []byte {
	if m != nil {
		return m.BackupId
	}
	return nil
}

func (m *RestoreRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *RestoreRequest) GetValidFrom() uint64 {
	if m != nil && m.ValidFrom != nil {
		return *m.ValidFrom
	}
	return 0
}

func (m *RestoreRequest) GetPin() []byte {
	if m != nil {
		return m.Pin
	}
	return nil
}

type RestoreResponse struct {
	Status               *RestoreResponse_Status `protobuf:"varint,1,opt,name=status,enum=textsecure.RestoreResponse_Status" json:"status,omitempty"`
	Token                []byte                  `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Data                 []byte                  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Tries                *uint32                 `protobuf:"varint,4,opt,name=tries" json:"tries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{5}
}

func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (m *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(m, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

func (m *RestoreResponse) GetStatus() RestoreResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return RestoreResponse_OK
}

func (m *RestoreResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *RestoreResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RestoreResponse) GetTries() uint32 {
	if m != nil && m.Tries != nil {
		return *m.Tries
	}
	return 0
}

type DeleteRequest struct {
	ServiceId            []byte   `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	BackupId             []byte   `protobuf:"bytes,2,opt,name=backup_id,json=backupId" json:"backup_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetServiceId() []byte {
	if m != nil {
		return m.ServiceId
	}
	return nil
}

func (m *DeleteRequest) GetBackupId() []byte {
	if m != nil {
		return m.BackupId
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c9075a509db6ac, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("textsecure.BackupResponse_Status", BackupResponse_Status_name, BackupResponse_Status_value)
	proto.RegisterEnum("textsecure.RestoreResponse_Status", RestoreResponse_Status_name, RestoreResponse_Status_value)
	proto.RegisterType((*Request)(nil), "textsecure.Request")
	proto.RegisterType((*Response)(nil), "textsecure.Response")
	proto.RegisterType((*BackupRequest)(nil), "textsecure.BackupRequest")
	proto.RegisterType((*BackupResponse)(nil), "textsecure.BackupResponse")
	proto.RegisterType((*RestoreRequest)(nil), "textsecure.RestoreRequest")
	proto.RegisterType((*RestoreResponse)(nil), "textsecure.RestoreResponse")
	proto.RegisterType((*DeleteRequest)(nil), "textsecure.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "textsecure.DeleteResponse")
}

func init() { proto.RegisterFile("KeyBackupService.proto", fileDescriptor_52c9075a509db6ac) }

var fileDescriptor_52c9075a509db6ac = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x8e, 0xd2, 0x4e,
	0x14, 0xc7, 0x33, 0xfc, 0x5d, 0xce, 0x02, 0xbf, 0xfe, 0x26, 0xc6, 0x54, 0x36, 0x26, 0xd8, 0x2b,
	0xae, 0x9a, 0x48, 0x34, 0xc6, 0xbd, 0x30, 0x61, 0x05, 0xb5, 0x61, 0x81, 0xcd, 0x94, 0x6c, 0xdc,
	0xab, 0xa6, 0xd2, 0xe3, 0xda, 0x00, 0x2d, 0xce, 0x0c, 0xab, 0x3c, 0x87, 0x77, 0xde, 0x7b, 0xe1,
	0x3b, 0xf8, 0x3a, 0xbe, 0x87, 0x61, 0xa6, 0x74, 0xa1, 0x56, 0x63, 0x62, 0xe2, 0x5d, 0xe7, 0x9c,
	0xef, 0x39, 0xe7, 0x93, 0xef, 0x99, 0x29, 0xdc, 0x1d, 0xe2, 0xe6, 0xcc, 0x9f, 0xcd, 0xd7, 0x2b,
	0x17, 0xf9, 0x4d, 0x38, 0x43, 0x7b, 0xc5, 0x63, 0x19, 0x53, 0x90, 0xf8, 0x51, 0x0a, 0x9c, 0xad,
	0x39, 0x5a, 0x5f, 0x08, 0x54, 0x19, 0xbe, 0x5f, 0xa3, 0x90, 0xf4, 0x21, 0x54, 0xde, 0x28, 0xb9,
	0x49, 0xda, 0xa4, 0x73, 0xdc, 0xbd, 0x67, 0xdf, 0x0a, 0x6d, 0xdd, 0x28, 0x91, 0xb2, 0x44, 0x48,
	0x1f, 0x41, 0x95, 0xa3, 0x90, 0x31, 0x47, 0xb3, 0xa0, 0x6a, 0x5a, 0xfb, 0x35, 0x4c, 0xa7, 0x76,
	0x45, 0x3b, 0xe9, 0x76, 0x50, 0x80, 0x0b, 0x94, 0x68, 0x16, 0x7f, 0x1e, 0xd4, 0x57, 0x99, 0x74,
	0x90, 0x16, 0x5a, 0x5f, 0x09, 0x1c, 0x31, 0x14, 0xab, 0x38, 0x12, 0x48, 0xbb, 0x19, 0xd0, 0x56,
	0x1e, 0xa8, 0xd6, 0xa6, 0xa4, 0x8f, 0xb3, 0xa4, 0x27, 0xb9, 0xa4, 0x49, 0x55, 0x8a, 0xda, 0xcd,
	0xa0, 0xb6, 0xf2, 0x50, 0x77, 0xa3, 0x12, 0xd6, 0x6f, 0x04, 0x1a, 0x07, 0x76, 0xd1, 0xfb, 0x00,
	0x42, 0xaf, 0xc0, 0x0b, 0x03, 0x05, 0x5d, 0x67, 0xb5, 0x24, 0xe2, 0x04, 0xf4, 0x04, 0x6a, 0x9a,
	0x72, 0x9b, 0x2d, 0xa8, 0xec, 0x91, 0x0e, 0x38, 0x01, 0xbd, 0x03, 0x65, 0x19, 0xcf, 0x31, 0x52,
	0x00, 0x75, 0xa6, 0x0f, 0xdb, 0x8e, 0x37, 0xfe, 0x22, 0x0c, 0xbc, 0xb7, 0x3c, 0x5e, 0x9a, 0xa5,
	0x36, 0xe9, 0x94, 0x58, 0x4d, 0x45, 0x5e, 0xf0, 0x78, 0x49, 0x29, 0x94, 0x02, 0x5f, 0xfa, 0x66,
	0x59, 0xd5, 0xa8, 0x6f, 0x6a, 0x40, 0x71, 0x15, 0x46, 0x66, 0x45, 0x85, 0xb6, 0x9f, 0xaa, 0x35,
	0x0f, 0x51, 0x98, 0xd5, 0x36, 0xe9, 0x34, 0x98, 0x3e, 0x58, 0x9f, 0x09, 0x34, 0x0f, 0x4d, 0xa4,
	0x4f, 0xa1, 0x22, 0xa4, 0x2f, 0xd7, 0x42, 0xb1, 0x37, 0xbb, 0x0f, 0x7e, 0x6d, 0xb8, 0xed, 0x2a,
	0x21, 0x4b, 0x0a, 0x6e, 0xf1, 0x0b, 0x7b, 0xf8, 0xd6, 0x13, 0xa8, 0x68, 0x1d, 0xad, 0x40, 0x61,
	0x32, 0x34, 0x08, 0xa5, 0xd0, 0xec, 0x9d, 0xb3, 0x41, 0xaf, 0x7f, 0xe5, 0x0d, 0x5e, 0x3b, 0xee,
	0xd4, 0x35, 0x0a, 0xf4, 0x7f, 0x68, 0x8c, 0x27, 0x53, 0xef, 0x6a, 0x30, 0xf5, 0x2e, 0x7b, 0xe7,
	0x4e, 0xdf, 0x28, 0x5a, 0x9f, 0x08, 0x34, 0x0f, 0xaf, 0xd5, 0xbf, 0x37, 0x37, 0x31, 0xb2, 0x9c,
	0x1a, 0x69, 0x7d, 0x27, 0xf0, 0x5f, 0xe6, 0x0a, 0xd1, 0xd3, 0x8c, 0x67, 0xd6, 0x6f, 0xee, 0xdb,
	0x1f, 0x99, 0x96, 0x2e, 0xb5, 0xb8, 0xb7, 0xd4, 0x74, 0x85, 0xa5, 0xfd, 0x15, 0x5e, 0xe6, 0xd9,
	0x3b, 0x9d, 0x0c, 0x07, 0x63, 0x6f, 0xe4, 0xb8, 0xa3, 0xde, 0xf4, 0xf9, 0xab, 0x5c, 0x7b, 0xe9,
	0x31, 0x54, 0x47, 0x8e, 0xeb, 0x3a, 0xe3, 0x97, 0x46, 0x89, 0x1a, 0x50, 0xbf, 0x70, 0xf6, 0x2a,
	0xca, 0xd6, 0x10, 0x1a, 0x07, 0xcf, 0xf3, 0x6f, 0xbc, 0xb7, 0x0c, 0x68, 0x1e, 0x3e, 0xa0, 0xb3,
	0x67, 0x70, 0x1a, 0xf3, 0x6b, 0xfb, 0xc3, 0xbb, 0x50, 0xac, 0x90, 0x8b, 0x8d, 0x90, 0xb8, 0x14,
	0xb6, 0x08, 0xaf, 0x23, 0x7f, 0x91, 0x34, 0xb5, 0xc3, 0x48, 0x22, 0x8f, 0xfc, 0x85, 0x3d, 0xc7,
	0x8d, 0x6e, 0xa5, 0xff, 0x6a, 0xe2, 0x82, 0xfc, 0x08, 0x00, 0x00, 0xff, 0xff, 0x50, 0x7d, 0x1f,
	0x28, 0xf1, 0x04, 0x00, 0x00,
}
