// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ResumableUploads.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResumableUpload struct {
	SecretKey            []byte   `protobuf:"bytes,1,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Iv                   []byte   `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	CdnKey               string   `protobuf:"bytes,3,opt,name=cdnKey,proto3" json:"cdnKey,omitempty"`
	CdnNumber            uint32   `protobuf:"varint,4,opt,name=cdnNumber,proto3" json:"cdnNumber,omitempty"`
	Location             string   `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Timeout              uint64   `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumableUpload) Reset()         { *m = ResumableUpload{} }
func (m *ResumableUpload) String() string { return proto.CompactTextString(m) }
func (*ResumableUpload) ProtoMessage()    {}
func (*ResumableUpload) Descriptor() ([]byte, []int) {
	return fileDescriptor_3818b8ff14f50ede, []int{0}
}

func (m *ResumableUpload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumableUpload.Unmarshal(m, b)
}
func (m *ResumableUpload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumableUpload.Marshal(b, m, deterministic)
}
func (m *ResumableUpload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumableUpload.Merge(m, src)
}
func (m *ResumableUpload) XXX_Size() int {
	return xxx_messageInfo_ResumableUpload.Size(m)
}
func (m *ResumableUpload) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumableUpload.DiscardUnknown(m)
}

var xxx_messageInfo_ResumableUpload proto.InternalMessageInfo

func (m *ResumableUpload) GetSecretKey() []byte {
	if m != nil {
		return m.SecretKey
	}
	return nil
}

func (m *ResumableUpload) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *ResumableUpload) GetCdnKey() string {
	if m != nil {
		return m.CdnKey
	}
	return ""
}

func (m *ResumableUpload) GetCdnNumber() uint32 {
	if m != nil {
		return m.CdnNumber
	}
	return 0
}

func (m *ResumableUpload) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ResumableUpload) GetTimeout() uint64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func init() {
	proto.RegisterType((*ResumableUpload)(nil), "ResumableUpload")
}

func init() { proto.RegisterFile("ResumableUploads.proto", fileDescriptor_3818b8ff14f50ede) }

var fileDescriptor_3818b8ff14f50ede = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0b, 0x4a, 0x2d, 0x2e,
	0xcd, 0x4d, 0x4c, 0xca, 0x49, 0x0d, 0x2d, 0xc8, 0xc9, 0x4f, 0x4c, 0x29, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0x5a, 0xcd, 0xc8, 0xc5, 0x8f, 0x26, 0x25, 0x24, 0xc3, 0xc5, 0x59, 0x9c, 0x9a,
	0x5c, 0x94, 0x5a, 0xe2, 0x9d, 0x5a, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0x84, 0x10, 0x10,
	0xe2, 0xe3, 0x62, 0xca, 0x2c, 0x93, 0x60, 0x02, 0x0b, 0x33, 0x65, 0x96, 0x09, 0x89, 0x71, 0xb1,
	0x25, 0xa7, 0xe4, 0x81, 0x94, 0x32, 0x2b, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x20, 0x53, 0x92,
	0x53, 0xf2, 0xfc, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x24, 0x58, 0x14, 0x18, 0x35, 0x78, 0x83, 0x10,
	0x02, 0x42, 0x52, 0x5c, 0x1c, 0x39, 0xf9, 0xc9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x12, 0xac, 0x60,
	0x7d, 0x70, 0xbe, 0x90, 0x04, 0x17, 0x7b, 0x49, 0x66, 0x6e, 0x6a, 0x7e, 0x69, 0x89, 0x04, 0x9b,
	0x02, 0xa3, 0x06, 0x4b, 0x10, 0x8c, 0xeb, 0xa4, 0xc2, 0xa5, 0x94, 0x5f, 0x94, 0xae, 0x57, 0x9c,
	0x99, 0x9e, 0x97, 0x98, 0x03, 0xf1, 0x41, 0xb1, 0x5e, 0x11, 0xcc, 0xf9, 0xa5, 0x10, 0x9f, 0x25,
	0xb1, 0x81, 0x25, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x99, 0xd7, 0x1a, 0xf4, 0x00,
	0x00, 0x00,
}
