// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SignalStorage.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ManifestRecord_Identifier_Type int32

const (
	ManifestRecord_Identifier_UNKNOWN ManifestRecord_Identifier_Type = 0
	ManifestRecord_Identifier_CONTACT ManifestRecord_Identifier_Type = 1
	ManifestRecord_Identifier_GROUPV1 ManifestRecord_Identifier_Type = 2
	ManifestRecord_Identifier_GROUPV2 ManifestRecord_Identifier_Type = 3
	ManifestRecord_Identifier_ACCOUNT ManifestRecord_Identifier_Type = 4
)

var ManifestRecord_Identifier_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CONTACT",
	2: "GROUPV1",
	3: "GROUPV2",
	4: "ACCOUNT",
}

var ManifestRecord_Identifier_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"CONTACT": 1,
	"GROUPV1": 2,
	"GROUPV2": 3,
	"ACCOUNT": 4,
}

func (x ManifestRecord_Identifier_Type) String() string {
	return proto.EnumName(ManifestRecord_Identifier_Type_name, int32(x))
}

func (ManifestRecord_Identifier_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{5, 0, 0}
}

type ContactRecord_IdentityState int32

const (
	ContactRecord_DEFAULT    ContactRecord_IdentityState = 0
	ContactRecord_VERIFIED   ContactRecord_IdentityState = 1
	ContactRecord_UNVERIFIED ContactRecord_IdentityState = 2
)

var ContactRecord_IdentityState_name = map[int32]string{
	0: "DEFAULT",
	1: "VERIFIED",
	2: "UNVERIFIED",
}

var ContactRecord_IdentityState_value = map[string]int32{
	"DEFAULT":    0,
	"VERIFIED":   1,
	"UNVERIFIED": 2,
}

func (x ContactRecord_IdentityState) String() string {
	return proto.EnumName(ContactRecord_IdentityState_name, int32(x))
}

func (ContactRecord_IdentityState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{7, 0}
}

type StorageManifest struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageManifest) Reset()         { *m = StorageManifest{} }
func (m *StorageManifest) String() string { return proto.CompactTextString(m) }
func (*StorageManifest) ProtoMessage()    {}
func (*StorageManifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{0}
}

func (m *StorageManifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageManifest.Unmarshal(m, b)
}
func (m *StorageManifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageManifest.Marshal(b, m, deterministic)
}
func (m *StorageManifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageManifest.Merge(m, src)
}
func (m *StorageManifest) XXX_Size() int {
	return xxx_messageInfo_StorageManifest.Size(m)
}
func (m *StorageManifest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageManifest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageManifest proto.InternalMessageInfo

func (m *StorageManifest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *StorageManifest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StorageItem struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageItem) Reset()         { *m = StorageItem{} }
func (m *StorageItem) String() string { return proto.CompactTextString(m) }
func (*StorageItem) ProtoMessage()    {}
func (*StorageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{1}
}

func (m *StorageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageItem.Unmarshal(m, b)
}
func (m *StorageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageItem.Marshal(b, m, deterministic)
}
func (m *StorageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageItem.Merge(m, src)
}
func (m *StorageItem) XXX_Size() int {
	return xxx_messageInfo_StorageItem.Size(m)
}
func (m *StorageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageItem.DiscardUnknown(m)
}

var xxx_messageInfo_StorageItem proto.InternalMessageInfo

func (m *StorageItem) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *StorageItem) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StorageItems struct {
	Items                []*StorageItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StorageItems) Reset()         { *m = StorageItems{} }
func (m *StorageItems) String() string { return proto.CompactTextString(m) }
func (*StorageItems) ProtoMessage()    {}
func (*StorageItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{2}
}

func (m *StorageItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageItems.Unmarshal(m, b)
}
func (m *StorageItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageItems.Marshal(b, m, deterministic)
}
func (m *StorageItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageItems.Merge(m, src)
}
func (m *StorageItems) XXX_Size() int {
	return xxx_messageInfo_StorageItems.Size(m)
}
func (m *StorageItems) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageItems.DiscardUnknown(m)
}

var xxx_messageInfo_StorageItems proto.InternalMessageInfo

func (m *StorageItems) GetItems() []*StorageItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ReadOperation struct {
	ReadKey              [][]byte `protobuf:"bytes,1,rep,name=readKey,proto3" json:"readKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOperation) Reset()         { *m = ReadOperation{} }
func (m *ReadOperation) String() string { return proto.CompactTextString(m) }
func (*ReadOperation) ProtoMessage()    {}
func (*ReadOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{3}
}

func (m *ReadOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOperation.Unmarshal(m, b)
}
func (m *ReadOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOperation.Marshal(b, m, deterministic)
}
func (m *ReadOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOperation.Merge(m, src)
}
func (m *ReadOperation) XXX_Size() int {
	return xxx_messageInfo_ReadOperation.Size(m)
}
func (m *ReadOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOperation.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOperation proto.InternalMessageInfo

func (m *ReadOperation) GetReadKey() [][]byte {
	if m != nil {
		return m.ReadKey
	}
	return nil
}

type WriteOperation struct {
	Manifest             *StorageManifest `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	InsertItem           []*StorageItem   `protobuf:"bytes,2,rep,name=insertItem,proto3" json:"insertItem,omitempty"`
	DeleteKey            [][]byte         `protobuf:"bytes,3,rep,name=deleteKey,proto3" json:"deleteKey,omitempty"`
	ClearAll             bool             `protobuf:"varint,4,opt,name=clearAll,proto3" json:"clearAll,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WriteOperation) Reset()         { *m = WriteOperation{} }
func (m *WriteOperation) String() string { return proto.CompactTextString(m) }
func (*WriteOperation) ProtoMessage()    {}
func (*WriteOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{4}
}

func (m *WriteOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteOperation.Unmarshal(m, b)
}
func (m *WriteOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteOperation.Marshal(b, m, deterministic)
}
func (m *WriteOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteOperation.Merge(m, src)
}
func (m *WriteOperation) XXX_Size() int {
	return xxx_messageInfo_WriteOperation.Size(m)
}
func (m *WriteOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteOperation.DiscardUnknown(m)
}

var xxx_messageInfo_WriteOperation proto.InternalMessageInfo

func (m *WriteOperation) GetManifest() *StorageManifest {
	if m != nil {
		return m.Manifest
	}
	return nil
}

func (m *WriteOperation) GetInsertItem() []*StorageItem {
	if m != nil {
		return m.InsertItem
	}
	return nil
}

func (m *WriteOperation) GetDeleteKey() [][]byte {
	if m != nil {
		return m.DeleteKey
	}
	return nil
}

func (m *WriteOperation) GetClearAll() bool {
	if m != nil {
		return m.ClearAll
	}
	return false
}

type ManifestRecord struct {
	Version              uint64                       `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Identifiers          []*ManifestRecord_Identifier `protobuf:"bytes,2,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ManifestRecord) Reset()         { *m = ManifestRecord{} }
func (m *ManifestRecord) String() string { return proto.CompactTextString(m) }
func (*ManifestRecord) ProtoMessage()    {}
func (*ManifestRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{5}
}

func (m *ManifestRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestRecord.Unmarshal(m, b)
}
func (m *ManifestRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestRecord.Marshal(b, m, deterministic)
}
func (m *ManifestRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestRecord.Merge(m, src)
}
func (m *ManifestRecord) XXX_Size() int {
	return xxx_messageInfo_ManifestRecord.Size(m)
}
func (m *ManifestRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestRecord proto.InternalMessageInfo

func (m *ManifestRecord) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ManifestRecord) GetIdentifiers() []*ManifestRecord_Identifier {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

type ManifestRecord_Identifier struct {
	Raw                  []byte                         `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Type                 ManifestRecord_Identifier_Type `protobuf:"varint,2,opt,name=type,proto3,enum=signalservice.ManifestRecord_Identifier_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ManifestRecord_Identifier) Reset()         { *m = ManifestRecord_Identifier{} }
func (m *ManifestRecord_Identifier) String() string { return proto.CompactTextString(m) }
func (*ManifestRecord_Identifier) ProtoMessage()    {}
func (*ManifestRecord_Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{5, 0}
}

func (m *ManifestRecord_Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestRecord_Identifier.Unmarshal(m, b)
}
func (m *ManifestRecord_Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestRecord_Identifier.Marshal(b, m, deterministic)
}
func (m *ManifestRecord_Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestRecord_Identifier.Merge(m, src)
}
func (m *ManifestRecord_Identifier) XXX_Size() int {
	return xxx_messageInfo_ManifestRecord_Identifier.Size(m)
}
func (m *ManifestRecord_Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestRecord_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestRecord_Identifier proto.InternalMessageInfo

func (m *ManifestRecord_Identifier) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *ManifestRecord_Identifier) GetType() ManifestRecord_Identifier_Type {
	if m != nil {
		return m.Type
	}
	return ManifestRecord_Identifier_UNKNOWN
}

type StorageRecord struct {
	// Types that are valid to be assigned to Record:
	//	*StorageRecord_Contact
	//	*StorageRecord_GroupV1
	//	*StorageRecord_GroupV2
	//	*StorageRecord_Account
	Record               isStorageRecord_Record `protobuf_oneof:"record"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StorageRecord) Reset()         { *m = StorageRecord{} }
func (m *StorageRecord) String() string { return proto.CompactTextString(m) }
func (*StorageRecord) ProtoMessage()    {}
func (*StorageRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{6}
}

func (m *StorageRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRecord.Unmarshal(m, b)
}
func (m *StorageRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRecord.Marshal(b, m, deterministic)
}
func (m *StorageRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRecord.Merge(m, src)
}
func (m *StorageRecord) XXX_Size() int {
	return xxx_messageInfo_StorageRecord.Size(m)
}
func (m *StorageRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRecord.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRecord proto.InternalMessageInfo

type isStorageRecord_Record interface {
	isStorageRecord_Record()
}

type StorageRecord_Contact struct {
	Contact *ContactRecord `protobuf:"bytes,1,opt,name=contact,proto3,oneof"`
}

type StorageRecord_GroupV1 struct {
	GroupV1 *GroupV1Record `protobuf:"bytes,2,opt,name=groupV1,proto3,oneof"`
}

type StorageRecord_GroupV2 struct {
	GroupV2 *GroupV2Record `protobuf:"bytes,3,opt,name=groupV2,proto3,oneof"`
}

type StorageRecord_Account struct {
	Account *AccountRecord `protobuf:"bytes,4,opt,name=account,proto3,oneof"`
}

func (*StorageRecord_Contact) isStorageRecord_Record() {}

func (*StorageRecord_GroupV1) isStorageRecord_Record() {}

func (*StorageRecord_GroupV2) isStorageRecord_Record() {}

func (*StorageRecord_Account) isStorageRecord_Record() {}

func (m *StorageRecord) GetRecord() isStorageRecord_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *StorageRecord) GetContact() *ContactRecord {
	if x, ok := m.GetRecord().(*StorageRecord_Contact); ok {
		return x.Contact
	}
	return nil
}

func (m *StorageRecord) GetGroupV1() *GroupV1Record {
	if x, ok := m.GetRecord().(*StorageRecord_GroupV1); ok {
		return x.GroupV1
	}
	return nil
}

func (m *StorageRecord) GetGroupV2() *GroupV2Record {
	if x, ok := m.GetRecord().(*StorageRecord_GroupV2); ok {
		return x.GroupV2
	}
	return nil
}

func (m *StorageRecord) GetAccount() *AccountRecord {
	if x, ok := m.GetRecord().(*StorageRecord_Account); ok {
		return x.Account
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StorageRecord) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StorageRecord_Contact)(nil),
		(*StorageRecord_GroupV1)(nil),
		(*StorageRecord_GroupV2)(nil),
		(*StorageRecord_Account)(nil),
	}
}

type ContactRecord struct {
	ServiceUuid          string                      `protobuf:"bytes,1,opt,name=serviceUuid,proto3" json:"serviceUuid,omitempty"`
	ServiceE164          string                      `protobuf:"bytes,2,opt,name=serviceE164,proto3" json:"serviceE164,omitempty"`
	ProfileKey           []byte                      `protobuf:"bytes,3,opt,name=profileKey,proto3" json:"profileKey,omitempty"`
	IdentityKey          []byte                      `protobuf:"bytes,4,opt,name=identityKey,proto3" json:"identityKey,omitempty"`
	IdentityState        ContactRecord_IdentityState `protobuf:"varint,5,opt,name=identityState,proto3,enum=signalservice.ContactRecord_IdentityState" json:"identityState,omitempty"`
	GivenName            string                      `protobuf:"bytes,6,opt,name=givenName,proto3" json:"givenName,omitempty"`
	FamilyName           string                      `protobuf:"bytes,7,opt,name=familyName,proto3" json:"familyName,omitempty"`
	Username             string                      `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Blocked              bool                        `protobuf:"varint,9,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Whitelisted          bool                        `protobuf:"varint,10,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	Archived             bool                        `protobuf:"varint,11,opt,name=archived,proto3" json:"archived,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ContactRecord) Reset()         { *m = ContactRecord{} }
func (m *ContactRecord) String() string { return proto.CompactTextString(m) }
func (*ContactRecord) ProtoMessage()    {}
func (*ContactRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{7}
}

func (m *ContactRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactRecord.Unmarshal(m, b)
}
func (m *ContactRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactRecord.Marshal(b, m, deterministic)
}
func (m *ContactRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactRecord.Merge(m, src)
}
func (m *ContactRecord) XXX_Size() int {
	return xxx_messageInfo_ContactRecord.Size(m)
}
func (m *ContactRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ContactRecord proto.InternalMessageInfo

func (m *ContactRecord) GetServiceUuid() string {
	if m != nil {
		return m.ServiceUuid
	}
	return ""
}

func (m *ContactRecord) GetServiceE164() string {
	if m != nil {
		return m.ServiceE164
	}
	return ""
}

func (m *ContactRecord) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *ContactRecord) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *ContactRecord) GetIdentityState() ContactRecord_IdentityState {
	if m != nil {
		return m.IdentityState
	}
	return ContactRecord_DEFAULT
}

func (m *ContactRecord) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *ContactRecord) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *ContactRecord) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ContactRecord) GetBlocked() bool {
	if m != nil {
		return m.Blocked
	}
	return false
}

func (m *ContactRecord) GetWhitelisted() bool {
	if m != nil {
		return m.Whitelisted
	}
	return false
}

func (m *ContactRecord) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

type GroupV1Record struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Blocked              bool     `protobuf:"varint,2,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Whitelisted          bool     `protobuf:"varint,3,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	Archived             bool     `protobuf:"varint,4,opt,name=archived,proto3" json:"archived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupV1Record) Reset()         { *m = GroupV1Record{} }
func (m *GroupV1Record) String() string { return proto.CompactTextString(m) }
func (*GroupV1Record) ProtoMessage()    {}
func (*GroupV1Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{8}
}

func (m *GroupV1Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupV1Record.Unmarshal(m, b)
}
func (m *GroupV1Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupV1Record.Marshal(b, m, deterministic)
}
func (m *GroupV1Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupV1Record.Merge(m, src)
}
func (m *GroupV1Record) XXX_Size() int {
	return xxx_messageInfo_GroupV1Record.Size(m)
}
func (m *GroupV1Record) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupV1Record.DiscardUnknown(m)
}

var xxx_messageInfo_GroupV1Record proto.InternalMessageInfo

func (m *GroupV1Record) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GroupV1Record) GetBlocked() bool {
	if m != nil {
		return m.Blocked
	}
	return false
}

func (m *GroupV1Record) GetWhitelisted() bool {
	if m != nil {
		return m.Whitelisted
	}
	return false
}

func (m *GroupV1Record) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

type GroupV2Record struct {
	MasterKey            []byte   `protobuf:"bytes,1,opt,name=masterKey,proto3" json:"masterKey,omitempty"`
	Blocked              bool     `protobuf:"varint,2,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Whitelisted          bool     `protobuf:"varint,3,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	Archived             bool     `protobuf:"varint,4,opt,name=archived,proto3" json:"archived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupV2Record) Reset()         { *m = GroupV2Record{} }
func (m *GroupV2Record) String() string { return proto.CompactTextString(m) }
func (*GroupV2Record) ProtoMessage()    {}
func (*GroupV2Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{9}
}

func (m *GroupV2Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupV2Record.Unmarshal(m, b)
}
func (m *GroupV2Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupV2Record.Marshal(b, m, deterministic)
}
func (m *GroupV2Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupV2Record.Merge(m, src)
}
func (m *GroupV2Record) XXX_Size() int {
	return xxx_messageInfo_GroupV2Record.Size(m)
}
func (m *GroupV2Record) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupV2Record.DiscardUnknown(m)
}

var xxx_messageInfo_GroupV2Record proto.InternalMessageInfo

func (m *GroupV2Record) GetMasterKey() []byte {
	if m != nil {
		return m.MasterKey
	}
	return nil
}

func (m *GroupV2Record) GetBlocked() bool {
	if m != nil {
		return m.Blocked
	}
	return false
}

func (m *GroupV2Record) GetWhitelisted() bool {
	if m != nil {
		return m.Whitelisted
	}
	return false
}

func (m *GroupV2Record) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

type AccountRecord struct {
	ProfileKey             []byte `protobuf:"bytes,1,opt,name=profileKey,proto3" json:"profileKey,omitempty"`
	GivenName              string `protobuf:"bytes,2,opt,name=givenName,proto3" json:"givenName,omitempty"`
	FamilyName             string `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName,omitempty"`
	AvatarUrlPath          string `protobuf:"bytes,4,opt,name=avatarUrlPath,proto3" json:"avatarUrlPath,omitempty"`
	NoteToSelfArchived     bool   `protobuf:"varint,5,opt,name=noteToSelfArchived,proto3" json:"noteToSelfArchived,omitempty"`
	ReadReceipts           bool   `protobuf:"varint,6,opt,name=readReceipts,proto3" json:"readReceipts,omitempty"`
	SealedSenderIndicators bool   `protobuf:"varint,7,opt,name=sealedSenderIndicators,proto3" json:"sealedSenderIndicators,omitempty"`
	TypingIndicators       bool   `protobuf:"varint,8,opt,name=typingIndicators,proto3" json:"typingIndicators,omitempty"`
	ProxiedLinkPreviews    bool   `protobuf:"varint,9,opt,name=proxiedLinkPreviews,proto3" json:"proxiedLinkPreviews,omitempty"`
	// 10 is reserved for unread
	LinkPreviews         bool     `protobuf:"varint,11,opt,name=linkPreviews,proto3" json:"linkPreviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRecord) Reset()         { *m = AccountRecord{} }
func (m *AccountRecord) String() string { return proto.CompactTextString(m) }
func (*AccountRecord) ProtoMessage()    {}
func (*AccountRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbf53b35b6c1982, []int{10}
}

func (m *AccountRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRecord.Unmarshal(m, b)
}
func (m *AccountRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRecord.Marshal(b, m, deterministic)
}
func (m *AccountRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRecord.Merge(m, src)
}
func (m *AccountRecord) XXX_Size() int {
	return xxx_messageInfo_AccountRecord.Size(m)
}
func (m *AccountRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRecord proto.InternalMessageInfo

func (m *AccountRecord) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *AccountRecord) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *AccountRecord) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *AccountRecord) GetAvatarUrlPath() string {
	if m != nil {
		return m.AvatarUrlPath
	}
	return ""
}

func (m *AccountRecord) GetNoteToSelfArchived() bool {
	if m != nil {
		return m.NoteToSelfArchived
	}
	return false
}

func (m *AccountRecord) GetReadReceipts() bool {
	if m != nil {
		return m.ReadReceipts
	}
	return false
}

func (m *AccountRecord) GetSealedSenderIndicators() bool {
	if m != nil {
		return m.SealedSenderIndicators
	}
	return false
}

func (m *AccountRecord) GetTypingIndicators() bool {
	if m != nil {
		return m.TypingIndicators
	}
	return false
}

func (m *AccountRecord) GetProxiedLinkPreviews() bool {
	if m != nil {
		return m.ProxiedLinkPreviews
	}
	return false
}

func (m *AccountRecord) GetLinkPreviews() bool {
	if m != nil {
		return m.LinkPreviews
	}
	return false
}

func init() {
	proto.RegisterEnum("signalservice.ManifestRecord_Identifier_Type", ManifestRecord_Identifier_Type_name, ManifestRecord_Identifier_Type_value)
	proto.RegisterEnum("signalservice.ContactRecord_IdentityState", ContactRecord_IdentityState_name, ContactRecord_IdentityState_value)
	proto.RegisterType((*StorageManifest)(nil), "signalservice.StorageManifest")
	proto.RegisterType((*StorageItem)(nil), "signalservice.StorageItem")
	proto.RegisterType((*StorageItems)(nil), "signalservice.StorageItems")
	proto.RegisterType((*ReadOperation)(nil), "signalservice.ReadOperation")
	proto.RegisterType((*WriteOperation)(nil), "signalservice.WriteOperation")
	proto.RegisterType((*ManifestRecord)(nil), "signalservice.ManifestRecord")
	proto.RegisterType((*ManifestRecord_Identifier)(nil), "signalservice.ManifestRecord.Identifier")
	proto.RegisterType((*StorageRecord)(nil), "signalservice.StorageRecord")
	proto.RegisterType((*ContactRecord)(nil), "signalservice.ContactRecord")
	proto.RegisterType((*GroupV1Record)(nil), "signalservice.GroupV1Record")
	proto.RegisterType((*GroupV2Record)(nil), "signalservice.GroupV2Record")
	proto.RegisterType((*AccountRecord)(nil), "signalservice.AccountRecord")
}

func init() { proto.RegisterFile("SignalStorage.proto", fileDescriptor_cbbf53b35b6c1982) }

var fileDescriptor_cbbf53b35b6c1982 = []byte{
	// 909 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xd1, 0x6e, 0xe2, 0x46,
	0x14, 0x5d, 0xdb, 0x24, 0x21, 0x17, 0x48, 0xd1, 0x6c, 0x55, 0x59, 0xd1, 0x6a, 0x15, 0x59, 0x7d,
	0xa0, 0x2b, 0x15, 0x6d, 0x68, 0xbb, 0x5a, 0x45, 0x7d, 0x28, 0xcb, 0x66, 0x53, 0x9a, 0x2d, 0xa0,
	0x01, 0xb2, 0xcf, 0xb3, 0xf6, 0x85, 0x8c, 0x62, 0x6c, 0x6b, 0x3c, 0x40, 0x79, 0xec, 0x43, 0x3f,
	0xa4, 0xea, 0x5b, 0x3f, 0xa3, 0xff, 0xd0, 0xff, 0xa9, 0x66, 0x6c, 0x63, 0x1b, 0xb2, 0xb4, 0x2f,
	0x7d, 0xf3, 0x3d, 0xf7, 0x9c, 0x99, 0x33, 0x73, 0xcf, 0x84, 0xc0, 0xd3, 0x31, 0x9f, 0x07, 0xcc,
	0x1f, 0xcb, 0x50, 0xb0, 0x39, 0xb6, 0x23, 0x11, 0xca, 0x90, 0x34, 0x62, 0x0d, 0xc6, 0x28, 0x56,
	0xdc, 0x45, 0xa7, 0x0b, 0x9f, 0xa5, 0xfd, 0x9f, 0x59, 0xc0, 0x67, 0x18, 0x4b, 0x62, 0xc3, 0xc9,
	0x0a, 0x45, 0xcc, 0xc3, 0xc0, 0x36, 0x2e, 0x8c, 0x56, 0x85, 0x66, 0x25, 0xf9, 0x1c, 0x8e, 0x56,
	0xcc, 0x5f, 0xa2, 0x6d, 0x5e, 0x18, 0xad, 0x3a, 0x4d, 0x0a, 0xe7, 0x3b, 0xa8, 0xa5, 0x4b, 0xf4,
	0x25, 0x2e, 0x48, 0x13, 0xac, 0x07, 0xdc, 0x68, 0x69, 0x9d, 0xaa, 0xcf, 0x4f, 0xc8, 0x7e, 0x80,
	0x7a, 0x41, 0x16, 0x93, 0x97, 0x70, 0xc4, 0xd5, 0x87, 0x6d, 0x5c, 0x58, 0xad, 0x5a, 0xe7, 0xbc,
	0x5d, 0x32, 0xda, 0x2e, 0x70, 0x69, 0x42, 0x74, 0xbe, 0x82, 0x06, 0x45, 0xe6, 0x0d, 0x23, 0x14,
	0x4c, 0x2a, 0x7f, 0x36, 0x9c, 0x08, 0x64, 0xde, 0xad, 0xde, 0xde, 0x6a, 0xd5, 0x69, 0x56, 0x3a,
	0x7f, 0x19, 0x70, 0xf6, 0x41, 0x70, 0x89, 0x39, 0xf9, 0x0a, 0xaa, 0x8b, 0xf4, 0xc8, 0xda, 0x6c,
	0xad, 0xf3, 0xfc, 0xf1, 0x2d, 0xb3, 0x8b, 0xa1, 0x5b, 0x3e, 0xb9, 0x02, 0xe0, 0x41, 0x8c, 0x42,
	0x2a, 0x3b, 0xb6, 0xf9, 0xaf, 0x86, 0x0b, 0x6c, 0xf2, 0x0c, 0x4e, 0x3d, 0xf4, 0x51, 0xa2, 0xb2,
	0x69, 0x69, 0x9b, 0x39, 0x40, 0xce, 0xa1, 0xea, 0xfa, 0xc8, 0x44, 0xd7, 0xf7, 0xed, 0xca, 0x85,
	0xd1, 0xaa, 0xd2, 0x6d, 0xed, 0xfc, 0x61, 0xc2, 0xd9, 0xd6, 0x0c, 0xba, 0xa1, 0xf0, 0x0e, 0xcc,
	0xea, 0x27, 0xa8, 0x71, 0x0f, 0x03, 0xc9, 0x67, 0x1c, 0x45, 0x9c, 0x7a, 0x6c, 0xed, 0x78, 0x2c,
	0xaf, 0xd6, 0xee, 0x6f, 0x05, 0xb4, 0x28, 0x3e, 0xff, 0xd3, 0x00, 0xc8, 0x7b, 0x6a, 0xc2, 0x82,
	0xad, 0xb3, 0x09, 0x0b, 0xb6, 0x26, 0x5d, 0xa8, 0xc8, 0x4d, 0x94, 0x0c, 0xf8, 0xac, 0xf3, 0xf5,
	0x7f, 0xdd, 0xa5, 0x3d, 0xd9, 0x44, 0x48, 0xb5, 0xd4, 0xb9, 0x81, 0x8a, 0xaa, 0x48, 0x0d, 0x4e,
	0xa6, 0x83, 0xdb, 0xc1, 0xf0, 0xc3, 0xa0, 0xf9, 0x44, 0x15, 0xbd, 0xe1, 0x60, 0xd2, 0xed, 0x4d,
	0x9a, 0x86, 0x2a, 0x6e, 0xe8, 0x70, 0x3a, 0xba, 0xbb, 0x6c, 0x9a, 0x79, 0xd1, 0x69, 0x5a, 0xaa,
	0xe8, 0xf6, 0x7a, 0xc3, 0xe9, 0x60, 0xd2, 0xac, 0x38, 0xbf, 0x9a, 0xd0, 0x48, 0xef, 0x3e, 0xbd,
	0xa4, 0xd7, 0x70, 0xe2, 0x86, 0x81, 0x64, 0x6e, 0x36, 0xe8, 0x67, 0x3b, 0x06, 0x7b, 0x49, 0x37,
	0xa1, 0xff, 0xf8, 0x84, 0x66, 0x74, 0xa5, 0x9c, 0x8b, 0x70, 0x19, 0xdd, 0x5d, 0xea, 0xa3, 0xed,
	0x2b, 0x6f, 0x92, 0x6e, 0xae, 0x4c, 0xe9, 0xb9, 0xb2, 0x63, 0x5b, 0x07, 0x94, 0x9d, 0x5d, 0x65,
	0x47, 0x29, 0x99, 0xeb, 0x86, 0xcb, 0x40, 0xea, 0x00, 0xec, 0x2b, 0xbb, 0x49, 0x37, 0x57, 0xa6,
	0xf4, 0x37, 0x55, 0x38, 0x16, 0x1a, 0x74, 0xfe, 0xb6, 0xa0, 0x51, 0x3a, 0x14, 0xb9, 0x80, 0x5a,
	0xaa, 0x9f, 0x2e, 0xb9, 0xa7, 0xef, 0xe1, 0x94, 0x16, 0xa1, 0x02, 0xe3, 0xfa, 0xf2, 0xd5, 0xb7,
	0xfa, 0xbc, 0x39, 0x43, 0x41, 0xe4, 0x39, 0x40, 0x24, 0xc2, 0x19, 0xf7, 0xd3, 0xe8, 0xaa, 0xf1,
	0x17, 0x10, 0xb5, 0x42, 0x92, 0x1a, 0xb9, 0x51, 0x84, 0x8a, 0x26, 0x14, 0x21, 0x32, 0x82, 0x46,
	0x56, 0x8e, 0x25, 0x93, 0x68, 0x1f, 0xe9, 0xc0, 0xbc, 0x38, 0x34, 0x8f, 0x34, 0x2f, 0xa9, 0x82,
	0x96, 0x17, 0x50, 0xaf, 0x69, 0xce, 0x57, 0x18, 0x0c, 0xd8, 0x02, 0xed, 0x63, 0xed, 0x39, 0x07,
	0x94, 0xe3, 0x19, 0x5b, 0x70, 0x7f, 0xa3, 0xdb, 0x27, 0xba, 0x5d, 0x40, 0xd4, 0x6b, 0x5b, 0xc6,
	0x28, 0x02, 0xd5, 0xad, 0xea, 0xee, 0xb6, 0x56, 0x4f, 0xeb, 0xa3, 0x1f, 0xba, 0x0f, 0xe8, 0xd9,
	0xa7, 0xfa, 0x21, 0x66, 0xa5, 0x3a, 0xe7, 0xfa, 0x9e, 0x4b, 0xf4, 0x79, 0x2c, 0xd1, 0xb3, 0x41,
	0x77, 0x8b, 0x90, 0x5a, 0x97, 0x09, 0xf7, 0x9e, 0xaf, 0xd0, 0xb3, 0x6b, 0xc9, 0x2b, 0xce, 0x6a,
	0xe7, 0x0a, 0x1a, 0xa5, 0x13, 0xa9, 0xf4, 0xbe, 0xbd, 0x7e, 0xd7, 0x9d, 0xbe, 0x9f, 0x34, 0x9f,
	0x90, 0x3a, 0x54, 0xef, 0xae, 0x69, 0xff, 0x5d, 0xff, 0xfa, 0x6d, 0xd3, 0x20, 0x67, 0x00, 0xd3,
	0xc1, 0xb6, 0x36, 0x9d, 0x35, 0x34, 0x4a, 0x89, 0x23, 0x67, 0x60, 0xa6, 0xd3, 0xac, 0x53, 0x93,
	0x7b, 0x45, 0xd3, 0xe6, 0x41, 0xd3, 0xd6, 0x61, 0xd3, 0x95, 0x1d, 0xd3, 0xbf, 0x19, 0xd9, 0xce,
	0x69, 0x62, 0xd5, 0xc5, 0x2f, 0x58, 0x2c, 0x51, 0xdc, 0x6e, 0xff, 0xd8, 0xe7, 0xc0, 0xff, 0xe6,
	0xe3, 0x77, 0x0b, 0x1a, 0xa5, 0xfc, 0xef, 0x84, 0xd2, 0xd8, 0x0b, 0x65, 0x29, 0x20, 0xe6, 0xe1,
	0x80, 0x58, 0x7b, 0x01, 0xf9, 0x12, 0x1a, 0x6c, 0xc5, 0x24, 0x13, 0x53, 0xe1, 0x8f, 0x98, 0xbc,
	0xd7, 0x86, 0x4e, 0x69, 0x19, 0x24, 0x6d, 0x20, 0x41, 0x28, 0x71, 0x12, 0x8e, 0xd1, 0x9f, 0x75,
	0x33, 0xef, 0x47, 0xda, 0xfb, 0x23, 0x1d, 0xe2, 0x40, 0x5d, 0xfd, 0x30, 0x51, 0x74, 0x91, 0x47,
	0x32, 0xd6, 0xb9, 0xad, 0xd2, 0x12, 0x46, 0x5e, 0xc1, 0x17, 0x31, 0x32, 0x1f, 0xbd, 0x31, 0x06,
	0x1e, 0x8a, 0x7e, 0xe0, 0x71, 0x97, 0xc9, 0x50, 0xc4, 0x3a, 0xc6, 0x55, 0xfa, 0x89, 0x2e, 0x79,
	0x01, 0x4d, 0xb9, 0x89, 0x78, 0x30, 0x2f, 0x28, 0xaa, 0x5a, 0xb1, 0x87, 0x93, 0x97, 0xf0, 0x34,
	0x12, 0xe1, 0x2f, 0x1c, 0xbd, 0xf7, 0x3c, 0x78, 0x18, 0x09, 0x5c, 0x71, 0x5c, 0xc7, 0x69, 0xdc,
	0x1f, 0x6b, 0x29, 0xe7, 0x7e, 0x91, 0x9a, 0x84, 0xbb, 0x84, 0xbd, 0xf9, 0x1e, 0x5e, 0x87, 0x62,
	0xde, 0x5e, 0xdf, 0xf3, 0x38, 0x42, 0x11, 0x6f, 0x62, 0xf5, 0x63, 0xbd, 0xf3, 0xc2, 0x79, 0x20,
	0xd5, 0x33, 0xf3, 0xdb, 0x71, 0xf1, 0x9f, 0x93, 0x78, 0x64, 0x7c, 0x3c, 0xd6, 0x5f, 0xdf, 0xfc,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x31, 0x64, 0xcc, 0x80, 0xbd, 0x08, 0x00, 0x00,
}
