// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: LocalStorageProtocol.proto

//
// Copyright 2020 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

package textsecure

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SessionStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionVersion       uint32                  `protobuf:"varint,1,opt,name=session_version,json=sessionVersion,proto3" json:"session_version,omitempty"`
	LocalIdentityPublic  []byte                  `protobuf:"bytes,2,opt,name=local_identity_public,json=localIdentityPublic,proto3" json:"local_identity_public,omitempty"`
	RemoteIdentityPublic []byte                  `protobuf:"bytes,3,opt,name=remote_identity_public,json=remoteIdentityPublic,proto3" json:"remote_identity_public,omitempty"`
	RootKey              []byte                  `protobuf:"bytes,4,opt,name=root_key,json=rootKey,proto3" json:"root_key,omitempty"`
	PreviousCounter      uint32                  `protobuf:"varint,5,opt,name=previous_counter,json=previousCounter,proto3" json:"previous_counter,omitempty"`
	SenderChain          *SessionStructure_Chain `protobuf:"bytes,6,opt,name=sender_chain,json=senderChain,proto3" json:"sender_chain,omitempty"`
	// The order is significant; keys at the end are "older" and will get trimmed.
	ReceiverChains       []*SessionStructure_Chain       `protobuf:"bytes,7,rep,name=receiver_chains,json=receiverChains,proto3" json:"receiver_chains,omitempty"`
	PendingPreKey        *SessionStructure_PendingPreKey `protobuf:"bytes,9,opt,name=pending_pre_key,json=pendingPreKey,proto3" json:"pending_pre_key,omitempty"`
	RemoteRegistrationId uint32                          `protobuf:"varint,10,opt,name=remote_registration_id,json=remoteRegistrationId,proto3" json:"remote_registration_id,omitempty"`
	LocalRegistrationId  uint32                          `protobuf:"varint,11,opt,name=local_registration_id,json=localRegistrationId,proto3" json:"local_registration_id,omitempty"`
	NeedsRefresh         bool                            `protobuf:"varint,12,opt,name=needs_refresh,json=needsRefresh,proto3" json:"needs_refresh,omitempty"`
	AliceBaseKey         []byte                          `protobuf:"bytes,13,opt,name=alice_base_key,json=aliceBaseKey,proto3" json:"alice_base_key,omitempty"`
}

func (x *SessionStructure) Reset() {
	*x = SessionStructure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure) ProtoMessage() {}

func (x *SessionStructure) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure.ProtoReflect.Descriptor instead.
func (*SessionStructure) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *SessionStructure) GetSessionVersion() uint32 {
	if x != nil {
		return x.SessionVersion
	}
	return 0
}

func (x *SessionStructure) GetLocalIdentityPublic() []byte {
	if x != nil {
		return x.LocalIdentityPublic
	}
	return nil
}

func (x *SessionStructure) GetRemoteIdentityPublic() []byte {
	if x != nil {
		return x.RemoteIdentityPublic
	}
	return nil
}

func (x *SessionStructure) GetRootKey() []byte {
	if x != nil {
		return x.RootKey
	}
	return nil
}

func (x *SessionStructure) GetPreviousCounter() uint32 {
	if x != nil {
		return x.PreviousCounter
	}
	return 0
}

func (x *SessionStructure) GetSenderChain() *SessionStructure_Chain {
	if x != nil {
		return x.SenderChain
	}
	return nil
}

func (x *SessionStructure) GetReceiverChains() []*SessionStructure_Chain {
	if x != nil {
		return x.ReceiverChains
	}
	return nil
}

func (x *SessionStructure) GetPendingPreKey() *SessionStructure_PendingPreKey {
	if x != nil {
		return x.PendingPreKey
	}
	return nil
}

func (x *SessionStructure) GetRemoteRegistrationId() uint32 {
	if x != nil {
		return x.RemoteRegistrationId
	}
	return 0
}

func (x *SessionStructure) GetLocalRegistrationId() uint32 {
	if x != nil {
		return x.LocalRegistrationId
	}
	return 0
}

func (x *SessionStructure) GetNeedsRefresh() bool {
	if x != nil {
		return x.NeedsRefresh
	}
	return false
}

func (x *SessionStructure) GetAliceBaseKey() []byte {
	if x != nil {
		return x.AliceBaseKey
	}
	return nil
}

type RecordStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentSession *SessionStructure `protobuf:"bytes,1,opt,name=current_session,json=currentSession,proto3" json:"current_session,omitempty"`
	// The order is significant; sessions at the end are "older" and will get trimmed.
	PreviousSessions []*SessionStructure `protobuf:"bytes,2,rep,name=previous_sessions,json=previousSessions,proto3" json:"previous_sessions,omitempty"`
}

func (x *RecordStructure) Reset() {
	*x = RecordStructure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordStructure) ProtoMessage() {}

func (x *RecordStructure) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordStructure.ProtoReflect.Descriptor instead.
func (*RecordStructure) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *RecordStructure) GetCurrentSession() *SessionStructure {
	if x != nil {
		return x.CurrentSession
	}
	return nil
}

func (x *RecordStructure) GetPreviousSessions() []*SessionStructure {
	if x != nil {
		return x.PreviousSessions
	}
	return nil
}

type PreKeyRecordStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey  []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey []byte `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *PreKeyRecordStructure) Reset() {
	*x = PreKeyRecordStructure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreKeyRecordStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyRecordStructure) ProtoMessage() {}

func (x *PreKeyRecordStructure) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyRecordStructure.ProtoReflect.Descriptor instead.
func (*PreKeyRecordStructure) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{2}
}

func (x *PreKeyRecordStructure) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PreKeyRecordStructure) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PreKeyRecordStructure) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type SignedPreKeyRecordStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey  []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey []byte `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Signature  []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp  uint64 `protobuf:"fixed64,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SignedPreKeyRecordStructure) Reset() {
	*x = SignedPreKeyRecordStructure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedPreKeyRecordStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPreKeyRecordStructure) ProtoMessage() {}

func (x *SignedPreKeyRecordStructure) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPreKeyRecordStructure.ProtoReflect.Descriptor instead.
func (*SignedPreKeyRecordStructure) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{3}
}

func (x *SignedPreKeyRecordStructure) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SignedPreKeyRecordStructure) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedPreKeyRecordStructure) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *SignedPreKeyRecordStructure) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPreKeyRecordStructure) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IdentityKeyPairStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey []byte `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *IdentityKeyPairStructure) Reset() {
	*x = IdentityKeyPairStructure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityKeyPairStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityKeyPairStructure) ProtoMessage() {}

func (x *IdentityKeyPairStructure) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityKeyPairStructure.ProtoReflect.Descriptor instead.
func (*IdentityKeyPairStructure) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityKeyPairStructure) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *IdentityKeyPairStructure) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type SenderKeyStateStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageVersion    uint32                                      `protobuf:"varint,5,opt,name=message_version,json=messageVersion,proto3" json:"message_version,omitempty"`
	ChainId           uint32                                      `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	SenderChainKey    *SenderKeyStateStructure_SenderChainKey     `protobuf:"bytes,2,opt,name=sender_chain_key,json=senderChainKey,proto3" json:"sender_chain_key,omitempty"`
	SenderSigningKey  *SenderKeyStateStructure_SenderSigningKey   `protobuf:"bytes,3,opt,name=sender_signing_key,json=senderSigningKey,proto3" json:"sender_signing_key,omitempty"`
	SenderMessageKeys []*SenderKeyStateStructure_SenderMessageKey `protobuf:"bytes,4,rep,name=sender_message_keys,json=senderMessageKeys,proto3" json:"sender_message_keys,omitempty"`
}

func (x *SenderKeyStateStructure) Reset() {
	*x = SenderKeyStateStructure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderKeyStateStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyStateStructure) ProtoMessage() {}

func (x *SenderKeyStateStructure) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyStateStructure.ProtoReflect.Descriptor instead.
func (*SenderKeyStateStructure) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{5}
}

func (x *SenderKeyStateStructure) GetMessageVersion() uint32 {
	if x != nil {
		return x.MessageVersion
	}
	return 0
}

func (x *SenderKeyStateStructure) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SenderKeyStateStructure) GetSenderChainKey() *SenderKeyStateStructure_SenderChainKey {
	if x != nil {
		return x.SenderChainKey
	}
	return nil
}

func (x *SenderKeyStateStructure) GetSenderSigningKey() *SenderKeyStateStructure_SenderSigningKey {
	if x != nil {
		return x.SenderSigningKey
	}
	return nil
}

func (x *SenderKeyStateStructure) GetSenderMessageKeys() []*SenderKeyStateStructure_SenderMessageKey {
	if x != nil {
		return x.SenderMessageKeys
	}
	return nil
}

type SenderKeyRecordStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderKeyStates []*SenderKeyStateStructure `protobuf:"bytes,1,rep,name=sender_key_states,json=senderKeyStates,proto3" json:"sender_key_states,omitempty"`
}

func (x *SenderKeyRecordStructure) Reset() {
	*x = SenderKeyRecordStructure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderKeyRecordStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyRecordStructure) ProtoMessage() {}

func (x *SenderKeyRecordStructure) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyRecordStructure.ProtoReflect.Descriptor instead.
func (*SenderKeyRecordStructure) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{6}
}

func (x *SenderKeyRecordStructure) GetSenderKeyStates() []*SenderKeyStateStructure {
	if x != nil {
		return x.SenderKeyStates
	}
	return nil
}

type SessionStructure_Chain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderRatchetKey        []byte                               `protobuf:"bytes,1,opt,name=sender_ratchet_key,json=senderRatchetKey,proto3" json:"sender_ratchet_key,omitempty"`
	SenderRatchetKeyPrivate []byte                               `protobuf:"bytes,2,opt,name=sender_ratchet_key_private,json=senderRatchetKeyPrivate,proto3" json:"sender_ratchet_key_private,omitempty"`
	ChainKey                *SessionStructure_Chain_ChainKey     `protobuf:"bytes,3,opt,name=chain_key,json=chainKey,proto3" json:"chain_key,omitempty"`
	MessageKeys             []*SessionStructure_Chain_MessageKey `protobuf:"bytes,4,rep,name=message_keys,json=messageKeys,proto3" json:"message_keys,omitempty"`
}

func (x *SessionStructure_Chain) Reset() {
	*x = SessionStructure_Chain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStructure_Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_Chain) ProtoMessage() {}

func (x *SessionStructure_Chain) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_Chain.ProtoReflect.Descriptor instead.
func (*SessionStructure_Chain) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SessionStructure_Chain) GetSenderRatchetKey() []byte {
	if x != nil {
		return x.SenderRatchetKey
	}
	return nil
}

func (x *SessionStructure_Chain) GetSenderRatchetKeyPrivate() []byte {
	if x != nil {
		return x.SenderRatchetKeyPrivate
	}
	return nil
}

func (x *SessionStructure_Chain) GetChainKey() *SessionStructure_Chain_ChainKey {
	if x != nil {
		return x.ChainKey
	}
	return nil
}

func (x *SessionStructure_Chain) GetMessageKeys() []*SessionStructure_Chain_MessageKey {
	if x != nil {
		return x.MessageKeys
	}
	return nil
}

type SessionStructure_PendingPreKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreKeyId       uint32 `protobuf:"varint,1,opt,name=pre_key_id,json=preKeyId,proto3" json:"pre_key_id,omitempty"`
	SignedPreKeyId int32  `protobuf:"varint,3,opt,name=signed_pre_key_id,json=signedPreKeyId,proto3" json:"signed_pre_key_id,omitempty"`
	BaseKey        []byte `protobuf:"bytes,2,opt,name=base_key,json=baseKey,proto3" json:"base_key,omitempty"`
}

func (x *SessionStructure_PendingPreKey) Reset() {
	*x = SessionStructure_PendingPreKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStructure_PendingPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_PendingPreKey) ProtoMessage() {}

func (x *SessionStructure_PendingPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_PendingPreKey.ProtoReflect.Descriptor instead.
func (*SessionStructure_PendingPreKey) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SessionStructure_PendingPreKey) GetPreKeyId() uint32 {
	if x != nil {
		return x.PreKeyId
	}
	return 0
}

func (x *SessionStructure_PendingPreKey) GetSignedPreKeyId() int32 {
	if x != nil {
		return x.SignedPreKeyId
	}
	return 0
}

func (x *SessionStructure_PendingPreKey) GetBaseKey() []byte {
	if x != nil {
		return x.BaseKey
	}
	return nil
}

type SessionStructure_Chain_ChainKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Key   []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SessionStructure_Chain_ChainKey) Reset() {
	*x = SessionStructure_Chain_ChainKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStructure_Chain_ChainKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_Chain_ChainKey) ProtoMessage() {}

func (x *SessionStructure_Chain_ChainKey) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_Chain_ChainKey.ProtoReflect.Descriptor instead.
func (*SessionStructure_Chain_ChainKey) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SessionStructure_Chain_ChainKey) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SessionStructure_Chain_ChainKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SessionStructure_Chain_MessageKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CipherKey []byte `protobuf:"bytes,2,opt,name=cipher_key,json=cipherKey,proto3" json:"cipher_key,omitempty"`
	MacKey    []byte `protobuf:"bytes,3,opt,name=mac_key,json=macKey,proto3" json:"mac_key,omitempty"`
	Iv        []byte `protobuf:"bytes,4,opt,name=iv,proto3" json:"iv,omitempty"`
}

func (x *SessionStructure_Chain_MessageKey) Reset() {
	*x = SessionStructure_Chain_MessageKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStructure_Chain_MessageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_Chain_MessageKey) ProtoMessage() {}

func (x *SessionStructure_Chain_MessageKey) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_Chain_MessageKey.ProtoReflect.Descriptor instead.
func (*SessionStructure_Chain_MessageKey) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *SessionStructure_Chain_MessageKey) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SessionStructure_Chain_MessageKey) GetCipherKey() []byte {
	if x != nil {
		return x.CipherKey
	}
	return nil
}

func (x *SessionStructure_Chain_MessageKey) GetMacKey() []byte {
	if x != nil {
		return x.MacKey
	}
	return nil
}

func (x *SessionStructure_Chain_MessageKey) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

type SenderKeyStateStructure_SenderChainKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iteration uint32 `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	Seed      []byte `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *SenderKeyStateStructure_SenderChainKey) Reset() {
	*x = SenderKeyStateStructure_SenderChainKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderKeyStateStructure_SenderChainKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyStateStructure_SenderChainKey) ProtoMessage() {}

func (x *SenderKeyStateStructure_SenderChainKey) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyStateStructure_SenderChainKey.ProtoReflect.Descriptor instead.
func (*SenderKeyStateStructure_SenderChainKey) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SenderKeyStateStructure_SenderChainKey) GetIteration() uint32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *SenderKeyStateStructure_SenderChainKey) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type SenderKeyStateStructure_SenderMessageKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iteration uint32 `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	Seed      []byte `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *SenderKeyStateStructure_SenderMessageKey) Reset() {
	*x = SenderKeyStateStructure_SenderMessageKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderKeyStateStructure_SenderMessageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyStateStructure_SenderMessageKey) ProtoMessage() {}

func (x *SenderKeyStateStructure_SenderMessageKey) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyStateStructure_SenderMessageKey.ProtoReflect.Descriptor instead.
func (*SenderKeyStateStructure_SenderMessageKey) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{5, 1}
}

func (x *SenderKeyStateStructure_SenderMessageKey) GetIteration() uint32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *SenderKeyStateStructure_SenderMessageKey) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type SenderKeyStateStructure_SenderSigningKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Public  []byte `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private []byte `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *SenderKeyStateStructure_SenderSigningKey) Reset() {
	*x = SenderKeyStateStructure_SenderSigningKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LocalStorageProtocol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderKeyStateStructure_SenderSigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyStateStructure_SenderSigningKey) ProtoMessage() {}

func (x *SenderKeyStateStructure_SenderSigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_LocalStorageProtocol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyStateStructure_SenderSigningKey.ProtoReflect.Descriptor instead.
func (*SenderKeyStateStructure_SenderSigningKey) Descriptor() ([]byte, []int) {
	return file_LocalStorageProtocol_proto_rawDescGZIP(), []int{5, 2}
}

func (x *SenderKeyStateStructure_SenderSigningKey) GetPublic() []byte {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *SenderKeyStateStructure_SenderSigningKey) GetPrivate() []byte {
	if x != nil {
		return x.Private
	}
	return nil
}

var File_LocalStorageProtocol_proto protoreflect.FileDescriptor

var file_LocalStorageProtocol_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x22, 0xe0, 0x09, 0x0a, 0x10, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x32, 0x0a, 0x15, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x13, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x12, 0x34, 0x0a, 0x16, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f,
	0x6f, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x6f,
	0x6f, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75,
	0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x12, 0x4f, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x12, 0x55, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x5c, 0x0a, 0x0f, 0x70, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x34, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x16, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x15,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x5f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x61,
	0x6c, 0x69, 0x63, 0x65, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x1a, 0xc2, 0x03, 0x0a, 0x05,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f,
	0x72, 0x61, 0x74, 0x63, 0x68, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x61, 0x74, 0x63, 0x68, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x12, 0x3b, 0x0a, 0x1a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x72, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x17, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x12, 0x52, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x08, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x4b, 0x65, 0x79, 0x12, 0x5a, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x73,
	0x1a, 0x32, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x1a, 0x6a, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x61, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x76,
	0x1a, 0x73, 0x0a, 0x0d, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12,
	0x29, 0x0a, 0x11, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x5f, 0x6b, 0x65,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x61,
	0x73, 0x65, 0x4b, 0x65, 0x79, 0x22, 0xb7, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x4f, 0x0a, 0x0f, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x53, 0x0a, 0x11, 0x70, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x10, 0x70,
	0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x67, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0xa9, 0x01, 0x0a, 0x1b, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x06, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x5a, 0x0a, 0x18, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x22, 0xf3, 0x04, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x66, 0x0a, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x6c, 0x0a, 0x12, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x4b, 0x65, 0x79, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e,
	0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x6e, 0x0a, 0x13, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x1a, 0x42, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x74, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x1a, 0x44, 0x0a, 0x10, 0x53, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64,
	0x1a, 0x44, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x75, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x59, 0x0a, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0f, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x3b, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LocalStorageProtocol_proto_rawDescOnce sync.Once
	file_LocalStorageProtocol_proto_rawDescData = file_LocalStorageProtocol_proto_rawDesc
)

func file_LocalStorageProtocol_proto_rawDescGZIP() []byte {
	file_LocalStorageProtocol_proto_rawDescOnce.Do(func() {
		file_LocalStorageProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_LocalStorageProtocol_proto_rawDescData)
	})
	return file_LocalStorageProtocol_proto_rawDescData
}

var file_LocalStorageProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_LocalStorageProtocol_proto_goTypes = []interface{}{
	(*SessionStructure)(nil),                         // 0: signal.proto.storage.SessionStructure
	(*RecordStructure)(nil),                          // 1: signal.proto.storage.RecordStructure
	(*PreKeyRecordStructure)(nil),                    // 2: signal.proto.storage.PreKeyRecordStructure
	(*SignedPreKeyRecordStructure)(nil),              // 3: signal.proto.storage.SignedPreKeyRecordStructure
	(*IdentityKeyPairStructure)(nil),                 // 4: signal.proto.storage.IdentityKeyPairStructure
	(*SenderKeyStateStructure)(nil),                  // 5: signal.proto.storage.SenderKeyStateStructure
	(*SenderKeyRecordStructure)(nil),                 // 6: signal.proto.storage.SenderKeyRecordStructure
	(*SessionStructure_Chain)(nil),                   // 7: signal.proto.storage.SessionStructure.Chain
	(*SessionStructure_PendingPreKey)(nil),           // 8: signal.proto.storage.SessionStructure.PendingPreKey
	(*SessionStructure_Chain_ChainKey)(nil),          // 9: signal.proto.storage.SessionStructure.Chain.ChainKey
	(*SessionStructure_Chain_MessageKey)(nil),        // 10: signal.proto.storage.SessionStructure.Chain.MessageKey
	(*SenderKeyStateStructure_SenderChainKey)(nil),   // 11: signal.proto.storage.SenderKeyStateStructure.SenderChainKey
	(*SenderKeyStateStructure_SenderMessageKey)(nil), // 12: signal.proto.storage.SenderKeyStateStructure.SenderMessageKey
	(*SenderKeyStateStructure_SenderSigningKey)(nil), // 13: signal.proto.storage.SenderKeyStateStructure.SenderSigningKey
}
var file_LocalStorageProtocol_proto_depIdxs = []int32{
	7,  // 0: signal.proto.storage.SessionStructure.sender_chain:type_name -> signal.proto.storage.SessionStructure.Chain
	7,  // 1: signal.proto.storage.SessionStructure.receiver_chains:type_name -> signal.proto.storage.SessionStructure.Chain
	8,  // 2: signal.proto.storage.SessionStructure.pending_pre_key:type_name -> signal.proto.storage.SessionStructure.PendingPreKey
	0,  // 3: signal.proto.storage.RecordStructure.current_session:type_name -> signal.proto.storage.SessionStructure
	0,  // 4: signal.proto.storage.RecordStructure.previous_sessions:type_name -> signal.proto.storage.SessionStructure
	11, // 5: signal.proto.storage.SenderKeyStateStructure.sender_chain_key:type_name -> signal.proto.storage.SenderKeyStateStructure.SenderChainKey
	13, // 6: signal.proto.storage.SenderKeyStateStructure.sender_signing_key:type_name -> signal.proto.storage.SenderKeyStateStructure.SenderSigningKey
	12, // 7: signal.proto.storage.SenderKeyStateStructure.sender_message_keys:type_name -> signal.proto.storage.SenderKeyStateStructure.SenderMessageKey
	5,  // 8: signal.proto.storage.SenderKeyRecordStructure.sender_key_states:type_name -> signal.proto.storage.SenderKeyStateStructure
	9,  // 9: signal.proto.storage.SessionStructure.Chain.chain_key:type_name -> signal.proto.storage.SessionStructure.Chain.ChainKey
	10, // 10: signal.proto.storage.SessionStructure.Chain.message_keys:type_name -> signal.proto.storage.SessionStructure.Chain.MessageKey
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_LocalStorageProtocol_proto_init() }
func file_LocalStorageProtocol_proto_init() {
	if File_LocalStorageProtocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LocalStorageProtocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStructure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordStructure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreKeyRecordStructure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedPreKeyRecordStructure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityKeyPairStructure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderKeyStateStructure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderKeyRecordStructure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStructure_Chain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStructure_PendingPreKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStructure_Chain_ChainKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStructure_Chain_MessageKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderKeyStateStructure_SenderChainKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderKeyStateStructure_SenderMessageKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LocalStorageProtocol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderKeyStateStructure_SenderSigningKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LocalStorageProtocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_LocalStorageProtocol_proto_goTypes,
		DependencyIndexes: file_LocalStorageProtocol_proto_depIdxs,
		MessageInfos:      file_LocalStorageProtocol_proto_msgTypes,
	}.Build()
	File_LocalStorageProtocol_proto = out.File
	file_LocalStorageProtocol_proto_rawDesc = nil
	file_LocalStorageProtocol_proto_goTypes = nil
	file_LocalStorageProtocol_proto_depIdxs = nil
}
